#!/usr/bin/env -S guile --no-auto-compile -s
!#
(use-modules (ice-9 popen) (ice-9 textual-ports) (sxml simple) (srfi srfi-64))
(define root (cadr (command-line)))
(define id "20260926T120000Z-00c0de")
(define dir (string-append root "/" id))
(mkdir dir)
(define meta (string-append dir "/notebook.json"))
(define page (string-append dir "/page-0.jsonl"))
(define truth (string-append root "/truth.txt"))
(define (put path text) (call-with-output-file path (lambda (p) (display text p))))
(define (get path) (call-with-input-file path get-string-all))
(put meta (string-append "{\"format\":\"wilkbook-notebook\",\"v\":1,\"id\":\"" id
                        "\",\"created\":0,\"abs\":[20966,15725,4095],\"panel\":[1872,1404,227]}\n"))
(define record "{\"k\":\"s\",\"a\":1,\"tool\":\"pen\",\"brush\":\"fine\",\"size\":\"M\",\"st\":[135,135,100,100,4095,100,100],\"comp\":\"black\",\"pat\":\"solid\",\"rot\":0,\"t0\":1000,\"gap\":0,\"bb\":[0,0,1871,1403],\"d\":[0,0,0,100,-2,3,1000,20966,15725,100,6,-8]}")
(put page (string-append record "\n"))
(put truth "A café & <a book>.\n")
(define (run)
  (let* ((p (open-pipe* OPEN_READ "luajit" "export-line.lua" root id "0" truth))
         (out (get-string-all p))
         (status (close-pipe p)))
    (cons (status:exit-val status) out)))
(test-begin "handwriting-cli")
(define runner (test-runner-current))
(define before-meta (get meta))
(define good (run))
(test-equal "real CLI succeeds" 0 (car good))
(test-assert "independent XML parser accepts output"
  (pair? (xml->sxml (open-input-string (cdr good)))))
(test-assert "UTF-8 truth survives" (string-contains (cdr good) "café"))
(test-equal "source metadata unchanged" before-meta (get meta))
(test-equal "source page unchanged" (string-append record "\n") (get page))
(put page record)
(define torn (run))
(test-equal "torn tail is a failing exit" 1 (car torn))
(test-equal "failure emits no partial sample" "" (cdr torn))
(test-equal "torn tail is not repaired by export" record (get page))
(test-end "handwriting-cli")
(exit (if (zero? (test-runner-fail-count runner)) 0 1))
