;;; One native Guile book for the deterministic lost-ack integration test.
;;; It owns only its connected Book Protocol FD and never imports state/storage.
(use-modules (book-protocol blocking-io)
             (ice-9 ftw)
             (rnrs bytevectors)
             (srfi srfi-1))

(define initialize-fields
  '("type" "version" "grant_count" "surface_handle"
    "surface_generation" "max_pending_requests" "max_present_text_bytes"))
(define ready-fields
  '("type" "protocol_version" "grant_handle" "grant_generation" "access"))
(define value-fields
  '("type" "protocol_version" "present" "state_version" "text"))
(define committed-fields
  '("type" "protocol_version" "operation_id" "state_version" "text_bytes"))
(define action-fields
  '("type" "request_id" "action_id" "surface_handle"
    "surface_generation" "sequence" "text"))

(define (fail message . details) (error message details))
(define (field object name) (assoc-ref object name))

(define (exact-fields? message expected)
  (and (list? message)
       (= (length message) (length expected))
       (every (lambda (entry)
                (and (pair? entry) (string? (car entry))
                     (member (car entry) expected string=?)))
              message)
       (every (lambda (name) (assoc name message)) expected)))

(define (require-type port expected)
  (let ((message (read-frame port)))
    (when (eof-object? message)
      (fail "authority closed before expected message" expected))
    (unless (and (string? (field message "type"))
                 (string=? (field message "type") expected))
      (fail "authority sent unexpected message" expected message))
    message))

(define (require-initialize message)
  (unless (and (exact-fields? message initialize-fields)
               (string=? (field message "type") "initialize")
               (= (field message "version") 1)
               (= (field message "grant_count") 1)
               (= (field message "surface_generation") 1)
               (= (field message "max_pending_requests") 4)
               (= (field message "max_present_text_bytes") 4096)
               (string? (field message "surface_handle"))
               (not (string-null? (field message "surface_handle"))))
    (fail "initialize failed exact lost-ack schema")))

(define (require-ready message)
  (unless (and (exact-fields? message ready-fields)
               (string=? (field message "type") "state-ready")
               (= (field message "protocol_version") 1)
               (string? (field message "grant_handle"))
               (not (string-null? (field message "grant_handle")))
               (integer? (field message "grant_generation"))
               (> (field message "grant_generation") 0)
               (string=? (field message "access") "read-write"))
    (fail "state-ready failed exact lost-ack schema")))

(define (require-value message)
  (unless (and (exact-fields? message value-fields)
               (string=? (field message "type") "state-value")
               (= (field message "protocol_version") 1)
               (boolean? (field message "present"))
               (integer? (field message "state_version"))
               (string? (field message "text"))
               (<= (bytevector-length (string->utf8 (field message "text")))
                   4096)
               (if (field message "present")
                   (> (field message "state_version") 0)
                   (and (= (field message "state_version") 0)
                        (string-null? (field message "text")))))
    (fail "state-value failed exact lost-ack schema"))
  message)

(define (require-action message action-id)
  (unless (and (exact-fields? message action-fields)
               (string=? (field message "type") "action")
               (string=? (field message "action_id") action-id)
               (string? (field message "request_id"))
               (not (string-null? (field message "request_id")))
               (string? (field message "surface_handle"))
               (not (string-null? (field message "surface_handle")))
               (integer? (field message "surface_generation"))
               (integer? (field message "sequence"))
               (string? (field message "text")))
    (fail "action failed exact lost-ack schema" action-id))
  message)

(define (require-committed message operation-id text)
  (unless (and (exact-fields? message committed-fields)
               (string=? (field message "type") "state-committed")
               (= (field message "protocol_version") 1)
               (string=? (field message "operation_id") operation-id)
               (= (field message "state_version") 1)
               (= (field message "text_bytes")
                  (bytevector-length (string->utf8 text))))
    (fail "retry did not receive the original version-1 receipt"))
  message)

(define (state-read ready)
  `(("type" . "state-read")
    ("protocol_version" . 1)
    ("grant_handle" . ,(field ready "grant_handle"))
    ("grant_generation" . ,(field ready "grant_generation"))))

(define (state-commit ready operation-id text)
  `(("type" . "state-commit")
    ("protocol_version" . 1)
    ("grant_handle" . ,(field ready "grant_handle"))
    ("grant_generation" . ,(field ready "grant_generation"))
    ("operation_id" . ,operation-id)
    ("expected_state_version" . 0)
    ("text" . ,text)))

(define (presentation action text)
  `(("type" . "present")
    ("request_id" . ,(field action "request_id"))
    ("action_id" . ,(field action "action_id"))
    ("surface_handle" . ,(field action "surface_handle"))
    ("surface_generation" . ,(field action "surface_generation"))
    ("sequence" . ,(field action "sequence"))
    ("count" . 1)
    ("text" . ,text)))

(define (receive-load port ready)
  (write-frame port (state-read ready))
  (let loop ((snapshot #f) (action #f))
    (if (and snapshot action)
        (values snapshot action)
        (let* ((message (read-frame port))
               (type (and (not (eof-object? message))
                          (field message "type"))))
          (cond
           ((and (string? type) (string=? type "state-value"))
            (when snapshot (fail "duplicate state-value"))
            (loop (require-value message) action))
           ((and (string? type) (string=? type "action"))
            (when action (fail "duplicate load action"))
            (loop snapshot (require-action message "load-display")))
           (else (fail "unexpected load message" message)))))))

(define (run port mode operation-id)
  (write-frame port '(("type" . "hello") ("version" . 1)))
  (let ((initialize (require-type port "initialize"))
        (ready (require-type port "state-ready")))
    (require-initialize initialize)
    (require-ready ready)
    (call-with-values
        (lambda () (receive-load port ready))
      (lambda (snapshot load-action)
        (when (if (string=? mode "lose")
                  (field snapshot "present")
                  (not (and (field snapshot "present")
                            (= (field snapshot "state_version") 1))))
          (fail "lost-ack mode loaded the wrong durable baseline"))
        (write-frame
         port (presentation load-action
                            (if (field snapshot "present")
                                (field snapshot "text") "ABSENT")))
        (let* ((edit-action
                (require-action (require-type port "action") "edit-save"))
               (text
                (if (string=? mode "lose")
                    (field edit-action "text")
                    (begin
                      (unless (string=? (field edit-action "text")
                                        "RETRY-LOADED")
                        (fail "retry action exposed unexpected text"))
                      (field snapshot "text")))))
          (write-frame port (state-commit ready operation-id text))
          (format #t "LOST_ACK_BOOK: commit-sent:operation=~a:text-bytes=~a~%"
                  operation-id (bytevector-length (string->utf8 text)))
          (force-output)
          (cond
           ((string=? mode "lose")
            (let ((message (read-frame port)))
              (unless (eof-object? message)
                (fail "loss book consumed a frame before endpoint close" message))
              (display "LOST_ACK_BOOK: EOF-before-state-committed:ok\n")
              (force-output)))
           ((string=? mode "pretend-loss")
            (require-committed
             (require-type port "state-committed") operation-id text)
            (display "LOST_ACK_BOOK: state-committed-consumed:yes\n")
            (display "LOST_ACK_BOOK: pretended-loss-after-receipt\n")
            (force-output))
           ((string=? mode "retry")
            (let ((committed
                   (require-committed
                    (require-type port "state-committed") operation-id text)))
              (write-frame port (state-read ready))
              (let ((current
                     (require-value (require-type port "state-value"))))
                (unless (and (field current "present")
                             (= (field current "state_version") 1)
                             (string=? (field current "text") text))
                  (fail "exact retry changed current durable state"))
                (write-frame
                 port
                 (presentation
                  edit-action
                  (format #f
                          "receipt=~a|state-version=~a|text-bytes=~a|current-version=~a"
                          operation-id (field committed "state_version")
                          (field committed "text_bytes")
                          (field current "state_version"))))
                (display
                 "LOST_ACK_BOOK: original-receipt-consumed-after-restart:ok\n")
                (force-output))))
           (else (fail "unknown lost-ack book mode" mode))))))))

(define (open-protocol-port)
  (unless (equal? (getenv "BOOK_SESSION_FD") "0")
    (fail "BOOK_SESSION_FD must name donated FD 0"))
  (unless (eq? (stat:type (stat 0)) 'socket)
    (fail "donated FD 0 is not a socket"))
  (when (positive? (logand (fcntl 0 F_GETFD) FD_CLOEXEC))
    (fail "donated FD 0 remained close-on-exec"))
  (let ((port (fdopen 0 "r+0")))
    (unless (= (getsockopt port SOL_SOCKET SO_TYPE) SOCK_STREAM)
      (fail "donated FD 0 is not a stream socket"))
    (unless (and (= (vector-ref (getsockname port) 0) AF_UNIX)
                 (= (vector-ref (getpeername port) 0) AF_UNIX))
      (fail "donated FD 0 is not a connected Unix socket"))
    (let* ((donated (stat 0))
           (open
            (filter-map
             (lambda (name)
               (let ((fd (string->number name 10)))
                 (and fd (> fd 2)
                      (catch 'system-error
                        (lambda () (fcntl fd F_GETFD) fd)
                        (lambda arguments #f)))))
             (scandir "/proc/self/fd"
                      (lambda (name)
                        (and (not (member name '("." "..")))
                             (string->number name 10)))))))
      (for-each
       (lambda (fd)
         (let ((info (stat fd)))
           (when (and (= (stat:dev info) (stat:dev donated))
                      (= (stat:ino info) (stat:ino donated)))
             (fail "fixture retained duplicate donated socket" fd))
           (unless (positive? (logand (fcntl fd F_GETFD) FD_CLOEXEC))
             (fail "fixture inherited unrelated non-CLOEXEC FD" fd))))
       open))
    (setvbuf port 'none)
    port))

(let ((arguments (cdr (command-line))))
  (unless (= (length arguments) 2)
    (fail "usage: lost-ack-book.scm MODE OPERATION-ID"))
  (unless (member (car arguments) '("lose" "retry" "pretend-loss"))
    (fail "invalid lost-ack book mode"))
  (setpgid 0 0)
  (kill (getpid) SIGSTOP)
  (let ((port (open-protocol-port)))
    (dynamic-wind
      (lambda () #t)
      (lambda () (run port (car arguments) (cadr arguments)))
      (lambda ()
        (unless (port-closed? port) (close-port port))))))
