;;; Synthetic store and private control parser only; no authored native execution.
(primitive-load (search-path %load-path "guest-book-protocol.scm"))
(use-modules (workbench-editor-sandbox) (workbench-preview) (workbench-sandbox)
             (ice-9 ftw) (json) (rnrs bytevectors) (rnrs io ports)
             (srfi srfi-1) (srfi srfi-64))
(define root (mkdtemp "/tmp/opencode/editor-sandbox-unit.XXXXXX"))
(define (write-text path text) (call-with-output-file path (lambda (p) (display text p))))
(define (rejected? thunk) (catch #t (lambda () (thunk) #f) (lambda _ #t)))
(define (editor name) (module-ref (resolve-module '(workbench-editor-sandbox)) name))
(define (sandbox name) (module-ref (resolve-module '(workbench-sandbox)) name))
(set! test-log-to-file #f)
(test-begin "editor-sandbox")
(define runner (test-runner-current))
(dynamic-wind
  (lambda () #t)
  (lambda ()
    (let ((path (string-append root "/source")))
      (write-text path "(error \"never evaluated\")") (chmod path #o400)
      (test-equal "source is data" "(error \"never evaluated\")"
        (utf8->string ((editor 'source-bytes) path)))
      (chmod path #o600)
      (test-assert "writable source refused" (rejected? (lambda () ((editor 'source-bytes) path))))
      (write-text path (make-string 8193 #\a)) (chmod path #o400)
      (test-assert "oversized source refused" (rejected? (lambda () ((editor 'source-bytes) path))))
      (chmod path #o600) (write-text path "") (chmod path #o400)
      (test-assert "empty source refused" (rejected? (lambda () ((editor 'source-bytes) path))))
      (symlink path (string-append path "-link"))
      (test-assert "symlink source refused" (rejected? (lambda () ((editor 'source-bytes) (string-append path "-link"))))))
    (let* ((module (resolve-module '(workbench-editor-sandbox)))
           (original (module-ref module 'run-editor-sandbox*))
           (source (string-append root "/diagnostic-source"))
           (record (string-append source ".sandbox-error")))
      (dynamic-wind
        (lambda ()
          (module-set! module 'run-editor-sandbox*
                       (lambda _ `((status . failed) (diagnostic . ,(make-string 1024 #\λ))))))
        (lambda ()
          (run-editor-sandbox '() -1 source)
          (test-equal "failure record private mode" #o600 (logand #o7777 (stat:mode (lstat record))))
          (test-assert "failure record byte bound" (<= (stat:size (lstat record)) 2048))
          (let ((original (call-with-input-file record get-string-all)))
            (test-assert "failure record strict UTF-8 data" (positive? (string-length original)))
            (module-set! module 'run-editor-sandbox* (lambda _ '((status . failed) (diagnostic . "changed"))))
            (run-editor-sandbox '() -1 source)
            (test-equal "failure record never overwrites existing evidence" original
              (call-with-input-file record get-string-all))))
        (lambda () (module-set! module 'run-editor-sandbox* original))))
    (for-each
     (lambda (case)
       (let* ((pair (socketpair AF_UNIX SOCK_STREAM 0))
              (control ((editor 'control-port) (fileno (car pair))))
              (read! ((editor 'control-reader) control)))
         (test-equal "idle control read returns immediately" #f (read!))
         (send (cdr pair) (string->utf8 (car case)))
         (test-equal (string-append "control " (car case)) (cadr case)
           (catch #t read! (lambda _ 'refused)))
         (close-port (cdr pair))
         (test-equal "EOF always requests cleanup" #t (read!))
         (close-port control)))
     '(("sto" #f) ("stop\n" #t) ("wat\n" refused)
       ("stop\nstop\n" refused) ("abcdefghijklmnopqrstuvwxyz1234567" refused)))
    (let* ((store (string-append root "/store")) (prefix (make-string 32 #\a))
           (profile (string-append store "/" prefix "-profile"))
           (sources (map (lambda (name) (string-append store "/" prefix "-" name))
                         '("runner" "protocol" "blocking")))
           (bundle (string-append root "/bundle")) (bytes (string->utf8 "opaque source")))
      (mkdir store) (mkdir profile) (mkdir (string-append profile "/bin"))
      (write-text (string-append profile "/manifest") "synthetic store only\n")
      (for-each (lambda (name) (let ((path (string-append profile "/bin/" name)))
                                (write-text path "fixture") (chmod path #o555))) '("guile" "python3"))
      (for-each (lambda (path) (write-text path "immutable") (chmod path #o444)) sources)
      (generate-workbench-preview-bundle
       #:source bytes #:profile-input profile #:runner-input (car sources)
       #:protocol-input (cadr sources) #:blocking-input (caddr sources)
       #:bundle-input bundle #:container-id "editor-test" #:requisites-runner (lambda _ (list profile))
       #:store-root store #:editor? #t)
      (define (validate)
        ((sandbox 'validate-launch!) bundle "editor-test" bytes profile (list profile) sources store #:editor? #t))
      (test-assert "editor passes independent exact validator" (not (rejected? validate)))
      (test-assert "finite validator rejects editor policy"
        (rejected? (lambda () ((sandbox 'validate-launch!) bundle "editor-test" bytes profile (list profile) sources store))))
      (let* ((path (string-append bundle "/config.json"))
             (spec (call-with-input-file path (lambda (p) (json->scm p #:ordered #t))))
             (process (assoc-ref spec "process"))
             (limits (vector->list (assoc-ref process "rlimits"))))
        (test-assert "editor has no finite CPU rlimit"
          (not (find (lambda (x) (equal? (assoc-ref x "type") "RLIMIT_CPU")) limits)))
        (test-assert "guest task limit retained"
          (find (lambda (x) (equal? x '(("type" . "RLIMIT_NPROC") ("soft" . 32) ("hard" . 32)))) limits))
        (test-equal "host CPU quota retained" 50000
          (assoc-ref (assoc-ref (assoc-ref (assoc-ref spec "linux") "resources") "cpu") "quota"))
        (let ((changed ((sandbox 'replace) spec "process"
                        ((sandbox 'replace) process "rlimits"
                         (list->vector (cons '(("type" . "RLIMIT_CPU") ("soft" . 10) ("hard" . 10)) limits))))))
          (call-with-output-file path (lambda (p) (scm->json changed p)))
          (test-assert "CPU rlimit reintroduction rejected" (rejected? validate))))))
  (lambda () ((@@ (workbench-preview) remove-owned-tree) root)))
(test-end "editor-sandbox")
(exit (if (zero? (test-runner-fail-count runner)) 0 1))
