;;; Separate evidence classes: synthetic launch validation, then controlled
;;; native lifetime seams. No public preview-sandbox path is replaced by native.
;;; Actual gVisor/resource evidence belongs to the separately invoked QEMU gate.
;; Initialize Guile's signal thread outside the module-loader lock: the existing
;; guest-book-protocol module installs its SIGPIPE disposition while loading.
(sigaction SIGPIPE SIG_IGN)
(use-modules (workbench-sandbox) (workbench-preview) (book-session)
             (ice-9 ftw) (ice-9 threads) (json) (rnrs bytevectors)
             (rnrs io ports) (srfi srfi-1) (srfi srfi-13) (srfi srfi-64))

(define here (dirname (canonicalize-path (car (command-line)))))
(define guile (or (getenv "BOOK_WORKBENCH_GUILE") (getenv "GUILE_TEST")
                  "/gnu/store/nlkcijvhrj9xfz4dz134iwlc9z52mb4s-wilkbook-book-state-device-supervisor/bin/guile"))
(define profile-directory (dirname (dirname guile)))
;; Realized ARM fixture from gk9wmzvbfya92qrdh6gjgqfmc0aqdsrf-system. These
;; overrides allow another realized system's matching pair without executing ARM
;; code or runsc. The test deliberately reads the inherited manifest artifact.
(define language-closure-file
  (or (getenv "BOOK_WORKBENCH_LANGUAGE_CLOSURE")
      "/gnu/store/8a8c36ikjvgw0xfhwax1m5jl050g3akz-wilkbook-book-execution-language-closure"))
(define language-profile
  (or (getenv "BOOK_WORKBENCH_LANGUAGE_PROFILE")
      "/gnu/store/79c6nxapy2b91mr4566dq7z9gzdanmii-wilkbook-book-execution-languages"))
(define runner (string-append here "/workbench-runner.scm"))
(define adapter (canonicalize-path (string-append here "/../book-state-guest/runsc-fd3-exec.scm")))
(define runtime-owner (string-append here "/workbench-runtime-owner.scm"))
(define protocol-directory (canonicalize-path (string-append here "/../book-protocol")))
(define seed "(define (workbench text) (string-append \"Sandbox: \" text))")
(define root (mkdtemp "/tmp/opencode/workbench-sandbox-tests.XXXXXX"))
(chmod root #o700)
(define sandbox-module (resolve-module '(workbench-sandbox)))
(define (sandbox name) (module-ref sandbox-module name))
(define (set-sandbox! name value) (module-set! sandbox-module name value))
(define remove-tree (@@ (workbench-preview) remove-owned-tree))
(define (write-text path text)
  (call-with-output-file path (lambda (port) (display text port))))
(define (read-text path) (call-with-input-file path get-string-all))
(define (field value key) (assoc-ref value key))
(define (rejected? thunk) (catch #t (lambda () (thunk) #f) (lambda _ #t)))
(define (clock) (/ (get-internal-real-time) internal-time-units-per-second 1.0))
(define (fd-open? fd)
  (catch 'system-error (lambda () (fcntl fd F_GETFD) #t) (lambda _ #f)))
(define (open-fds)
  (sort (filter-map (lambda (name) (let ((n (string->number name)))
                                   (and n (fd-open? n) n))) (scandir "/proc/self/fd")) <))
(define (live? pid)
  (catch 'system-error (lambda () (kill pid 0) #t) (lambda _ #f)))
(define fake-runtime (string-append root "/fake-runsc.scm"))
;; A native runsc-control model: attached run waits for its guest then performs
;; Destroy; kill targets the guest. Delete deliberately models unsafe saved-PID
;; signalling by writing a persistent would-signal marker instead of sending a
;; signal. No test actually recycles or signals an unrelated host PID.
;; The checked state file also proves incomplete cleanup after forced termination.
(define unsafe-delete-marker (string-append root "/unsafe-delete-would-signal-recycled-pid"))
(write-text fake-runtime
 (format #f "(use-modules (ice-9 textual-ports) (srfi srfi-1))
(define guile ~s) (define adapter ~s) (define protocol ~s) (define unsafe-delete-marker ~s)
(define args (cdr (command-line)))
(define state (substring (car args) 7))
(define bundle (dirname state))
(define mode (call-with-input-file (string-append bundle \"/control-mode\") get-string-all))
(define mark (string-append state \"/fake-container\"))
(define pidfile (string-append bundle \"/fake-guest\"))
(define (start pid) (let* ((s (call-with-input-file (format #f \"/proc/~~a/stat\" pid) get-string-all)) (f (string-tokenize (substring s (+ 2 (string-rindex s #\\))))))) (list-ref f 19)))
(define (destroy) (when (file-exists? mark) (delete-file mark)))
(cond
 ((equal? (cadr args) \"run\")
  (let* ((runner (call-with-input-file (string-append bundle \"/selected-runner\") get-string-all))
         (donation (fdopen 3 \"r+0\"))
         (pid (spawn guile (list guile \"--no-auto-compile\" adapter \"--directory\" bundle \"--\"
                                 guile \"--no-auto-compile\" \"-L\" protocol runner \"--native-run\"
                                 (string-append bundle \"/program.scm\"))
                     #:input donation #:output (current-output-port) #:error (current-error-port))))
    (close-port donation)
    (unless (equal? (status:stop-sig (cdr (waitpid pid WUNTRACED))) SIGSTOP) (exit 90))
    (call-with-output-file pidfile (lambda (p) (write (list pid (start pid)) p)))
    (call-with-output-file mark (lambda (p) (display \"saved_sentry_pid=31337; no start identity\" p)))
    (kill pid SIGCONT)
    (let ((status (cdr (waitpid pid))))
      (unless (equal? mode \"stale-after-exit\") (destroy))
      (exit (or (status:exit-val status) 137)))))
 ((equal? (cadr args) \"kill\")
  (when (equal? mode \"fail-kill\") (exit 19))
  (when (equal? mode \"hang-kill\") (let loop () (sleep 1) (loop)))
  (catch 'system-error
    (lambda () (let ((p (call-with-input-file pidfile read)))
                 (unless (equal? (cadr p) (start (car p))) (exit 91)) (kill (car p) SIGKILL)))
    (lambda _ (exit 1))))
 ((equal? (cadr args) \"delete\")
  (call-with-output-file unsafe-delete-marker
    (lambda (p) (display \"would signal recycled numeric PID 31337 from stale metadata\" p)))
  (destroy))
 (else (exit 92)))\n" guile adapter protocol-directory unsafe-delete-marker))

(set! test-log-to-file #f)
(test-begin "workbench-sandbox")
(dynamic-wind
  (lambda () #t)
  (lambda ()
    (display "Evidence: synthetic launch-validation only (no runtime)\n")
    (let* ((store (string-append root "/store")) (prefix (make-string 32 #\a))
           (profile (string-append store "/" prefix "-profile"))
           (sources (map (lambda (name) (string-append store "/" prefix "-" name ".scm"))
                         '("runner" "protocol" "blocking")))
           (bundle (string-append root "/bundle")) (id "sandbox-validation")
           (bytes (string->utf8 seed)))
      (define (validate)
        (call-with-values
            (lambda () ((sandbox 'validate-launch!) bundle id bytes profile (list profile) sources store))
          list))
      (define (mutate-json name label transform)
        (let* ((path (string-append bundle "/" name)) (original (read-text path))
               (value (call-with-input-file path (lambda (p) (json->scm p #:ordered #t)))))
          (dynamic-wind
            (lambda () #t)
            (lambda ()
              (call-with-output-file path (lambda (p) (scm->json (transform value) p)))
              (test-assert label (rejected? validate)))
            (lambda () (write-text path original)))))
      (define (replace value key new) ((sandbox 'replace) value key new))
      (mkdir store) (mkdir profile) (mkdir (string-append profile "/bin"))
      (write-text (string-append profile "/manifest") "synthetic store only\n")
      (for-each (lambda (name)
                  (let ((path (string-append profile "/bin/" name)))
                    (write-text path "synthetic, never execute\n") (chmod path #o555)))
                '("guile" "python3"))
      (for-each (lambda (path) (write-text path "; synthetic trusted input\n") (chmod path #o444)) sources)
      (generate-workbench-preview-bundle
       #:source seed #:profile-input profile #:runner-input (car sources)
       #:protocol-input (cadr sources) #:blocking-input (caddr sources)
       #:bundle-input bundle #:container-id id #:store-root store
       #:requisites-runner (lambda (_) (list profile)))
      (test-equal "independent reader admits exact prepared launch"
        (workbench-preview-launch-argv bundle id) (car (validate)))
      (test-equal "independent environment is fixed"
        (list "HOME=/nonexistent" "LANG=C" "LC_ALL=C" "PATH=/run/current-system/profile/bin"
              (string-append "TMPDIR=" bundle "/supervisor-tmp")) (cadr (validate)))
      (for-each
       (lambda (pair)
         (mutate-json "launch.json" (string-append "reject launch " (car pair))
                      (lambda (value) (replace value (car pair) (cdr pair)))))
       '(("claim" . "sandbox-accepted") ("executionProfile" . "functional-directfs")
         ("fixtureKind" . "guile") ("guestProtocolFd" . 4) ("supervisorUid" . 1000)
         ("requiredKernelConfig" . #()) ("sourceBytes" . 1) ("sourceSha256" . "wrong")
         ("cgroupsPath" . "/") ("supervisorEnv" . #("PATH=/bin"))
         ("argv" . #("/bin/true"))))
      (mutate-json "launch.json" "reject extra launch authority"
                   (lambda (v) (cons '("nativeFallback" . #t) v)))
      (mutate-json "launch.json" "reject duplicate launch key"
                   (lambda (v) (cons (car v) v)))
      (mutate-json "launch.json" "reject extra runtime flag"
                   (lambda (v) (replace v "argv" (list->vector
                                                 (append (vector->list (field v "argv")) '("--network=host"))))))
      (for-each
       (lambda (pair)
         (mutate-json "config.json" (string-append "reject process " (car pair))
                      (lambda (v) (replace v "process" (replace (field v "process") (car pair) (cdr pair))))))
       '(("env" . #("GUILE_LOAD_PATH=/data")) ("args" . #("/bin/sh"))
         ("rlimits" . #()) ("noNewPrivileges" . #f) ("terminal" . #t)
         ("user" . (("uid" . 0))) ("capabilities" . (("effective" . #("CAP_SYS_ADMIN"))))))
      (for-each
       (lambda (pair)
         (mutate-json "config.json" (string-append "reject OCI " (car pair))
                      (lambda (v) (replace v (car pair) (cdr pair)))))
       '(("mounts" . #()) ("root" . (("path" . "/") ("readonly" . #f)))))
      (mutate-json "config.json" "reject extra OCI hook"
                   (lambda (v) (cons '("hooks" . (("prestart" . #()))) v)))
       (mutate-json "config.json" "reject missing resource limits"
                   (lambda (v) (replace v "linux" (filter (lambda (p) (not (equal? (car p) "resources")))
                                                          (field v "linux")))))
       (for-each
        (lambda (limit)
          (mutate-json "config.json" (format #f "reject non-policy PID limit ~a" limit)
                       (lambda (v)
                         (let* ((linux (field v "linux")) (resources (field linux "resources")))
                           (replace v "linux" (replace linux "resources"
                             (replace resources "pids" `(("limit" . ,limit)))))))))
        '(64 128 255 257 -1))
       (for-each
        (lambda (change)
          (mutate-json "config.json" (format #f "reject guest CPU budget change ~s" change)
            (lambda (v)
              (let* ((process (field v "process"))
                     (limits (map (lambda (limit)
                                    (if (equal? (field limit "type") "RLIMIT_CPU")
                                        (replace limit (car change) (cdr change)) limit))
                                  (vector->list (field process "rlimits")))))
                (replace v "process" (replace process "rlimits" (list->vector limits)))))))
        '(("soft" . 2) ("hard" . 2) ("soft" . 11) ("hard" . 11)))
      (mutate-json "config.json" "reject duplicate nested JSON key"
                   (lambda (v) (replace v "root" (cons '("readonly" . #t) (field v "root")))))
      (let ((path (string-append bundle "/program.scm")))
        (chmod path #o644)
        (test-assert "writable source snapshot refused" (rejected? validate))
        (chmod path #o444)
        (delete-file path) (symlink (car sources) path)
        (test-assert "symlink source snapshot refused without following it" (rejected? validate))
        (delete-file path) (mknod path 'fifo #o444 0)
        (let ((start (clock)))
          (test-assert "FIFO snapshot refused before a blocking read" (rejected? validate))
          (test-assert "FIFO refusal is prompt" (< (- (clock) start) 0.5)))
        (delete-file path) (write-text path (string-append seed ";changed")) (chmod path #o444)
        (test-assert "source snapshot must match broker bytes" (rejected? validate))
        (delete-file path) (write-text path seed) (chmod path #o444)
        (link path (string-append bundle "/source-alias"))
        (test-assert "hard-linked source refused" (rejected? validate))
        (delete-file (string-append bundle "/source-alias")))
      (let ((path (string-append bundle "/rootfs/book/runner.scm")))
        (delete-file path) (symlink "/data/book-state.sqlite" path)
        (test-assert "rootfs placeholder symlink refused" (rejected? validate))
        (delete-file path) (write-text path "") (chmod path #o444))
      (let ((path (string-append bundle "/rootfs/injected")))
        (write-text path "injected")
        (test-assert "extra rootfs file refused" (rejected? validate))
        (delete-file path))
      (let ((path (string-append bundle "/launch.json")))
        (let ((original (read-text path)))
          (write-text path (string-append original " {}"))
          (test-assert "trailing JSON value refused" (rejected? validate))
          (write-text path original)))
      (let* ((preview-module (resolve-module '(workbench-preview)))
             (original-base (module-ref preview-module 'base)) (writes 0) (reads 0)
             (clock-value 0) (partial (string-append root "/failed-preparation")))
        (dynamic-wind
          (lambda ()
            (module-set! preview-module 'base
                         (lambda (name)
                           (if (eq? name 'write-json)
                               (lambda args
                                 (set! writes (+ writes 1))
                                 (if (= writes 2) (throw 'late-json-write-failure)
                                     (apply (original-base name) args)))
                               (original-base name)))))
          (lambda ()
            (parameterize (((@@ (workbench-preview) cleanup-clock) (lambda () clock-value))
                           ((@@ (workbench-preview) cleanup-read-directory)
                            (lambda (directory)
                              (set! reads (+ reads 1)) (set! clock-value reads) (readdir directory))))
              (test-assert "late generator failure honors supplied cleanup deadline"
                (rejected?
                 (lambda ()
                   (generate-workbench-preview-bundle
                    #:source seed #:profile-input profile #:runner-input (car sources)
                    #:protocol-input (cadr sources) #:blocking-input (caddr sources)
                    #:bundle-input partial #:container-id id #:store-root store
                    #:requisites-runner (lambda (_) (list profile)) #:cleanup-deadline 3)))))
            (test-equal "generator cleanup stops at exact deadline traversal" 3 reads)
            (test-assert "expired generator cleanup retains partial root" (file-exists? partial)))
          (lambda () (module-set! preview-module 'base original-base))))
      (test-assert "restored exact bundle still validates" (not (rejected? validate))))

    (display "Evidence: trusted alias pinning and mocked ancestry inspection\n")
    (let* ((alias (string-append root "/guile-alias"))
           (_ (symlink guile alias)) (selected ((sandbox 'trusted-program!) alias #t)))
      (delete-file alias) (symlink "/usr/bin/false" alias)
      (test-equal "validated executable selection is canonical" (canonicalize-path guile) selected)
      (let* ((null (open-file "/dev/null" "r+"))
             (pid (spawn selected (list selected "-c" "(exit 0)")
                         #:input null #:output null #:error null)))
        (close-port null)
        (test-equal "alias retarget cannot substitute the spawned executable" 0
          (status:exit-val (cdr (waitpid pid))))))
    (display "Evidence: realized ARM system closure manifest read/validation (no execution)\n")
    (let* ((alias (string-append root "/closure-alias"))
           (manifest language-closure-file)
           (expected (call-with-input-file manifest read))
           (replacement (string-append root "/wrong-closure"))
           (original (sandbox 'trusted-program!)) (callback #f)
           (original-preview (sandbox 'preview-sandbox)))
      (test-equal "realized inherited Scheme-list manifest is decoded exactly"
        expected ((sandbox 'read-language-closure) manifest))
      (test-equal "realized closure validates against its selected ARM profile"
        (sort (list-copy expected) string<?)
        (((sandbox 'oci) 'validate-requisites)
         ((sandbox 'read-language-closure) manifest) language-profile "/gnu/store"))
      (test-assert "realized closure contains selected language profile"
        (member language-profile expected))
      (write-text replacement "(\"wrong replacement\")")
      (symlink manifest alias)
      (dynamic-wind
        (lambda ()
          (set-sandbox! 'trusted-program!
                        (lambda (path executable?)
                          (let ((selected (original path executable?)))
                            (when (string=? path alias)
                               (delete-file alias) (symlink replacement alias))
                            selected)))
          (set-sandbox! 'preview-sandbox (lambda* (source text #:key closure #:allow-other-keys) closure)))
        (lambda ()
          (set! callback (make-sandbox-preview `((language-profile . ,language-profile)
                                               (language-closure . ,alias))))
          (test-equal "closure read uses validated target across alias retarget"
            expected (callback seed "x")))
        (lambda () (set-sandbox! 'trusted-program! original)
          (set-sandbox! 'preview-sandbox original-preview))))
    (display "Evidence: malformed/bounded Scheme closure data fixtures\n")
    (let ((path (string-append root "/closure-data"))
          (read-closure (sandbox 'read-language-closure)))
      (for-each
       (lambda (pair)
         (write-text path (cdr pair))
         (test-assert (car pair) (rejected? (lambda () (read-closure path)))))
       '(("empty manifest rejected" . "")
         ("whitespace-only manifest rejected" . " \n")
         ("malformed list rejected" . "(\"path\"")
         ("non-string entry rejected" . "(\"path\" 7)")
         ("dotted list rejected" . "(\"path\" . \"other\")")
         ("quoted expression is not a path list" . "'(\"path\")")
         ("vector is not a path list" . "#(\"path\")")
         ("additional list form rejected" . "(\"path\") (\"other\")")
         ("additional scalar form rejected" . "(\"path\") #t")
         ("line-oriented requisites are not silently accepted" . "/gnu/store/path-one\n/gnu/store/path-two\n")))
      (write-text path "(\"path\") ; trailing comment\n")
      (test-equal "trailing whitespace/comment reaches exact Scheme EOF" '("path") (read-closure path))
      (write-text path "()")
      (test-assert "empty list cannot satisfy selected profile requisites"
        (rejected? (lambda () (((sandbox 'oci) 'validate-requisites)
                              (read-closure path) language-profile "/gnu/store"))))
      (let* ((prefix "(\"é\")")
             (padding (- 262144 (bytevector-length (string->utf8 prefix)))))
        (write-text path (string-append prefix (make-string padding #\space)))
        (test-equal "exact 262144-byte UTF-8 manifest bound" '("é") (read-closure path))
        (write-text path (string-append prefix (make-string (+ padding 1) #\space)))
        (test-assert "one byte above manifest bound rejected" (rejected? (lambda () (read-closure path)))))
      (write-text path (make-string 131073 #\é))
      (test-assert "manifest bound counts UTF-8 bytes" (rejected? (lambda () (read-closure path))))
      (call-with-output-file path (lambda (port) (put-bytevector port #vu8(195 40))))
      (let ((before (open-fds)))
        (test-assert "invalid UTF-8 manifest rejected" (rejected? (lambda () (read-closure path))))
        (test-equal "failed decoding closes the manifest descriptor" before (open-fds)))
      (delete-file path) (mknod path 'fifo #o600 0)
      (let ((start (clock)))
        (test-assert "nonregular manifest rejected without blocking" (rejected? (lambda () (read-closure path))))
        (test-assert "FIFO manifest refusal is prompt" (< (- (clock) start) 0.5))))
    (let ((inspect (lambda (_) (stat "/"))))
      (test-assert "mock root-owned nonwritable ancestry accepted"
        (not (rejected? (lambda () ((sandbox 'trusted-ancestry!) "/run/workbench" inspect)))))
      (test-assert "mock root-owned leaf below user-owned ancestor refused"
        (rejected? (lambda () ((sandbox 'trusted-ancestry!) "/tmp/alice/runtime"
                               (lambda (path) (if (equal? path "/tmp/alice") (lstat root)
                                                  (if (equal? path "/tmp") (stat "/tmp") (stat "/"))))))))
      (test-assert "mock writable ancestor outside sticky /tmp refused"
        (rejected? (lambda () ((sandbox 'trusted-ancestry!) "/run/writable/runtime"
                               (lambda (path) (if (equal? path "/run/writable") (stat "/tmp") (stat "/")))))))
      (test-assert "mock root-owned sticky /tmp exception accepted"
        (not (rejected? (lambda () ((sandbox 'trusted-ancestry!) "/tmp/runtime"
                                    (lambda (path) (if (equal? path "/tmp") (stat "/tmp") (stat "/")))))))))

    (display "Evidence: bounded stderr selection, independent of runtime verdicts\n")
    (let ((path (string-append root "/capture-data")))
      (define (captured bytes)
        (call-with-output-file path (lambda (port) (put-bytevector port bytes)))
        (call-with-input-file path
          (lambda (port)
            (let ((capture ((@@ (workbench-sandbox) make-capture) port 0 #f #vu8() '())))
              (let loop ()
                (unless ((@@ (workbench-sandbox) capture-eof?) capture)
                  (catch #t (lambda () ((sandbox 'pump-capture!) capture)) (lambda _ #f))
                  (loop)))
              ((sandbox 'capture-evidence) capture)))))
      (let* ((early "Guile early loader failure\n")
             (late "I0915 18:39:39.769106 197 cli.go:317] Exiting with status: 9\n")
             (value (captured (string->utf8 (string-append early
                        (string-concatenate (make-list 200 "D0915 18:39:39.000000 197 sandbox.go:1571] Destroying sandbox\n")) late)))))
        (test-assert "early stderr survives more than 1 KiB of teardown debug" (string-prefix? early (field value 'text)))
        (test-assert "non-debug runtime wait-status line also retained" (string-suffix? late (field value 'text)))
        (test-assert "debug noise removed only from diagnostic selection" (not (string-contains (field value 'text) "Destroying sandbox"))))
      (let ((value (captured (string->utf8 (string-append (make-string 4095 #\x) "é\n")))))
        (test-assert "UTF-8 split across read chunks remains intact" (string-suffix? "é\n" (field value 'text))))
      (let ((value (captured #vu8(97 255 98))))
        (test-equal "invalid UTF-8 does not discard surrounding diagnostic bytes" "a�b" (field value 'text)))
      (let ((value (captured (string->utf8 (string-append "EARLY" (make-string 262144 #\x) "BEYOND")))))
        (test-equal "stderr storage never exceeds 256 KiB even after overflow" 262144 (field value 'captured-bytes))
        (test-equal "stderr storage truncation explicitly flagged" #t (field value 'capture-truncated?))
        (test-equal "selected stderr bounded to 8192 characters" 8192 (string-length (field value 'text)))
        (test-equal "selected stderr truncation explicitly flagged" #t (field value 'selection-truncated?))
        (test-assert "selected stderr preserves earliest evidence" (string-prefix? "EARLY" (field value 'text)))
        (test-assert "discarded overflow bytes cannot enter evidence" (not (string-contains (field value 'text) "BEYOND"))))
      (let ((value (captured (string->utf8 "D0915 debug only\n"))))
        (test-equal "all-debug stream has explicit fallback" 'all-lines-fallback (field value 'selection)))
      (test-equal "empty stderr remains usable evidence" "" (field (captured #vu8()) 'text)))

    (display "Evidence: synthetic kernel observation files (no resource enforcement claim)\n")
    (let* ((directory (string-append root "/wilkbook-execution-observation"))
           (files '(("memory.max" . "268435456\n") ("memory.current" . "120000\n")
                    ("memory.events" . "oom 0\noom_kill 0\n") ("cpu.max" . "50000 100000\n")
                    ("cpu.stat" . "usage_usec 1234\nnr_throttled 2\n") ("pids.max" . "256\n")
                    ("pids.current" . "0\n") ("pids.events" . "max 0\n") ("cgroup.procs" . ""))))
      (define (read-race errno vanished? procedure)
        (let* ((hierarchy (mkdtemp (string-append root "/observation-race.XXXXXX")))
               (group (string-append hierarchy "/wilkbook-execution-race"))
               (original (sandbox 'read-kernel-text)) (reads 0))
          (mkdir group)
          (for-each (lambda (pair) (write-text (string-append group "/" (car pair)) (cdr pair))) files)
          (dynamic-wind
            (lambda ()
              (set-sandbox! 'read-kernel-text
                (lambda (path limit)
                  (set! reads (+ reads 1))
                  (if (string=? path (string-append group "/cpu.stat"))
                      ;; The attribute is already open when kernfs loses its
                      ;; active reference. A regular-file fixture supplies the
                      ;; fd/lifetime; inject the kernel's actual read-stage errno.
                      (call-with-input-file path
                        (lambda (port)
                          (when vanished? (remove-tree group))
                          (throw 'system-error "fport_read" "~A" (list (strerror errno)) (list errno))))
                      (original path limit)))))
            (lambda () (procedure (lambda () ((sandbox 'observe-cgroup) "race" hierarchy))
                                  (lambda () reads)))
            (lambda () (set-sandbox! 'read-kernel-text original) (remove-tree hierarchy)))))
      (mkdir directory)
      (for-each (lambda (pair) (write-text (string-append directory "/" (car pair)) (cdr pair))) files)
      (let ((sample ((sandbox 'observe-cgroup) "observation" root)))
        (test-equal "empty newly-created cgroup membership is ordinary" '() (field sample 'members))
        (test-equal "exact live controls are recognized" #t (field sample 'controls-match?))
         (test-equal "raw kernel CPU throttling counter retained" "usage_usec 1234\nnr_throttled 2"
           (field (field sample 'files) "cpu.stat")))
       (for-each
        (lambda (limit)
          (write-text (string-append directory "/pids.max") limit)
          (test-equal (string-append "non-policy live pids.max refused: " limit) #f
            (field ((sandbox 'observe-cgroup) "observation" root) 'controls-match?)))
        '("64" "128" "255" "257" "max"))
       (write-text (string-append directory "/pids.max") "256")
       (write-text (string-append directory "/pids.events") "max 1\n")
       (test-equal "PID rejection evidence survives zero current task count" "max 1"
         (field (field ((sandbox 'observe-cgroup) "observation" root) 'files) "pids.events"))
       ;; Synthetic duplicate entries exercise only the parser's bounded work,
       ;; not a claim that these are distinct processes or enforced task counts.
       (write-text (string-append directory "/cgroup.procs")
                   (string-concatenate (make-list 256 (format #f "~a\n" (getpid)))))
       (test-equal "observer accepts up to 256 membership entries" 256
         (length (field ((sandbox 'observe-cgroup) "observation" root) 'members)))
       (write-text (string-append directory "/cgroup.procs")
                   (string-concatenate (make-list 257 "1\n")))
       (test-assert "observer refuses more than 256 membership entries"
         (rejected? (lambda () ((sandbox 'observe-cgroup) "observation" root))))
       (write-text (string-append directory "/cgroup.procs") "")
       (write-text (string-append directory "/memory.max") "max\n")
      (test-equal "unlimited memory control is not accepted" #f
        (field ((sandbox 'observe-cgroup) "observation" root) 'controls-match?))
      (write-text (string-append directory "/cgroup.procs") (format #f "~a\n" (getpid)))
      (test-equal "membership metadata reads actual host PID identity" (getpid)
        (field (car (field ((sandbox 'observe-cgroup) "observation" root) 'members)) 'pid))
      (write-text (string-append directory "/cgroup.procs") "../unsafe\n")
      (test-assert "malformed kernel PID text fails closed"
        (rejected? (lambda () ((sandbox 'observe-cgroup) "observation" root))))
       (test-equal "absent runtime cgroup has no invented sample" #f
         ((sandbox 'observe-cgroup) "absent" root))
       (read-race ENODEV #t
          (lambda (observe reads)
            (test-equal "ENODEV while reading removed cgroup discards partial sample" #f (observe))
            (test-equal "vanished-sample handling adds no retry/read loop" 5 (reads))))
       (read-race ENODEV #f
         (lambda (observe reads)
           (let ((original (sandbox 'exists)) (checks 0))
             (dynamic-wind
               (lambda ()
                 (set-sandbox! 'exists
                   (lambda (path)
                     (set! checks (+ checks 1))
                     ;; First check starts the sample, second sees the still
                     ;; linked group after ENODEV, third observes its unlink.
                     (when (= checks 3) (remove-tree path))
                     (original path))))
               (lambda ()
                 (test-equal "kernfs retirement before directory unlink discards sample" #f (observe))
                 (test-equal "retirement waits only for unlink, never rereads controls" 5 (reads))
                 (test-equal "retirement actually observed delayed unlink" 3 checks))
               (lambda () (set-sandbox! 'exists original))))))
       (let ((before ((sandbox 'now))))
         (test-equal "expired observation deadline does not wait on a live group" #f
           ((sandbox 'cgroup-disappeared?) directory (lstat directory) (- before 1))))
       (read-race ENODEV #t
         (lambda (observe reads)
           (let ((original (sandbox 'exists)) (checks 0))
             (dynamic-wind
               (lambda ()
                 (set-sandbox! 'exists
                   (lambda (path)
                     (set! checks (+ checks 1))
                     (if (= checks 1) (original path)
                         (throw 'system-error "lstat" "~A" (list (strerror EACCES)) (list EACCES))))))
               (lambda ()
                 (test-equal "failed absence confirmation is not a vanished sample" EACCES
                   (catch 'system-error (lambda () (observe) #f)
                     (lambda args (system-error-errno args)))))
               (lambda () (set-sandbox! 'exists original))))))
       (for-each
        (lambda (case)
          (read-race (car case) (cadr case)
            (lambda (observe reads)
              (test-equal (format #f "read errno ~a with vanished=~a is not ignored" (car case) (cadr case))
                (car case)
                (catch 'system-error (lambda () (observe) #f)
                  (lambda args (system-error-errno args)))))))
        (list (list ENODEV #f) (list EACCES #f) (list EACCES #t)
              (list EIO #f) (list EIO #t)))
       ;; ENODEV is not broadly suppressed around process metadata collection.
       (write-text (string-append directory "/cgroup.procs") (format #f "~a\n" (getpid)))
       (let ((original (sandbox 'base)))
         (dynamic-wind
           (lambda ()
             (set-sandbox! 'base
               (lambda (name)
                 (if (eq? name 'read-process-start-time)
                     (lambda (pid)
                       (remove-tree directory)
                       (throw 'system-error "fport_read" "~A" (list (strerror ENODEV)) (list ENODEV)))
                     (original name)))))
           (lambda ()
             (test-equal "ENODEV outside control-file read stage still propagates" ENODEV
               (catch 'system-error (lambda () ((sandbox 'observe-cgroup) "observation" root) #f)
                 (lambda args (system-error-errno args)))))
           (lambda () (set-sandbox! 'base original)))))

    (display "Evidence: controlled native runtime seams (FD adapter/session/lifetime, no isolation claim)\n")
    ;; Replace only unavailable mount/cgroup boundaries. The real spawn/FD3
    ;; adapter, stop ownership, session, captures, signals, reap and tree cleanup
    ;; execute unchanged. This private call is not exposed as a public fallback.
    (let* ((names '(base smoke mount-diagnostic! cleanup-diagnostic! cleanup-runtime! observe-cgroup))
           (originals (map (lambda (name) (cons name (sandbox name))) names))
           (base (sandbox 'base)) (smoke (sandbox 'smoke))
           (sample '((controls-match? . #t) (test-only-synthetic-cgroup . #t)))
           (old-subreaper ((@@ (workbench-preview) subreaper?))))
      (define* (run source #:optional (text "élan") #:key (seconds 3) (selected-runner runner)
                    (selected-adapter adapter) (control-mode "normal"))
        (let* ((private (mkdtemp (string-append root "/seam.XXXXXX")))
               (bundle (string-append private "/bundle"))
               (path (string-append bundle "/program.scm"))
               (start (clock)))
          (chmod private #o700) (mkdir bundle #o700) (write-text path source)
          (mkdir (string-append bundle "/runsc-state") #o700)
          (write-text (string-append bundle "/selected-runner") selected-runner)
          (write-text (string-append bundle "/control-mode") control-mode)
          ((sandbox 'execute-bundle!)
           private bundle "controlled-native-seam"
           (list guile fake-runtime (string-append "--root=" bundle "/runsc-state") "run" "controlled-native-seam")
           (list "HOME=/nonexistent" "LANG=C.UTF-8" "LC_ALL=C.UTF-8" "GUILE_AUTO_COMPILE=0"
                 "BOOK_SESSION_FD=3" (string-append "PATH=" profile-directory "/bin")
                 (string-append "GUILE_LOAD_PATH=" profile-directory "/share/guile/site/3.0")
                 (string-append "GUILE_LOAD_COMPILED_PATH=" profile-directory "/lib/guile/3.0/site-ccache"))
           text guile selected-adapter runtime-owner (+ start seconds) (+ start (* seconds 2/3)))))
      (define (expected-failure label source)
        (let ((value (run source)))
          (test-equal label 'failed (field value 'status))
          (test-equal (string-append label " has no result") "" (field value 'text))
          (test-equal (string-append label " actually initialized") #t (field value 'execution-started?))
          (test-equal (string-append label " cleanup proven") #t (field value 'cleanup-complete?))))
      (define (fake-cleanup owner id executed? deadline)
        (when (file-exists? (string-append owner "/fake-container"))
          (throw 'fake-runtime-state-not-destroyed)))
      (define (retained-root value)
        (let* ((diagnostic (field value 'diagnostic)) (prefix "retained-root=")
               (offset (string-contains diagnostic prefix)))
          (and offset (let* ((start (+ offset (string-length prefix)))
                             (end (string-index diagnostic #\; start)))
                        (substring diagnostic start end)))))
      (dynamic-wind
        (lambda ()
          (set-sandbox! 'base (lambda (name)
                               (if (eq? name 'prepare-owned-runtime-state!)
                                   (lambda (bundle id) (string-append bundle "/runsc-state")) (base name))))
          (set-sandbox! 'smoke (lambda (name)
                                (if (eq? name 'diagnostic-stores) (lambda _ '()) (smoke name))))
          (set-sandbox! 'mount-diagnostic! (lambda _ #t))
          (set-sandbox! 'cleanup-diagnostic! (lambda _ #t))
          (set-sandbox! 'cleanup-runtime! fake-cleanup)
          (set-sandbox! 'observe-cgroup (lambda _ sample)))
        (lambda ()
          (let ((value (run seed)))
            (test-equal "real adapter carries exact ordinary result" "Sandbox: élan" (field value 'text))
            (test-equal "success status" 'ok (field value 'status))
            (test-equal "success has observed initialization" #t (field value 'execution-started?))
             (test-equal "success cleanup proven" #t (field value 'cleanup-complete?))
             (test-equal "success never exposes stderr evidence" #f (field value 'stderr-evidence))
            (test-equal "resource observations explicitly do not claim enforcement" #f
              (field (field value 'resource-observations) 'enforcement-proven?)))
           (test-equal "changed source changes result" "ÉLAN"
             (field (run "(define (workbench text) (string-upcase text))") 'text))
           (let* ((text (make-string 2048 (integer->char 1)))
                  (value (run "(define (workbench text) text)" text)))
             (test-equal "sandbox escaped input crosses production output budget intact" text (field value 'text))
             (test-equal "sandbox multi-pump input has delivery evidence" #t (field value 'execution-started?)))
           (let* ((group (string-append root "/wilkbook-execution-teardown-race"))
                  (marker (string-append root "/action-dispatched"))
                  (original-read (sandbox 'read-kernel-text))
                  (real-observe (field originals 'observe-cgroup)) (vanished-samples 0))
             (mkdir group) (write-text (string-append group "/memory.max") "268435456")
             (dynamic-wind
               (lambda ()
                 (set-sandbox! 'read-kernel-text
                   (lambda (path limit)
                     (if (string=? path (string-append group "/memory.max"))
                         (call-with-input-file path
                           (lambda (port)
                             (remove-tree group)
                             (throw 'system-error "fport_read" "~A" (list (strerror ENODEV)) (list ENODEV))))
                         (original-read path limit))))
                 (set-sandbox! 'observe-cgroup
                   (lambda _
                     (if (file-exists? marker)
                         (begin (set! vanished-samples (+ vanished-samples 1))
                                (real-observe "teardown-race" root))
                         sample))))
               (lambda ()
                 (let* ((source (format #f "(define (workbench text) (call-with-output-file ~s (lambda (p) (display \"dispatched\" p))) (usleep 150000) text)" marker))
                        (value (run source)))
                   (test-assert "post-dispatch ENODEV race was exercised" (positive? vanished-samples))
                   (test-equal "vanished observation does not invalidate ordinary result" 'ok (field value 'status))
                   (test-equal "vanished observation preserves exact result text" "élan" (field value 'text))
                   (test-equal "vanished observation still requires complete cleanup" #t (field value 'cleanup-complete?))
                   (test-equal "discarded partial samples preserve last valid observation" sample
                     (field (field value 'resource-observations) 'last))))
               (lambda () (set-sandbox! 'read-kernel-text original-read)
                 (set-sandbox! 'observe-cgroup (lambda _ sample)))))
           (let ((path (string-append root "/pre-hello-killed.scm")))
             ;; A controlled native signal fixture, not a gVisor CPU-timer test.
             ;; No ordinary hello is emitted. Teardown-sized noise must not erase
             ;; the early interpreter diagnostic, even after the root is removed.
             (write-text path
               "(display \"EARLY-LOADER-FAILURE\\n\" (current-error-port))\n(do ((n 0 (+ n 1))) ((= n 100)) (display \"D0915 18:39:39.000000 197 sandbox.go:1571] Destroying sandbox\\n\" (current-error-port)))\n(force-output (current-error-port)) (kill (getpid) SIGKILL)\n")
             (let* ((value (run seed #:selected-runner path))
                    (evidence (field value 'stderr-evidence))
                    (proof (field (field value 'resource-observations) 'runtime-owner)))
               (test-equal "SIGKILL before hello has no initialization proof" #f (field value 'execution-started?))
               (test-equal "pre-hello signal failure still completes owned cleanup" #t (field value 'cleanup-complete?))
               (test-assert "failed native runtime publishes early stderr evidence after cleanup"
                 (string-contains (field evidence 'text) "EARLY-LOADER-FAILURE"))
               (test-equal "native runtime model exposes host exit 137, not guest raw wait status 9"
                 137 (status:exit-val (field proof 'runtime-status)))))
          (test-equal "adapter replaces donated stdin with EOF" "élan"
            (field (run "(define (workbench text) (if (eof-object? (read-char)) text \"wrong\"))") 'text))
          (test-equal "exact 256 KiB stdout bound" 'ok
            (field (run "(define (workbench text) (display (make-string 262144 #\\x)) (force-output) text)") 'status))
          (let* ((path (string-append root "/exit7-runner.scm")) (original (read-text runner))
                 (needle "    (close-port port)))") (where (string-contains original needle)))
            (unless where (error "runner fixture closing form changed"))
            (write-text path (string-append (substring original 0 where)
                                           "    (close-port port) (primitive-exit 7)))"
                                           (substring original (+ where (string-length needle)))))
            (let ((value (run seed #:selected-runner path)))
              (test-equal "valid present then nonzero exit is failure" 'failed (field value 'status))
              (test-equal "nonzero exit still has complete reap" #t (field value 'cleanup-complete?))))
          (for-each (lambda (pair) (expected-failure (car pair) (cdr pair)))
                    '(("syntax" . "(define (workbench text)")
                      ("wrong result" . "(define (workbench text) 3)")
                      ("empty result" . "(define (workbench text) \"\")")
                      ("no presentation" . "(primitive-exit 0)")
                      ("stdout overflow" . "(define (workbench text) (display (make-string 270000 #\\x)) (force-output) text)")
                      ("stderr overflow" . "(define (workbench text) (display (make-string 270000 #\\x) (current-error-port)) (force-output (current-error-port)) text)")
                      ("malformed protocol" . "(use-modules (rnrs io ports)) (put-bytevector (fdopen 3 \"w0\") #vu8(0 0 0 1 33)) (force-output) (define (workbench text) text)")))
          (let* ((start (clock)) (value (run "(define (workbench text) (let loop () (loop)))" #:seconds 0.9)))
            (test-equal "loop fails" 'failed (field value 'status))
            (test-equal "loop had ordinary initialization" #t (field value 'execution-started?))
            (test-equal "loop process group cleanup proven" #t (field value 'cleanup-complete?))
            (test-assert "loop stays within the original deadline" (< (- (clock) start) 1.3)))
          (for-each
           (lambda (mode)
             (let* ((value (run "(define (workbench text) (let loop () (loop)))" #:control-mode mode))
                    (proof (field (field value 'resource-observations) 'runtime-owner)))
               (test-equal (string-append mode ": guest failure") 'failed (field value 'status))
               (if (equal? mode "normal")
                   (begin
                     (test-equal "guest RPC permits attached Destroy cleanup" #t (field value 'cleanup-complete?))
                     (test-equal "only guest kill RPC was invoked" '("kill") (map car (field proof 'controls)))
                     (test-equal "normal timeout needs no forced host termination" #f (field proof 'forced?)))
                   (let ((retained (retained-root value)))
                     (test-equal (string-append mode ": forced termination withholds cleanup proof") #f (field value 'cleanup-complete?))
                     (test-equal (string-append mode ": no owner cleanup proof published") #f proof)
                     (test-assert (string-append mode ": stale numeric-PID metadata retained")
                       (and retained (file-exists? (string-append retained "/bundle/runsc-state/fake-container"))))
                     (let ((guest (call-with-input-file (string-append retained "/bundle/fake-guest") read)))
                       (test-assert (string-append mode ": guest PID is dead and reaped") (not (live? (car guest)))))))
               (test-assert (string-append mode ": unsafe delete never uses released numeric PID")
                 (not (file-exists? unsafe-delete-marker)))))
           '("normal" "fail-kill" "hang-kill"))
          (let* ((value (run "(define (workbench text) 3)" #:control-mode "stale-after-exit"))
                 (retained (retained-root value)))
            (test-equal "already-reaped leader with stale state cannot claim cleanup" #f (field value 'cleanup-complete?))
            (test-assert "already-reaped leader leaves metadata for inspection"
              (and retained (file-exists? (string-append retained "/bundle/runsc-state/fake-container"))))
            (test-assert "earlier polling reap cannot lead to unsafe numeric-PID delete"
              (not (file-exists? unsafe-delete-marker))))
          (for-each
           (lambda (dead-leader?)
             (let* ((path (string-append root (if dead-leader? "/dead-leader-support.pid" "/setsid-support.pid")))
                    (source (format #f
                      "(define (workbench text) (let ((pid (primitive-fork))) (if (= pid 0) (begin (setsid) (call-with-output-file ~s (lambda (p) (display (getpid) p))) (close-port (current-input-port)) (close-port (current-output-port)) (close-port (current-error-port)) (close-fdes 3) (let loop () (sleep 1) (loop))) (begin (usleep 50000) ~a text))))"
                      path (if dead-leader? "(kill (getppid) SIGKILL)" "")))
                    (value (run source)))
               (test-equal "setsid support invalidates good text / dead leader" 'failed (field value 'status))
               (test-equal "forced setsid termination conservatively retains runtime state" #f (field value 'cleanup-complete?))
               (test-assert "forced setsid termination names retained root" (retained-root value))
               (test-assert "setsid cleanup never invokes unsafe delete" (not (file-exists? unsafe-delete-marker)))
               (test-assert "setsid support killed and reaped despite closed capture FDs"
                 (not (live? (string->number (read-text path)))))))
           '(#f #t))
          (let ((unrelated (spawn "/usr/bin/sleep" '("/usr/bin/sleep" "30"))))
            (dynamic-wind (lambda () #t)
                          (lambda () (run seed)
                            (test-assert "dedicated owner does not reap/signal unrelated authority child" (live? unrelated)))
                          (lambda () (kill unrelated SIGKILL) (waitpid unrelated))))
          (let* ((path (string-append root "/descendant.pid"))
                 (source (format #f "(define (workbench text) (let ((pid (primitive-fork))) (if (= pid 0) (begin (sigaction SIGTERM SIG_IGN) (let loop () (sleep 1) (loop))) (begin (call-with-output-file ~s (lambda (p) (display pid p))) text))))" path))
                 (value (run source)))
            (test-equal "descendant invalidates otherwise good result" 'failed (field value 'status))
            (test-equal "forced descendant termination withholds runtime cleanup proof" #f (field value 'cleanup-complete?))
            (test-assert "descendant is killed and reaped" (not (live? (string->number (read-text path))))))
          (let ((value (run seed #:selected-adapter "/does-not-exist.scm")))
            (test-equal "adapter launch failure" 'failed (field value 'status))
            (test-equal "pre-handshake failure is not execution evidence" #f (field value 'execution-started?))
            (test-equal "pre-handshake child still reaped" #t (field value 'cleanup-complete?)))
           (for-each
            (lambda (observation)
             (set-sandbox! 'observe-cgroup (lambda _ observation))
             (let* ((marker (string-append root "/forbidden-dispatch"))
                  (source (format #f "(define (workbench text) (call-with-output-file ~s (lambda (p) (display text p))) text)" marker))
                  (value (run source)))
             (test-equal "missing live cgroup refuses action" 'failed (field value 'status))
             (test-assert "missing live cgroup diagnostic" (string-contains (field value 'diagnostic) "live cgroup"))
             (test-equal "post-hello missing/wrong controls are not executed failures" #f (field value 'execution-started?))
             (test-equal "post-hello control refusal still proves cleanup" #t (field value 'cleanup-complete?))
             (test-assert "no valid sample before dispatch never authorizes authored code" (not (file-exists? marker)))))
            '(#f ((controls-match? . #f))))
           (set-sandbox! 'observe-cgroup (lambda _ sample))
           (let* ((session (resolve-module '(book-session)))
                  (pump (module-ref session 'endpoint-pump-output!))
                  (byte-budget (module-ref session 'max-output-bytes-per-pump))
                  (frame-budget (module-ref session 'max-output-frames-per-pump)))
             (for-each
              (lambda (mode)
                (let ((partial? #f) (final-budget? #f) (pumps 0))
                  (dynamic-wind
                    (lambda ()
                      (module-set! session 'max-output-bytes-per-pump
                                   (if (memq mode '(partial closed-after-budget)) 1 byte-budget))
                      (module-set! session 'max-output-frames-per-pump (if (eq? mode 'final-budget) 1 frame-budget))
                      (module-set! session 'endpoint-pump-output!
                        (lambda (endpoint)
                          (set! pumps (+ pumps 1))
                          (when (eq? mode 'broken-write)
                            (shutdown ((@@ (book-session) endpoint-binding-socket)
                                       ((@@ (book-session) session-endpoint-binding) endpoint)) 1))
                          (let* ((pumped (pump endpoint))
                                 (status (endpoint-pump-result-status pumped))
                                 (snapshot (host-session-snapshot endpoint)))
                            (when (eq? status 'budget)
                              (if (positive? (field snapshot "outbound_frames")) (set! partial? #t)
                                  (set! final-budget? #t)))
                            (if (memq mode '(partial closed-after-budget))
                                (begin (close-session! endpoint)
                                       (if (eq? mode 'partial) (pump endpoint) pumped))
                                pumped)))))
                    (lambda ()
                      (let ((value (run "(define (workbench text)")))
                        (test-assert (format #f "sandbox ~a reached queued output" mode) (positive? pumps))
                        (test-equal (format #f "sandbox ~a fails" mode) 'failed (field value 'status))
                        (test-equal (format #f "sandbox ~a delivery evidence" mode) (eq? mode 'final-budget)
                          (field value 'execution-started?))
                        (test-equal (format #f "sandbox ~a cleanup independent" mode) #t (field value 'cleanup-complete?))
                        (when (memq mode '(partial closed-after-budget))
                          (test-assert "sandbox partial byte budget left unsent frames" partial?))
                        (when (eq? mode 'final-budget)
                          (test-assert "sandbox final send hit budget with empty queue" final-budget?))))
                    (lambda ()
                      (module-set! session 'endpoint-pump-output! pump)
                      (module-set! session 'max-output-bytes-per-pump byte-budget)
                      (module-set! session 'max-output-frames-per-pump frame-budget)))))
              '(broken-write partial closed-after-budget final-budget)))
          (set-sandbox! 'cleanup-runtime! (lambda _ (throw 'synthetic-unmount-refusal)))
           (let ((value (run seed)))
             (test-equal "runtime cleanup failure revokes good text" 'failed (field value 'status))
            (test-equal "runtime cleanup failure has no text" "" (field value 'text))
            (test-equal "runtime cleanup failure flagged" #f (field value 'cleanup-complete?))
             (test-assert "runtime cleanup failure names retained root"
               (string-contains (field value 'diagnostic) "cleanup-incomplete; retained-root=")))
           (let* ((value (run "(primitive-exit 0)")) (diagnostic (field value 'diagnostic)))
             (test-assert "initial protocol failure survives subsequent cleanup failure"
               (string-contains diagnostic "protocol EOF before preview result"))
             (test-assert "first cleanup failure also appears in failed-run diagnostic"
               (string-contains diagnostic "cleanup=synthetic-unmount-refusal"))
             (test-assert "dual failure keeps its actual retained root"
               (file-exists? (retained-root value))))
           (set-sandbox! 'cleanup-runtime! fake-cleanup)
          (let ((value (parameterize (((@@ (workbench-preview) cleanup-clock) (lambda () (+ (clock) 30))))
                         (run seed))))
            (test-equal "original-deadline tree removal failure flagged" #f (field value 'cleanup-complete?))
            (test-equal "tree removal failure invalidates success" 'failed (field value 'status)))
          (let ((before (open-fds)) (count 0)
                (open-pipe (@@ (workbench-preview) capture-open-pipe)))
            (let ((value (parameterize ((open-pipe
                                        (lambda () (set! count (+ count 1))
                                          (if (= count 2) (throw 'synthetic-second-pipe-failure) (pipe)))))
                           (run seed))))
              (test-equal "second pipe failure" 'failed (field value 'status))
              (test-equal "partial pipe acquisition closes all FDs" before (open-fds))
              (test-equal "pipe failure before initialization" #f (field value 'execution-started?))))
          (test-equal "subreaper setting restored" old-subreaper ((@@ (workbench-preview) subreaper?))))
        (lambda () (for-each (lambda (pair) (set-sandbox! (car pair) (cdr pair))) originals))))

    (let* ((diagnostic ((sandbox 'failure-diagnostic) "/run/workbench/preview.test"
                        (string-append "first-cause " (make-string 2000 #\x))
                        (string-append "cleanup-cause " (make-string 2000 #\y))
                        (string-append (make-string 1024 #\z) "final-runtime-error")))
           (value ((sandbox 'result) 'failed "" diagnostic))
           (public (field value 'diagnostic)))
      (test-assert "public failure summary respects 1024 characters" (<= (string-length public) 1024))
      (test-assert "long failure cannot consume cleanup cause budget" (string-contains public "cleanup=cleanup-cause"))
      (test-assert "long cleanup cannot consume first failure budget" (string-contains public "failure=first-cause"))
      (test-assert "bounded public summary retains final stderr error" (string-suffix? "final-runtime-error" public))
      (test-assert "bounded public summary retains full normal root path"
        (string-contains public "retained-root=/run/workbench/preview.test;")))

    (display "Evidence: public runtime refuses missing prerequisites (no native fallback)\n")
    (let ((value ((make-sandbox-preview `((language-closure . ()) (timeout-seconds . 0))) seed "x")))
      (test-equal "config callback returns ordinary failed contract" 'failed (field value 'status))
      (test-equal "invalid timeout has no execution proof" #f (field value 'execution-started?))
      (test-equal "invalid timeout conservatively lacks cleanup proof" #f (field value 'cleanup-complete?)))
    (let ((value (preview-sandbox seed "x" #:timeout-seconds 31)))
      (test-equal "trusted timeout cannot exceed global bound" 'failed (field value 'status)))
    (unless (= (getuid) 0)
      (test-assert "real runtime preflight refuses non-root without touching cgroups"
        (rejected? (lambda () ((sandbox 'runtime-preflight!) "nonroot-offline-test")))))
    (let ((mutex (@@ (workbench-preview) native-mutex)))
      (lock-mutex mutex)
      (dynamic-wind
        (lambda () #t)
        (lambda ()
          (let ((value (join-thread (call-with-new-thread (lambda () (preview-sandbox seed "x"))))))
            (test-equal "overlapping native/sandbox execution rejected" 'failed (field value 'status))
            (test-assert "overlap diagnostic" (string-contains (field value 'diagnostic) "active"))))
        (lambda () (unlock-mutex mutex))))
    (display "Actual runsc execution: NOT RUN by this offline test; use the QEMU integration gate.\n"))
  (lambda () (remove-tree root)))
(let ((runner (test-runner-current)))
  (test-end "workbench-sandbox")
  (exit (if (zero? (test-runner-fail-count runner)) 0 1)))
