#!/bin/sh
# Differential + structural gate for wbf-clut, the C CLUT compiler
# (doc/direct-mode-adoption.md P1).
#
# Usage: run-clut-tests.sh ./build/wbf-clut ./build/wbf-clut-selftest \
#                          ./build/wbf-info
#
# Environment:
#   WBF=          the device's own ebc.wbf.  REQUIRED; never committed, so
#                 CI can never run any of this.  Unset => loud SKIP, exit 0.
#   CLUT_REF=     directory holding hrdl's wbf_to_custom.py + read_file.py
#                 (default $HOME/src/reference/pinenote-dist/bin, the
#                 location doc/reference-register.md's clone recipe makes).
#   CLUT_REF_BIN= a custom_wf.bin already generated by that script, used
#                 only when the script itself cannot be run here.
#   CLUT_PYTHON=  python interpreter with numpy (default python3).
#
# THE GATE IS BYTE-IDENTICAL OUTPUT, and the reason it has to be is that
# wbf_to_custom.py carries two bugs whose OUTPUT this compiler reproduces
# on purpose (see wbf-clut.c's header, doc/driver-findings-report.md).  A
# clean-room implementation written to what the reference *means* produces
# different bytes and would be wrong to ship.
#
# VACUITY: a differential passes trivially if both sides produce nothing,
# and "identical" proves nothing about whether the quirks are what made it
# identical.  So the reference comparison is bracketed by controls: the
# structural block below rejects an empty/degenerate output without any
# reference at all, and the mutation block requires each deliberately
# broken variant to DIFFER.  Neither side of that bracket can pass on a
# tool that emits nothing.
set -eu

clut=$1
clut_selftest=$2
wbf_info=$3

: "${WBF:=}"
: "${CLUT_REF:=$HOME/src/reference/pinenote-dist/bin}"
: "${CLUT_REF_BIN:=}"
: "${CLUT_PYTHON:=python3}"

if [ -z "$WBF" ]; then
  echo 'SKIP: clut-check -- WBF= is unset.'
  echo '      The waveform is per-device calibration and is NEVER committed,'
  echo '      so CI cannot cover the CLUT compiler at all.  Run locally:'
  echo '        make clut-check WBF=/path/to/ebc.wbf'
  exit 0
fi
if [ ! -r "$WBF" ]; then
  echo "FAIL: WBF=$WBF is not readable" >&2
  exit 1
fi

# Everything derived from the waveform is per-device calibration data in
# another encoding.  It is written to a private temp dir, never into the
# repo, and removed on exit.
work=$(mktemp -d)
trap 'rm -rf -- "$work"' EXIT HUP INT TERM

fail=0
pass() { echo "PASS: $1"; }
bad() { echo "FAIL: $1" >&2; fail=1; }

le32_at() {
  _bytes=$(od -An -tu1 -j "$2" -N4 -v "$1")
  set -- $_bytes
  echo $(( $1 + $2 * 256 + $3 * 65536 + $4 * 16777216 ))
}

u8_at() {
  od -An -tu1 -j "$2" -N1 -v "$1" | tr -d ' \n'
}

# ---------------------------------------------------------------- structural
# These need no reference.  They are what stops "byte-identical" from being
# satisfiable by a tool that writes an empty file.

ours=$work/ours.bin
if "$clut" "$WBF" "$ours" > "$work/ours.log" 2>&1; then
  pass "wbf-clut exits 0 on the device waveform"
else
  bad "wbf-clut exited nonzero"
  cat "$work/ours.log" >&2
  exit 1
fi

if [ -s "$ours" ]; then
  pass "wbf-clut wrote a non-empty CLUT"
else
  bad "wbf-clut produced no output"
  exit 1
fi

magic=$(dd if="$ours" bs=1 count=8 2>/dev/null)
if [ "$magic" = "CLUT0002" ]; then
  pass "magic CLUT0002"
else
  bad "magic is '$magic'"
fi

n_luts=$(le32_at "$ours" 8)
size=$(wc -c < "$ours")
lut_bytes=16398
expect=$(( 12 + n_luts * lut_bytes ))
if [ "$size" -eq "$expect" ]; then
  pass "size $size == 12 + $n_luts * $lut_bytes"
else
  bad "size $size != 12 + $n_luts * $lut_bytes ($expect)"
fi

# quirk: the .wbf header stores temp_range_count off by one, the same
# convention as mode_count (raw 7, yet the driver itself reads DU4 from
# mode index 7).  wbf_to_custom.py adds the one and compiles 14 LUTs; the
# driver's pvi_wbf_get_temp_index does not and so can never return the top
# bin.  Pinned here because the CLUT's LUT count is the visible
# consequence (doc/driver-findings-report.md).
info_bins=$("$wbf_info" "$WBF" 25 2>/dev/null |
            sed -n 's/^temp_range_count: \([0-9]*\)$/\1/p')
if [ -n "$info_bins" ] && [ "$n_luts" -eq $(( info_bins + 1 )) ]; then
  pass "quirk: n_luts $n_luts == the driver's temp_range_count ($info_bins) + 1"
else
  bad "n_luts $n_luts vs wbf-info temp_range_count '$info_bins'"
fi

# A file of zeros would satisfy magic + size.  Require real content, and
# require it not to be uniformly nonzero either (the cells past each
# mode's sequences must stay neutral).
nonzero=$(tr -d '\000' < "$ours" | wc -c)
if [ "$nonzero" -gt $(( size / 20 )) ] && [ "$nonzero" -lt "$size" ]; then
  pass "content is neither empty nor saturated ($nonzero/$size nonzero bytes)"
else
  bad "degenerate content: $nonzero of $size bytes nonzero"
fi

# Per-LUT offsets: index 0 is reserved, the five real modes take strictly
# ascending offsets, IDLE takes the final cursor without advancing it, and
# nothing may reach past the 64-deep sequence axis.
off_ok=1
t=0
while [ "$t" -lt "$n_luts" ] && [ "$off_ok" -eq 1 ]; do
  base=$(( 12 + t * lut_bytes + 8 ))
  prev=0
  w=0
  while [ "$w" -lt 6 ] && [ "$off_ok" -eq 1 ]; do
    o=$(u8_at "$ours" $(( base + w )))
    # DU (w=0) starts the cursor at 1; every later mode is strictly past
    # the one before it; IDLE (w=5) takes the final cursor, which may
    # legally land ON 64 because it addresses no cells of its own.
    if [ "$w" -eq 0 ] && [ "$o" -ne 1 ]; then
      off_ok=0
      bad "lut $t offset[DU]=$o, expected 1"
    elif [ "$o" -le "$prev" ]; then
      off_ok=0
      bad "lut $t offset[$w]=$o does not exceed $prev"
    elif [ "$w" -lt 5 ] && [ "$o" -ge 64 ]; then
      off_ok=0
      bad "lut $t offset[$w]=$o starts at or past the 64-cell axis"
    elif [ "$o" -gt 64 ]; then
      off_ok=0
      bad "lut $t IDLE offset=$o is past the 64-cell axis"
    fi
    prev=$o
    w=$(( w + 1 ))
  done
  t=$(( t + 1 ))
done
if [ "$off_ok" -eq 1 ]; then
  pass "offsets ascend from 1 and stay inside 64 in all $n_luts LUTs"
fi

# The two consumers of the extracted decoder must agree about the same
# (mode, temperature) pair, or one of them is reading a different LUT.
info_gc16=$("$wbf_info" "$WBF" 25 2>/dev/null |
            sed -n 's/^GC16 bin 8 ([0-9-]* C): temp_index=[0-9]* phases=\([0-9]*\)$/\1/p')
clut_gc16=$("$clut" -v "$WBF" "$work/verbose.bin" 2>/dev/null |
            sed -n 's/^clut: lut=8 mode=GC16 mode_index=[0-9]* phases=\([0-9]*\)$/\1/p')
if [ -n "$info_gc16" ] && [ "$info_gc16" = "$clut_gc16" ]; then
  pass "wbf-clut and wbf-info agree on GC16 bin 8 phases ($info_gc16)"
else
  bad "GC16 bin 8 phases: wbf-info='$info_gc16' wbf-clut='$clut_gc16'"
fi

# Determinism.  Each invocation is in an `if' so a nonzero exit is
# reported as a failed assertion rather than tripping `set -e' and taking
# the whole run down before the summary.
if "$clut" "$WBF" "$work/again.bin" > /dev/null 2>&1 &&
   cmp -s "$ours" "$work/again.bin"; then
  pass "deterministic across runs"
else
  bad "second run failed or differed from the first"
fi

# The self-test binary is the same source; without a --mutate flag it must
# be byte-for-byte the shipping compiler, or the mutation controls below
# would be testing a different program.
if "$clut_selftest" "$WBF" "$work/selftest-plain.bin" > /dev/null 2>&1 &&
   cmp -s "$ours" "$work/selftest-plain.bin"; then
  pass "selftest build without --mutate matches the shipping build"
else
  bad "selftest build failed or differs from the shipping build with no mutation"
fi

# The shipping binary must not carry the knobs at all.
if "$clut" --mutate=drop-suffix-off "$WBF" "$work/nope.bin" > /dev/null 2>&1; then
  bad "the shipping wbf-clut accepted --mutate=drop-suffix-off"
else
  pass "the shipping wbf-clut rejects --mutate flags"
fi

# A truncated waveform must fail loudly rather than emit a short CLUT --
# under direct mode a malformed custom_wf.bin is a -EINVAL probe failure,
# i.e. a device with no display (doc/direct-mode-adoption.md D4).
head -c 4096 "$WBF" > "$work/truncated.wbf"
if "$clut" "$work/truncated.wbf" "$work/truncated.bin" > /dev/null 2>&1; then
  bad "wbf-clut accepted a truncated waveform"
else
  if [ -e "$work/truncated.bin" ]; then
    bad "wbf-clut left an output file behind after failing"
  else
    pass "wbf-clut rejects a truncated waveform and writes nothing"
  fi
fi

# ----------------------------------------------------------------- mutations
# quirk: controls.  Each flips ONE reproduced upstream behaviour; each must
# change the bytes.  If any of these matched, the byte-identical result
# above would be evidence of nothing, because the quirk it names would not
# be load-bearing.
for mutation in drop-suffix-off collision-first-wins axis-swap; do
  out=$work/mut-$mutation.bin
  if "$clut_selftest" "--mutate=$mutation" "$WBF" "$out" > /dev/null 2>&1; then
    if [ ! -s "$out" ]; then
      bad "quirk: --mutate=$mutation produced no output (control is vacuous)"
    elif cmp -s "$ours" "$out"; then
      bad "quirk: --mutate=$mutation changed nothing -- that behaviour is not load-bearing, so the differential proves less than it claims"
    else
      pass "quirk: --mutate=$mutation changes the output"
    fi
  else
    # drop-suffix-off can legitimately blow past the 64-cell axis, since
    # the dropped entry is what kept max_len inside it.  A hard error is
    # still a difference from the reference, which is what the control is
    # for -- but say which happened.
    pass "quirk: --mutate=$mutation is rejected outright (still a difference)"
  fi
done

# ----------------------------------------------------------------- reference
ref=""
ref_how=""
if [ -r "$CLUT_REF/wbf_to_custom.py" ] && [ -r "$CLUT_REF/read_file.py" ]; then
  # wbf_to_custom.py writes ./custom_wf.bin, so it has to run in the temp
  # dir -- never in the repo.
  mkdir -p "$work/pyref"
  if ( cd "$work/pyref" &&
       PYTHONPATH="$CLUT_REF" "$CLUT_PYTHON" \
         "$CLUT_REF/wbf_to_custom.py" "$WBF" ) > "$work/pyref.log" 2>&1 &&
     [ -s "$work/pyref/custom_wf.bin" ]; then
    ref=$work/pyref/custom_wf.bin
    ref_how="regenerated by $CLUT_REF/wbf_to_custom.py"
  else
    echo "NOTE: could not run $CLUT_REF/wbf_to_custom.py (needs numpy):" >&2
    tail -n 5 "$work/pyref.log" >&2
  fi
fi
if [ -z "$ref" ] && [ -n "$CLUT_REF_BIN" ] && [ -s "$CLUT_REF_BIN" ]; then
  ref=$CLUT_REF_BIN
  ref_how="pre-generated file $CLUT_REF_BIN"
fi

if [ -z "$ref" ]; then
  echo 'SKIP: the byte-identical differential -- no runnable reference.'
  echo "      Looked for $CLUT_REF/wbf_to_custom.py (with numpy on PATH)"
  echo '      and $CLUT_REF_BIN.  The structural and quirk: controls above'
  echo '      ran, but NOTHING above proves fidelity to wbf_to_custom.py.'
  echo '      Clone it per doc/reference-register.md and re-run:'
  echo '        make clut-check WBF=... CLUT_REF=.../pinenote-dist/bin'
else
  echo "reference: $ref_how"
  ref_size=$(wc -c < "$ref")
  if [ "$ref_size" -eq "$size" ]; then
    pass "reference and wbf-clut agree on size ($size bytes)"
  else
    bad "reference is $ref_size bytes, wbf-clut wrote $size"
  fi
  if [ "$ref_size" -gt 0 ] && cmp -s "$ref" "$ours"; then
    pass "BYTE-IDENTICAL to wbf_to_custom.py"
  else
    bad "wbf-clut output differs from wbf_to_custom.py"
    cmp "$ref" "$ours" >&2 || true
  fi
fi

if [ "$fail" -eq 0 ]; then
  echo "ALL TESTS PASSED"
else
  echo "TESTS FAILED" >&2
fi
exit "$fail"
