#!/bin/sh
# Differential + structural gate for wbf-clut, the C CLUT compiler
# (doc/direct-mode-adoption.md P1).
#
# Usage: run-clut-tests.sh ./build/wbf-clut ./build/wbf-clut-selftest \
#                          ./build/wbf-info
#
# Environment:
#   WBF=          the device's own ebc.wbf.  REQUIRED; never committed, so
#                 CI can never run any of this.  Unset => loud SKIP, exit 0.
#   CLUT_REF=     directory holding hrdl's wbf_to_custom.py + read_file.py
#                 (default $HOME/src/reference/pinenote-dist/bin, the
#                 location doc/reference-register.md's clone recipe makes).
#   CLUT_REF_BIN= a custom_wf.bin already generated by that script, used
#                 only when the script itself cannot be run here.
#   CLUT_PYTHON=  python interpreter with numpy (default python3).
#
# THE GATE IS BYTE-IDENTICAL OUTPUT, and the reason it has to be is that
# wbf_to_custom.py carries two bugs whose OUTPUT this compiler reproduces
# on purpose (see wbf-clut.c's header, doc/driver-findings-report.md).  A
# clean-room implementation written to what the reference *means* produces
# different bytes and would be wrong to ship.
#
# VACUITY: a differential passes trivially if both sides produce nothing,
# and "identical" proves nothing about whether the quirks are what made it
# identical.  So the reference comparison is bracketed by controls: the
# structural block below rejects an empty/degenerate output without any
# reference at all, and the mutation block requires each deliberately
# broken variant to DIFFER.  Neither side of that bracket can pass on a
# tool that emits nothing.
set -eu

clut=$1
clut_selftest=$2
wbf_info=$3

: "${WBF:=}"
: "${CLUT_REF:=$HOME/src/reference/pinenote-dist/bin}"
: "${CLUT_REF_BIN:=}"
: "${CLUT_PYTHON:=python3}"

if [ -z "$WBF" ]; then
  echo 'SKIP: clut-check -- WBF= is unset.'
  echo '      The waveform is per-device calibration and is NEVER committed,'
  echo '      so CI cannot cover the CLUT compiler at all.  Run locally:'
  echo '        make clut-check WBF=/path/to/ebc.wbf'
  exit 0
fi
if [ ! -r "$WBF" ]; then
  echo "FAIL: WBF=$WBF is not readable" >&2
  exit 1
fi

# Everything derived from the waveform is per-device calibration data in
# another encoding.  It is written to a private temp dir, never into the
# repo, and removed on exit.
work=$(mktemp -d)
trap 'rm -rf -- "$work"' EXIT HUP INT TERM

fail=0
pass() { echo "PASS: $1"; }
bad() { echo "FAIL: $1" >&2; fail=1; }

le32_at() {
  _bytes=$(od -An -tu1 -j "$2" -N4 -v "$1")
  set -- $_bytes
  echo $(( $1 + $2 * 256 + $3 * 65536 + $4 * 16777216 ))
}

u8_at() {
  od -An -tu1 -j "$2" -N1 -v "$1" | tr -d ' \n'
}

# ---------------------------------------------------------------- structural
# These need no reference.  They are what stops "byte-identical" from being
# satisfiable by a tool that writes an empty file.

# ----------------------------------------------------------------------
# --class-source: the display-study remap knob (P4).  Identity must be a
# no-op byte-for-byte (so the reference differential below still covers
# the shipping path), a real remap must change the bytes and say so in
# -v, and junk must be refused.  Without the identity control, a build
# that silently ignored the option would pass every other test here.


ours=$work/ours.bin
if "$clut" "$WBF" "$ours" > "$work/ours.log" 2>&1; then
  pass "wbf-clut exits 0 on the device waveform"
else
  bad "wbf-clut exited nonzero"
  cat "$work/ours.log" >&2
  exit 1
fi

if [ -s "$ours" ]; then
  pass "wbf-clut wrote a non-empty CLUT"
else
  bad "wbf-clut produced no output"
  exit 1
fi

magic=$(dd if="$ours" bs=1 count=8 2>/dev/null)
if [ "$magic" = "CLUT0002" ]; then
  pass "magic CLUT0002"
else
  bad "magic is '$magic'"
fi

# ----------------------------------------------------------------------
# --balance-report: the charge-balance analysis (P4 groundwork for
# hand-crafted rows).  The arithmetic is positive-controlled on
# CONSTRUCTED rows in the selftest binary; the real-waveform run can
# then be held to structure and determinism honestly.
if "$clut_selftest" --selftest-balance > "$work/bal-self.log" 2>&1 \
   && grep -q "PASS: selftest-balance" "$work/bal-self.log"; then
  pass "selftest-balance arithmetic controls"
else
  bad "selftest-balance failed"
  cat "$work/bal-self.log" >&2
fi
if "$clut" --selftest-balance "$WBF" /dev/null >/dev/null 2>&1; then
  bad "the shipping wbf-clut accepted --selftest-balance"
else
  pass "shipping build refuses --selftest-balance"
fi

if "$clut" --balance-report "$WBF" > "$work/bal1.log" 2>&1; then
  pass "--balance-report (report-only, no OUTPUT) exits 0"
else
  bad "--balance-report exited nonzero"
  cat "$work/bal1.log" >&2
fi
if grep -q "^balance: lut=0 mode=DU " "$work/bal1.log" \
   && grep -q "^balance: lut=0 mode=GC16 " "$work/bal1.log"; then
  pass "balance report covers the modes"
else
  bad "balance report is missing mode lines"
fi
if ! grep -q "clut: wrote" "$work/bal1.log"; then
  pass "report-only mode writes no CLUT"
else
  bad "report-only mode wrote output anyway"
fi
"$clut" --balance-report "$WBF" > "$work/bal2.log" 2>&1 || true
if cmp -s "$work/bal1.log" "$work/bal2.log"; then
  pass "balance report is deterministic"
else
  bad "balance report differs between identical runs"
fi
if grep -q "phase3_runs=0" "$work/bal1.log" \
   && ! grep -E "phase3_runs=[1-9]" "$work/bal1.log" >/dev/null; then
  pass "vendor table uses no phase-3 runs (observation pin: revisit the impulse model if this ever fails)"
else
  bad "phase-3 runs appeared -- the impulse arithmetic's phase-3 handling is now load-bearing; decide its meaning before trusting the report"
fi

cs_id=$work/cs-identity.bin
if "$clut" --class-source=GL16:GL16 "$WBF" "$cs_id" >/dev/null 2>&1 \
   && cmp -s "$ours" "$cs_id"; then
  pass "--class-source identity (GL16:GL16) is byte-identical to default"
else
  bad "--class-source=GL16:GL16 changed the output or failed -- the option is not a clean no-op"
fi

cs_swap=$work/cs-swap.bin
if "$clut" -v --class-source=GL16:GC16 "$WBF" "$cs_swap" > "$work/cs-swap.log" 2>&1; then
  if cmp -s "$ours" "$cs_swap"; then
    bad "--class-source=GL16:GC16 produced identical bytes -- the remap did nothing"
  else
    pass "--class-source=GL16:GC16 changes the output"
  fi
  if grep -q "mode=GL16 from=GC16" "$work/cs-swap.log"; then
    pass "-v reports the GL16 slot sourcing GC16"
  else
    bad "-v does not report the remap (mode=GL16 from=GC16 missing)"
  fi
  gl16_len=$(grep -o "mode=GL16 from=GC16 rows=[0-9]* maxlen=[0-9]*" "$work/cs-swap.log" | head -1 | grep -o "maxlen=[0-9]*")
  gc16_len=$(grep -o "mode=GC16 from=GC16 rows=[0-9]* maxlen=[0-9]*" "$work/cs-swap.log" | head -1 | grep -o "maxlen=[0-9]*")
  if [ -n "$gl16_len" ] && [ "$gl16_len" = "$gc16_len" ]; then
    pass "remapped GL16 slot carries GC16's length ($gl16_len)"
  else
    bad "remapped GL16 maxlen '$gl16_len' != GC16 maxlen '$gc16_len'"
  fi
else
  bad "--class-source=GL16:GC16 exited nonzero"
fi

# Source-only classes (2026-08-26): real wbf modes the CLUT format has
# no slot for, loadable INTO a slot.  Two pins carry findings, not just
# plumbing:
#   * A2 into the DU slot compiles and differs -- the fast-mono-UI
#     lever (6 non-neutral rows on this panel).
#   * GLD16 into the GL16 slot compiles and is BYTE-IDENTICAL to the
#     identity table on this panel -- the observation that REFUTED the
#     "shipping turns were REGAL" theory (doc/status.md 2026-08-26):
#     whatever refresh_waveform=6 selected, it was this same table.
#     If a future wbf pull breaks this identity, that is a finding
#     about the panel, not a tool bug -- re-read the theory before
#     re-pinning.
if "$clut" -v --class-source=DU:A2 "$WBF" "$work/cs-a2.bin" > "$work/cs-a2.log" 2>&1; then
  if cmp -s "$ours" "$work/cs-a2.bin"; then
    bad "--class-source=DU:A2 produced identical bytes -- the remap did nothing"
  else
    pass "--class-source=DU:A2 changes the output (the fast-mono-UI lever)"
  fi
  if grep -q "mode=DU from=A2" "$work/cs-a2.log"; then
    pass "-v reports the DU slot sourcing A2"
  else
    bad "-v does not report the A2 remap"
  fi
else
  bad "--class-source=DU:A2 exited nonzero"
fi

if "$clut" --class-source=GL16:GLD16 "$WBF" "$work/cs-gld16.bin" >/dev/null 2>&1; then
  if cmp -s "$ours" "$work/cs-gld16.bin"; then
    pass "GLD16 into the GL16 slot is byte-identical on this panel (the REGAL refutation, pinned)"
  else
    bad "GLD16 table now DIFFERS from GL16 on this panel -- a finding, not a failure; re-read the theory"
  fi
else
  bad "--class-source=GL16:GLD16 exited nonzero"
fi

if "$clut" --class-source=A2:GL16 "$WBF" "$work/cs-srconly.bin" >/dev/null 2>&1; then
  bad "a source-only class was accepted as a TARGET"
else
  pass "--class-source=A2:GL16 is refused (A2 is source-only)"
fi

if "$clut" --class-source=GL16:NOPE "$WBF" "$work/cs-bad.bin" >/dev/null 2>&1; then
  bad "--class-source with an unknown class was accepted"
else
  pass "--class-source=GL16:NOPE is refused"
fi
if "$clut" --class-source=GL16 "$WBF" "$work/cs-bad2.bin" >/dev/null 2>&1; then
  bad "--class-source without :SOURCE was accepted"
else
  pass "--class-source=GL16 (malformed) is refused"
fi

n_luts=$(le32_at "$ours" 8)
size=$(wc -c < "$ours")
lut_bytes=16398
expect=$(( 12 + n_luts * lut_bytes ))
if [ "$size" -eq "$expect" ]; then
  pass "size $size == 12 + $n_luts * $lut_bytes"
else
  bad "size $size != 12 + $n_luts * $lut_bytes ($expect)"
fi

# quirk: the .wbf header stores temp_range_count off by one, the same
# convention as mode_count (raw 7, yet the driver itself reads DU4 from
# mode index 7).  wbf_to_custom.py adds the one and compiles 14 LUTs; the
# driver's pvi_wbf_get_temp_index does not and so can never return the top
# bin.  Pinned here because the CLUT's LUT count is the visible
# consequence (doc/driver-findings-report.md).
info_bins=$("$wbf_info" "$WBF" 25 2>/dev/null |
            sed -n 's/^temp_range_count: \([0-9]*\)$/\1/p')
if [ -n "$info_bins" ] && [ "$n_luts" -eq $(( info_bins + 1 )) ]; then
  pass "quirk: n_luts $n_luts == the driver's temp_range_count ($info_bins) + 1"
else
  bad "n_luts $n_luts vs wbf-info temp_range_count '$info_bins'"
fi

# A file of zeros would satisfy magic + size.  Require real content, and
# require it not to be uniformly nonzero either (the cells past each
# mode's sequences must stay neutral).
nonzero=$(tr -d '\000' < "$ours" | wc -c)
if [ "$nonzero" -gt $(( size / 20 )) ] && [ "$nonzero" -lt "$size" ]; then
  pass "content is neither empty nor saturated ($nonzero/$size nonzero bytes)"
else
  bad "degenerate content: $nonzero of $size bytes nonzero"
fi

# Per-LUT offsets: index 0 is reserved, the five real modes take strictly
# ascending offsets, IDLE takes the final cursor without advancing it, and
# nothing may reach past the 64-deep sequence axis.
off_ok=1
t=0
while [ "$t" -lt "$n_luts" ] && [ "$off_ok" -eq 1 ]; do
  base=$(( 12 + t * lut_bytes + 8 ))
  prev=0
  w=0
  while [ "$w" -lt 6 ] && [ "$off_ok" -eq 1 ]; do
    o=$(u8_at "$ours" $(( base + w )))
    # DU (w=0) starts the cursor at 1; every later mode is strictly past
    # the one before it; IDLE (w=5) takes the final cursor, which may
    # legally land ON 64 because it addresses no cells of its own.
    if [ "$w" -eq 0 ] && [ "$o" -ne 1 ]; then
      off_ok=0
      bad "lut $t offset[DU]=$o, expected 1"
    elif [ "$o" -le "$prev" ]; then
      off_ok=0
      bad "lut $t offset[$w]=$o does not exceed $prev"
    elif [ "$w" -lt 5 ] && [ "$o" -ge 64 ]; then
      off_ok=0
      bad "lut $t offset[$w]=$o starts at or past the 64-cell axis"
    elif [ "$o" -gt 64 ]; then
      off_ok=0
      bad "lut $t IDLE offset=$o is past the 64-cell axis"
    fi
    prev=$o
    w=$(( w + 1 ))
  done
  t=$(( t + 1 ))
done
if [ "$off_ok" -eq 1 ]; then
  pass "offsets ascend from 1 and stay inside 64 in all $n_luts LUTs"
fi

# The two consumers of the extracted decoder must agree about the same
# (mode, temperature) pair, or one of them is reading a different LUT.
info_gc16=$("$wbf_info" "$WBF" 25 2>/dev/null |
            sed -n 's/^GC16 bin 8 ([0-9-]* C): temp_index=[0-9]* phases=\([0-9]*\)$/\1/p')
clut_gc16=$("$clut" -v "$WBF" "$work/verbose.bin" 2>/dev/null |
            sed -n 's/^clut: lut=8 mode=GC16 mode_index=[0-9]* phases=\([0-9]*\)$/\1/p')
if [ -n "$info_gc16" ] && [ "$info_gc16" = "$clut_gc16" ]; then
  pass "wbf-clut and wbf-info agree on GC16 bin 8 phases ($info_gc16)"
else
  bad "GC16 bin 8 phases: wbf-info='$info_gc16' wbf-clut='$clut_gc16'"
fi

# Determinism.  Each invocation is in an `if' so a nonzero exit is
# reported as a failed assertion rather than tripping `set -e' and taking
# the whole run down before the summary.
if "$clut" "$WBF" "$work/again.bin" > /dev/null 2>&1 &&
   cmp -s "$ours" "$work/again.bin"; then
  pass "deterministic across runs"
else
  bad "second run failed or differed from the first"
fi

# The self-test binary is the same source; without a --mutate flag it must
# be byte-for-byte the shipping compiler, or the mutation controls below
# would be testing a different program.
if "$clut_selftest" "$WBF" "$work/selftest-plain.bin" > /dev/null 2>&1 &&
   cmp -s "$ours" "$work/selftest-plain.bin"; then
  pass "selftest build without --mutate matches the shipping build"
else
  bad "selftest build failed or differs from the shipping build with no mutation"
fi

# The shipping binary must not carry the knobs at all.
if "$clut" --mutate=drop-suffix-off "$WBF" "$work/nope.bin" > /dev/null 2>&1; then
  bad "the shipping wbf-clut accepted --mutate=drop-suffix-off"
else
  pass "the shipping wbf-clut rejects --mutate flags"
fi

# A truncated waveform must fail loudly rather than emit a short CLUT --
# under direct mode a malformed custom_wf.bin is a -EINVAL probe failure,
# i.e. a device with no display (doc/direct-mode-adoption.md D4).
head -c 4096 "$WBF" > "$work/truncated.wbf"
if "$clut" "$work/truncated.wbf" "$work/truncated.bin" > /dev/null 2>&1; then
  bad "wbf-clut accepted a truncated waveform"
else
  if [ -e "$work/truncated.bin" ]; then
    bad "wbf-clut left an output file behind after failing"
  else
    pass "wbf-clut rejects a truncated waveform and writes nothing"
  fi
fi

# ------------------------------------------------------- decode fidelity
# The strongest pin this suite has: the DEFAULT compile must be
# byte-exact to what the shipping hardware LUT engine reads -- verified
# by wbf-clut-diff (the verbatim drm_epd_helper reference vs an
# independent kernel-semantics walk) reporting ZERO divergence of any
# class.  This is the 2026-08-27 fix's standing regression gate.
clut_diff=$(dirname "$clut")/wbf-clut-diff
if [ ! -x "$clut_diff" ]; then
  bad "wbf-clut-diff not built beside wbf-clut -- the fidelity gate cannot run"
else
  diff_out=$("$clut_diff" "$WBF" "$ours" 2>&1) || true
  if printf '%s' "$diff_out" | grep -q 'RESULT: ok' &&
     printf '%s' "$diff_out" | grep -q ' 0 CONTENT divergent, 0 shift-equivalent, 0 length-only'; then
    pass "fidelity: default CLUT diffs CLEAN against the verbatim helper (all classes zero)"
  else
    bad "fidelity: default CLUT diverges from the verbatim helper:"
    printf '%s\n' "$diff_out" | tail -5
  fi
fi

# ----------------------------------------------------------------- mutations
# quirk: controls.  Each flips ONE reproduced upstream behaviour; each must
# change the bytes.  If any of these matched, the byte-identical result
# above would be evidence of nothing, because the quirk it names would not
# be load-bearing.
#
# Since the fidelity default (2026-08-27) the quirks live only behind
# --reference-quirks, so BOTH sides of each differential run in that
# mode: the controls prove the reference path still reproduces the
# upstream behaviours the register reports.
refq=$work/reference-quirks.bin
if ! "$clut_selftest" --reference-quirks "$WBF" "$refq" > /dev/null 2>&1    || [ ! -s "$refq" ]; then
  bad "reference-quirks baseline compile failed"
fi
if cmp -s "$ours" "$refq"; then
  bad "fidelity default is byte-identical to --reference-quirks -- the 2026-08-27 fix is not load-bearing"
else
  pass "fidelity default differs from --reference-quirks (the fix is load-bearing)"
fi
for mutation in drop-suffix-off collision-first-wins axis-swap; do
  out=$work/mut-$mutation.bin
  if "$clut_selftest" --reference-quirks "--mutate=$mutation" "$WBF" "$out" > /dev/null 2>&1; then
    if [ ! -s "$out" ]; then
      bad "quirk: --mutate=$mutation produced no output (control is vacuous)"
    elif cmp -s "$refq" "$out"; then
      bad "quirk: --mutate=$mutation changed nothing -- that behaviour is not load-bearing, so the differential proves less than it claims"
    else
      pass "quirk: --mutate=$mutation changes the output"
    fi
  else
    # drop-suffix-off can legitimately blow past the 64-cell axis, since
    # the dropped entry is what kept max_len inside it.  A hard error is
    # still a difference from the reference, which is what the control is
    # for -- but ONLY if the tool understood the flag.  Accepting any
    # nonzero exit would let a renamed or deleted mutation keep printing
    # PASS while testing nothing (review, 2026-08-25), which is the same
    # vacuity these controls exist to prevent.
    if "$clut_selftest" --reference-quirks "--mutate=$mutation" "$WBF" "$out" 2>&1 \
         | grep -qiE 'unknown|unrecognis|unrecogniz|usage'; then
      bad "quirk: --mutate=$mutation is not a flag this binary knows -- the control is testing nothing"
    else
      pass "quirk: --mutate=$mutation is rejected outright (still a difference)"
    fi
  fi
done

# ----------------------------------------------------------------- reference
ref=""
ref_how=""
if [ -r "$CLUT_REF/wbf_to_custom.py" ] && [ -r "$CLUT_REF/read_file.py" ]; then
  # wbf_to_custom.py writes ./custom_wf.bin, so it has to run in the temp
  # dir -- never in the repo.
  mkdir -p "$work/pyref"
  if ( cd "$work/pyref" &&
       PYTHONPATH="$CLUT_REF" "$CLUT_PYTHON" \
         "$CLUT_REF/wbf_to_custom.py" "$WBF" ) > "$work/pyref.log" 2>&1 &&
     [ -s "$work/pyref/custom_wf.bin" ]; then
    ref=$work/pyref/custom_wf.bin
    ref_how="regenerated by $CLUT_REF/wbf_to_custom.py"
  else
    echo "NOTE: could not run $CLUT_REF/wbf_to_custom.py (needs numpy):" >&2
    tail -n 5 "$work/pyref.log" >&2
  fi
fi
if [ -z "$ref" ] && [ -n "$CLUT_REF_BIN" ] && [ -s "$CLUT_REF_BIN" ]; then
  ref=$CLUT_REF_BIN
  ref_how="pre-generated file $CLUT_REF_BIN"
fi

differential_ran=0
if [ -z "$ref" ]; then
  echo 'SKIP: the byte-identical differential -- no runnable reference.'
  echo "      Looked for $CLUT_REF/wbf_to_custom.py (with numpy on PATH)"
  echo '      and $CLUT_REF_BIN.  The structural and quirk: controls above'
  echo '      ran, but NOTHING above proves fidelity to wbf_to_custom.py.'
  echo '      Clone it per doc/reference-register.md and re-run:'
  echo '        make clut-check WBF=... CLUT_REF=.../pinenote-dist/bin'
else
  echo "reference: $ref_how"
  ref_size=$(wc -c < "$ref")
  if [ "$ref_size" -eq "$size" ]; then
    pass "reference and wbf-clut agree on size ($size bytes)"
  else
    bad "reference is $ref_size bytes, wbf-clut wrote $size"
  fi
  differential_ran=1
  if [ "$ref_size" -gt 0 ] && cmp -s "$ref" "$ours"; then
    pass "BYTE-IDENTICAL to wbf_to_custom.py"
  else
    bad "wbf-clut output differs from wbf_to_custom.py"
    cmp "$ref" "$ours" >&2 || true
  fi
fi

# The summary must not say the same thing whether or not the headline gate
# ran.  It used to print a bare "ALL TESTS PASSED" three lines under a block
# explaining that NOTHING had proved fidelity to wbf_to_custom.py.
if [ "$fail" -eq 0 ]; then
  if [ "$differential_ran" -eq 1 ]; then
    echo "ALL TESTS PASSED (including the byte-identical differential)"
  else
    echo "ALL TESTS PASSED -- STRUCTURAL ONLY."
    echo "  The byte-identical differential did NOT run, so nothing here"
    echo "  proves fidelity to wbf_to_custom.py.  Do not read this green as"
    echo "  'the C compiler matches the reference'."
  fi
else
  echo "TESTS FAILED" >&2
fi
exit "$fail"
