#!/usr/bin/env -S guile --no-auto-compile -s
!#
;; Failure-path tests of the actual Lua entrypoint.  The Lua adapter models
;; only external operations, fails on unknown ones, and never touches the host.
(use-modules (ice-9 popen) (ice-9 textual-ports) (srfi srfi-1) (srfi srfi-64))

(define helper "../../packages/update-path/wilkbook-generation.lua")
(define (run scenario)
  (let* ((port (open-pipe* OPEN_READ "luajit" "trial-fixture.lua" helper scenario))
         (output (get-string-all port))
         (status (close-pipe port)))
    (unless (zero? status) (error "fixture failed" scenario output))
    output))
(define (has text needle) (not (not (string-contains text needle))))
(define (before text first second)
  (let ((a (string-contains text first)) (b (string-contains text second)))
    (and a b (< a b))))

(test-begin "generation-trial")
(define runner (test-runner-current))
(for-each
 (lambda (scenario)
   (let ((out (run scenario)))
     (test-assert (string-append scenario ": reaches kexec") (has out "RESULT kexec"))
     (test-assert (string-append scenario ": root clean before handoff") (has out "root=ro"))
     (test-assert (string-append scenario ": data clean or absent")
       (has out (if (equal? scenario "no-data") "data=absent" "data=ro")))
     (test-assert (string-append scenario ": no refusal record") (not (has out "RECORD ")))
     (when (member scenario '("absent" "stopped" "inert"))
       (test-assert (string-append scenario ": optional authority untouched")
         (not (has out "herd stop pinenote-book-state-device"))))
     (when (equal? scenario "already-ro")
       (test-assert "pre-existing ro mounts untouched" (not (has out "CMD mount "))))
     (when (equal? scenario "no-data")
       (test-assert "placeholder /data never remounted" (not (has out "remount,ro /data"))))))
 '("success" "absent" "stopped" "inert" "reader-stopped" "no-data" "already-ro" "wifi-off"))
(let ((out (run "success")))
  (for-each
   (lambda (pair)
     (test-assert (string-append "order: " (car pair) " before " (cadr pair))
       (apply before out pair)))
   '(("herd stop reader-session" "herd stop pinenote-book-state-device")
     ("herd stop pinenote-book-state-device" "pinenote-wifi-control off")
     ("pinenote-wifi-control off" "sbin/kexec -l")
     ("sbin/kexec -l" "CMD mount -o remount,ro /")
     ("CMD mount -o remount,ro /\n" "CMD mount -o remount,ro /data")
     ("CMD mount -o remount,ro /data" "WRITE /dev/watchdog0 1")
     ("WRITE /dev/watchdog0 1" "sbin/kexec -e"))))
(for-each
 (lambda (entry)
   (let* ((scenario (car entry)) (reason (cadr entry)) (out (run scenario)))
     (test-assert (string-append scenario ": refuses") (has out "RESULT exit 1"))
     (test-assert (string-append scenario ": records reason")
       (and (has out "RECORD boot_id=fixture-boot|generation=2|result=refused|")
            (has out reason)))
     (test-assert (string-append scenario ": mounts restored") (has out "root=rw data=rw"))
     (test-assert (string-append scenario ": reader restored") (has out "STATE reader=running"))
     (test-assert (string-append scenario ": radio restored") (has out "wifi=true"))
     (unless (member scenario '("exec-fail" "restart-fail"))
       (test-assert (string-append scenario ": never executes kernel") (not (has out "sbin/kexec -e"))))
     (unless (member scenario '("cleanup-fail" "restart-fail"))
       (test-assert (string-append scenario ": authority running again") (has out "authority=running")))))
 '(("stop-fail" "could not stop pinenote-book-state-device")
   ("stop-fail-after" "lost reply after stopping")
   ("stop-still-running" "did not stop")
   ("reader-stop-fail" "could not stop reader-session")
   ("status-fail" "cannot determine pinenote-book-state-device state")
   ("cleanup-fail" "authority cleanup incomplete")
   ("quiesce-fail" "EBC did not go idle")
   ("load-fail" "kexec -l failed")
   ("busy-root" "/ did not remount read-only")
   ("busy-data" "/data did not remount read-only")
   ("lying-mount" "not the original read-only filesystem")
   ("mountinfo-fail" "cannot read mountinfo")
   ("bind-ro" "mount/superblock read-only flags disagree")
   ("udc-error" "configfs write failed")
   ("exec-fail" "kexec -e returned")
   ("restart-fail" "restoration incomplete: pinenote-book-state-device")))
(let ((out (run "exec-fail")))
  (for-each
   (lambda (pair) (test-assert (string-append "recovery order: " (car pair)) (apply before out pair)))
   '(("WRITE /run/wilkbook-generation/last-trial" "WRITE /dev/watchdog0 V")
     ("WRITE /dev/watchdog0 V" "CMD mount -o remount,rw /data")
     ("CMD mount -o remount,rw /data" "CMD mount -o remount,rw / ")
     ("CMD mount -o remount,rw / " "herd start pinenote-book-state-device")
     ("herd start pinenote-book-state-device" "herd start reader-session"))))
(let ((out (run "restore-mount-fail")))
  (test-assert "failed rw restore is recorded" (has out "restoration incomplete: /data read-write"))
  (test-assert "failed rw restore does not start writers" (not (has out "herd start ")))
  (test-assert "failed rw restore still restores radio" (has out "wifi=true"))
  (test-assert "failed rw restore never claims success" (not (has out "teardown undone"))))
(let ((out (run "stop-in-progress")))
  (test-assert "stop timeout refuses" (has out "RESULT exit 1"))
  (test-assert "stop timeout retains incomplete restoration" (has out "restoration incomplete: pinenote-book-state-device"))
  (test-assert "stop timeout never races ongoing cleanup with start"
    (not (has out "herd start pinenote-book-state-device")))
  (test-assert "stop timeout restores reader" (has out "STATE reader=running"))
  (test-assert "stop timeout never starts handoff" (not (has out "sbin/kexec -l"))))
(for-each
 (lambda (initial)
   (let ((out (run (string-append initial ":exec-fail"))))
     (test-assert (string-append initial ": failed exec refuses") (has out "RESULT exit 1"))
     (test-assert (string-append initial ": records refusal") (has out "result=refused"))
     (cond
      ((member initial '("absent" "stopped" "inert"))
       (test-assert (string-append initial ": never starts authority on refusal")
         (not (has out "herd start pinenote-book-state-device"))))
      ((equal? initial "reader-stopped")
       (test-assert "refusal preserves stopped reader" (has out "STATE reader=stopped"))
       (test-assert "refusal does not start stopped reader" (not (has out "herd start reader-session"))))
      ((equal? initial "no-data")
       (test-assert "refusal leaves absent /data alone" (has out "data=absent"))
       (test-assert "refusal does not remount absent data" (not (has out "remount,rw /data"))))
      ((equal? initial "already-ro")
       (test-assert "refusal preserves original ro mounts" (has out "root=ro data=ro"))
       (test-assert "refusal never makes original ro mounts writable" (not (has out "remount,rw"))))
      ((equal? initial "wifi-off")
       (test-assert "refusal preserves radio off" (has out "wifi=false"))
       (test-assert "refusal never powers prior off radio" (not (has out "pinenote-wifi-control on")))))))
 '("absent" "stopped" "inert" "reader-stopped" "no-data" "already-ro" "wifi-off"))
(for-each
 (lambda (scenario)
   (let ((out (run scenario)))
     (test-assert (string-append scenario ": refuses uncertain filesystem") (has out "RESULT exit 1"))
     (test-assert (string-append scenario ": never arms watchdog or executes kernel")
       (and (not (has out "WRITE /dev/watchdog0 1")) (not (has out "sbin/kexec -e"))))
     (test-assert (string-append scenario ": never remounts replacement or missing /data")
       (not (has out "remount,ro /data")))
     (test-assert (string-append scenario ": never restarts writers onto unverified mounts")
       (not (has out "herd start ")))
     (test-assert (string-append scenario ": reports incomplete restoration")
       (has out "restoration incomplete:"))
     (test-assert (string-append scenario ": never claims restored state")
       (not (has out "teardown undone")))))
 '("data-replaced" "no-data:data-appeared" "data-disappeared" "late-mountinfo-fail"
   "root-replaced" "root-disappeared"))
(test-end "generation-trial")
(exit (zero? (test-runner-fail-count runner)))
