;;; Independent census of an existing system profile against a generated shelf.
;;; No Guix evaluation/build and no import of the converter's discovery code.
(use-modules (ice-9 ftw) (ice-9 match) (ice-9 popen) (ice-9 rdelim)
             (ice-9 regex) (ice-9 textual-ports) (srfi srfi-1)
             (srfi srfi-13) (sxml simple) ((sxml xpath) #:select (sxpath)))

(define (capture . args)
  (let* ((port (apply open-pipe* OPEN_READ args))
         (text (get-string-all port)) (status (close-pipe port)))
    (unless (zero? status) (error "command failed" args status))
    text))
(define (lines path)
  (call-with-input-file path
    (lambda (p)
      (let loop ((out '()))
        (let ((line (read-line p)))
          (if (eof-object? line) (reverse out) (loop (cons line out))))))))
(define (entries path)
  (if (file-exists? path)
      (scandir path (lambda (s) (not (member s '("." ".."))))) '()))
(define (files path)
  (append-map (lambda (name)
                (let ((p (string-append path "/" name)))
                  (if (eq? 'directory (stat:type (stat p)))
                      (files p) (list p))))
              (entries path)))
(define (unsuffix name)
  (let ((suffix (find (lambda (s) (string-suffix? s name))
                      '(".gz" ".zst" ".bz2" ".xz" ".lz" ".Z"))))
    (if suffix (substring name 0 (- (string-length name) (string-length suffix))) name)))
(define (ncx book)
  (call-with-input-string (capture "unzip" "-p" book "OEBPS/toc.ncx")
    (lambda (p) (xml->sxml p #:namespaces '((n . "http://www.daisy.org/z3986/2005/ncx/"))))))
(define (labels book)
  ((sxpath '(// n:navLabel n:text *text*)) (ncx book)))
(define (man-key label)
  (let ((m (string-match "^(.+)\\(([0-9][A-Za-z]*)\\)$" label)))
    (and m (string-append (match:substring m 1) "." (match:substring m 2)))))
(define (text-content node)
  (cond ((string? node) node)
        ((and (pair? node) (not (eq? (car node) '@)))
         (string-concatenate (map text-content (cdr node))))
        (else "")))
(define (man-index-keys book)
  (let ((members (filter (lambda (s) (string-match "^OEBPS/section-[^.]+\\.xhtml$" s))
                         (string-split (capture "unzip" "-Z1" book) #\newline))))
    (append-map
     (lambda (member)
       (let ((xml (call-with-input-string (capture "unzip" "-p" book member)
                    (lambda (p) (xml->sxml p #:namespaces '((h . "http://www.w3.org/1999/xhtml")))))))
         (map (lambda (li)
                (let* ((text (text-content li))
                       (m (string-match "^([^()]+)\\(([0-9][A-Za-z]*)\\)" text)))
                  (unless m (error "unrecognized man index item" text))
                  (string-append (match:substring m 1) "." (match:substring m 2))))
              ((sxpath '(// h:li)) xml)))) members)))
(define (info-key path)
  (let ((m (string-match "^(.+)\\.info(-[0-9]+)?$" (unsuffix (basename path)))))
    (and m (match:substring m 1))))
(define (sha path)
  (substring (capture "sha256sum" path) 0 64))
(define (doc-text path)
  ;; This census reads only identified installed inputs. The converter's
  ;; magic-byte handling (including mislabeled files) has its own unit gate.
  (let ((tool (cond ((string-suffix? ".gz" path) "gzip")
                    ((string-suffix? ".zst" path) "zstd")
                    ((string-suffix? ".xz" path) "xz")
                    ((string-suffix? ".bz2" path) "bzip2")
                    ((string-suffix? ".lz" path) "lzip")
                    (else #f))))
    (if tool (capture tool "-dc" path)
        (call-with-input-file path get-string-all))))
(define (node-count paths)
  (fold (lambda (p n)
          (+ n (count (lambda (chunk)
                        (string-match "^File:[^\n]*, *Node:" (string-trim-both chunk)))
                      (string-split (doc-text p) #\x1f)))) 0 paths))

(match (cdr (command-line))
  ((profile shelf exceptions)
   (let* ((profile (canonicalize-path profile))
          (shelf (canonicalize-path shelf))
          (rows (map (lambda (line) (string-split line #\tab))
                     (lines (string-append shelf "/MANIFEST"))))
          (allowed (filter (lambda (s) (and (not (string-null? s))
                                          (not (string-prefix? "#" s))))
                           (lines exceptions)))
          (omitted '()) (included '()) (translated 0) (auxiliary 0)
          (man-root (string-append profile "/share/man/"))
          (info-root (string-append profile "/share/info/"))
          (info-files (files (string-drop-right info-root 1)))
          (man-row (find (lambda (r) (equal? (take r 2) '("man" "all-sections"))) rows))
          (man-book (string-append shelf "/" (list-ref man-row 2)))
          (book-keys (man-index-keys man-book))
          (profile-man '()) (profile-info '()))
     (format #t "profile\t~a~%shelf\t~a~%manifest-sha256\t~a~%"
             profile shelf (sha (string-append shelf "/MANIFEST")))
     (for-each
      (lambda (p)
        (let* ((relative (substring p (string-length man-root)))
               (parts (string-split relative #\/)))
          (if (and (= 2 (length parts)) (string-match "^man[0-9][A-Za-z]*$" (car parts)))
              (set! profile-man (cons (unsuffix (basename p)) profile-man))
              (set! translated (+ translated 1)))))
      (files (string-drop-right man-root 1)))
     (for-each
      (lambda (p)
        (let ((key (info-key p)))
          (if (and key (not (string=? key "dir")))
              (set! profile-info (cons key profile-info))
              (set! auxiliary (+ auxiliary 1)))))
      info-files)
     (set! profile-man (sort (delete-duplicates profile-man) string<?))
     (set! profile-info (sort (delete-duplicates profile-info) string<?))
     (unless (= (length book-keys) (string->number (list-ref man-row 3)))
       (error "man manifest count differs from section indexes" (length book-keys) man-row))
     (unless (= (length book-keys) (length (delete-duplicates book-keys)))
       (error "duplicate man index entry"))
     (format #t "man-layout\tindex-entries=~a\tpage-chapters=~a\taliases=~a~%"
             (length book-keys) (length (filter-map man-key (labels man-book)))
             (- (length book-keys) (length (filter-map man-key (labels man-book)))))
     (for-each
      (lambda (r)
        (match r
          ((kind key filename count)
           (when (or (string-contains filename "/") (not (string-suffix? ".epub" filename)))
             (error "invalid manifest filename" filename))
           (let ((book (string-append shelf "/" filename)))
             (unless (file-exists? book) (error "missing manifest book" filename))
             (when (string=? kind "info")
               (unless (= (length (labels book)) (string->number count))
                 (error "info manifest count differs from NCX" filename))
               (unless (= (node-count (filter (lambda (p) (equal? key (info-key p))) info-files))
                          (string->number count))
                 (error "info source node count differs from manifest" key)))
             (format #t "book\t~a\t~a\t~a\t~a~%" kind key count (sha book))))
          (_ (error "invalid manifest row" r)))) rows)
     (define (compare kind sources outputs)
       (for-each (lambda (key)
                   (let ((id (string-append kind ":" key)))
                     (if (member key outputs)
                         (set! included (cons id included))
                         (set! omitted (cons id omitted))))) sources)
       (for-each (lambda (key)
                   (unless (member key sources) (error "shelf entry absent from profile" kind key))) outputs))
     (compare "man" profile-man book-keys)
     (compare "info" profile-info
              (map cadr (filter (lambda (r) (string=? (car r) "info")) rows)))
     (for-each (lambda (id) (format #t "omitted\t~a~%" id)) (sort omitted string<?))
     (format #t "summary\tman=~a\tinfo=~a\tincluded=~a\tomitted=~a\tlocalized-man=~a\tinfo-auxiliary=~a~%"
             (length profile-man) (length profile-info) (length included) (length omitted) translated auxiliary)
     ;; Exact set, not merely an allowlist: a fixed omission must be removed
     ;; from the reviewed exceptions rather than silently remaining waived.
     (unless (equal? (sort omitted string<?) (sort allowed string<?))
       (error "unreviewed or stale omissions" (lset-difference equal? omitted allowed)
              (lset-difference equal? allowed omitted)))
     (format #t "PASS: profile corpus reconciled with shelf manifest, indexes, NCX and Info node counts~%")))
  (_ (error "usage: corpus-check.scm PROFILE SHELF EXCEPTIONS")))
