#!/usr/bin/env python3
"""Emit the reviewed Guix origin table from release-vendor-manifest.json."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import vendor_manifest


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def origin_lines(item: dict) -> list[str]:
    urls = item["urls"]
    uri = quote(urls[0]) if len(urls) == 1 else "(list " + " ".join(map(quote, urls)) + ")"
    return [
        f"   (list {quote(item['id'])}",
        "     (origin",
        "        (method url-fetch)",
        f"        (uri {uri})",
        f"        (file-name {quote(item['file_name'])})",
        f"        (sha256 (base32 {quote(item['guix_base32'])}))))",
    ]


def emit(manifest: dict) -> str:
    vendor_manifest.validate_manifest(manifest)
    items = [manifest["bootstrap"]["bazel"]] + manifest["archives"] + manifest["go_modules"]
    lines = [
        ";; Generated by pinenote/tools/gvisor-package/emit_guix_inputs.py.",
        ";; Do not add runtime policy here; these are reusable fixed source inputs.",
        "(define-module (pinenote packages gvisor-dependencies)",
        "  #:use-module (guix download)",
        "  #:use-module (guix git-download)",
        "  #:use-module (guix packages)",
        "  #:export (gvisor-bcr-snapshot-origin",
        "            %gvisor-release-fixed-inputs))",
        "",
        "(define-public gvisor-bcr-snapshot-origin",
        "  (origin",
        "    (method git-fetch)",
        "    (uri (git-reference",
        '          (url "https://github.com/bazelbuild/bazel-central-registry.git")',
        f'          (commit "{manifest["bcr_snapshot"]["commit"]}")))',
        '    (file-name (git-file-name "bazel-central-registry"',
        f'                              "{manifest["bcr_snapshot"]["commit"]}"))',
        f'    (sha256 (base32 "{manifest["bcr_snapshot"]["guix_recursive_sha256"]}"))))',
        "",
        "(define-public %gvisor-release-fixed-inputs",
        "  (list",
        '   (list "bcr-snapshot" gvisor-bcr-snapshot-origin)',
    ]
    for item in items:
        lines.extend(origin_lines(item))
    lines[-1] += "))"
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manifest", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        manifest = vendor_manifest.read_json(args.manifest)
        text = emit(manifest)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text)
    except (OSError, vendor_manifest.ManifestError) as error:
        print(f"emit Guix inputs: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
