;; Generated by pinenote/tools/gvisor-package/emit_guix_inputs.py.
;; Do not add runtime policy here; these are reusable fixed source inputs.
(define-module (pinenote packages gvisor-dependencies)
  #:use-module (guix download)
  #:use-module (guix git-download)
  #:use-module (guix packages)
  #:export (gvisor-bcr-snapshot-origin
            %gvisor-release-fixed-inputs))

(define-public gvisor-bcr-snapshot-origin
  (origin
    (method git-fetch)
    (uri (git-reference
          (url "https://github.com/bazelbuild/bazel-central-registry.git")
          (commit "a5e087e21fcac28ff105ffc5eaeca966e61057af")))
    (file-name (git-file-name "bazel-central-registry"
                              "a5e087e21fcac28ff105ffc5eaeca966e61057af"))
    (sha256 (base32 "057akiiiqiigylnrsi7bqyrdkfhq1h1xpsblrpyni6p614wz8paz"))))

(define-public %gvisor-release-fixed-inputs
  (list
   (list "bcr-snapshot" gvisor-bcr-snapshot-origin)
   (list "bazel-bootstrap-8.3.1-linux-x86_64"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/bazel/releases/download/8.3.1/bazel-8.3.1-linux-x86_64")
        (file-name "bazel-8.3.1-linux-x86_64")
        (sha256 (base32 "0k3067d06b8160day48afskr42c41bz0qgb3pk9mjpr4hj57w90p"))))
   (list "archive-abseil-cpp-20250814-1"
     (origin
        (method url-fetch)
        (uri "https://github.com/abseil/abseil-cpp/releases/download/20250814.1/abseil-cpp-20250814.1.tar.gz")
        (file-name "1692f77d1739bacf-abseil-cpp-20250814.1.tar.gz")
        (sha256 (base32 "18c5czwa81andkfd4874nyx0kkw3hnvqhw9kjhzwzfir2xyzg4hn"))))
   (list "archive-apple-support-1-17-1"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/apple_support/releases/download/1.17.1/apple_support.1.17.1.tar.gz")
        (file-name "b53f6491e742549f-apple_support.1.17.1.tar.gz")
        (sha256 (base32 "02w97h8l5chn9bqw8zcqssrg7lbmrkzxsa36hq9rym22wy8n8gxm"))))
   (list "archive-bazel-features-1-33-0"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazel-contrib/bazel_features/releases/download/v1.33.0/bazel_features-v1.33.0.tar.gz")
        (file-name "c41853e3b636c533-bazel_features-v1.33.0.tar.gz")
        (sha256 (base32 "1aac6jaf0a86zz5m5kiv1bdwjv2f0rc4dazmdfw37i9nnvim6664"))))
   (list "archive-bazel-skylib-1-8-2"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/bazel-skylib/releases/download/1.8.2/bazel-skylib-1.8.2.tar.gz")
        (file-name "6e78f0e57de26801-bazel-skylib-1.8.2.tar.gz")
        (sha256 (base32 "0il4mkp3f2dv5flmfqj17s3kd2yw9157ryk4ypv02s72gpjz0y3f"))))
   (list "archive-cel-spec-0-25-1"
     (origin
        (method url-fetch)
        (uri "https://github.com/google/cel-spec/archive/refs/tags/v0.25.1.tar.gz")
        (file-name "13583c5a31286164-v0.25.1.tar.gz")
        (sha256 (base32 "1ljanzz3hidykj76nsrr8fdkqsk74abp0nw496268q9865d3qn0k"))))
   (list "archive-gazelle-0-47-0"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazel-contrib/bazel-gazelle/releases/download/v0.47.0/bazel-gazelle-v0.47.0.tar.gz")
        (file-name "675114d8b433d0a9-bazel-gazelle-v0.47.0.tar.gz")
        (sha256 (base32 "0iilx5c4s83g3rwlnrhm648w9swnpqrih5w19psskl1knkc18lb7"))))
   (list "archive-go-sdk-1-26-3-linux-amd64"
     (origin
        (method url-fetch)
        (uri "https://dl.google.com/go/go1.26.3.linux-amd64.tar.gz")
        (file-name "2b2cfc7148493da5-go1.26.3.linux-amd64.tar.gz")
        (sha256 (base32 "0mmm5sb69zwsqy19qy1yz7aq3wrs6przpgw177ksaga991qzqb1b"))))
   (list "archive-google-coral-crosstool-8e885509123395299bed6a5f9529fdc1b9751599"
     (origin
        (method url-fetch)
        (uri "https://github.com/google-coral/crosstool/archive/8e885509123395299bed6a5f9529fdc1b9751599.tar.gz")
        (file-name "f86d488ca353c5ee-8e885509123395299bed6a5f9529fdc1b9751599.tar.gz")
        (sha256 (base32 "00dswd691yrglkiwcs8xpgrfjwyvi90gwybm32cyxiaklf64hvgq"))))
   (list "archive-grpc-override-1-75-0"
     (origin
        (method url-fetch)
        (uri "https://github.com/grpc/grpc/archive/refs/tags/v1.75.0.tar.gz")
        (file-name "31d6c01c3bfa0a35-v1.75.0.tar.gz")
        (sha256 (base32 "1ydv2ff16zg5fm40pcvbsw8fn0vp91g72r96af23a2ps7cfc1mii"))))
   (list "archive-package-metadata-0-0-5"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazel-contrib/supply-chain/releases/download/v0.0.5/supply-chain-v0.0.5.tar.gz")
        (file-name "49ed11e5d6b752c5-supply-chain-v0.0.5.tar.gz")
        (sha256 (base32 "01pcvfvsq3d803apn788gcs4z5rn4w5v3jrrlmgwalmpsvji3va9"))))
   (list "archive-platforms-1-0-0"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/platforms/releases/download/1.0.0/platforms-1.0.0.tar.gz")
        (file-name "3384eb1c30762704-platforms-1.0.0.tar.gz")
        (sha256 (base32 "1a0rq0l10i187qp8r2pwr234058lw4204i4fwgxh89vn60ffp11k"))))
   (list "archive-protobuf-33-4"
     (origin
        (method url-fetch)
        (uri "https://github.com/protocolbuffers/protobuf/releases/download/v33.4/protobuf-33.4.bazel.tar.gz")
        (file-name "687e98a471973b5c-protobuf-33.4.bazel.tar.gz")
        (sha256 (base32 "0ass6hlhya8bw1jxnjgn6gg0lb5qp100qx8isxgmqfwpf6j9hzk8"))))
   (list "archive-protoc-gen-validate-1-3-0"
     (origin
        (method url-fetch)
        (uri "https://github.com/bufbuild/protoc-gen-validate/archive/refs/tags/v1.3.0.tar.gz")
        (file-name "26dc6db523ee943a-v1.3.0.tar.gz")
        (sha256 (base32 "0sz21y7rhicphgfg2m2nfd371gidi9jr5hnz3zskm57f4fsnvp16"))))
   (list "archive-rules-cc-0-2-16"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/rules_cc/releases/download/0.2.16/rules_cc-0.2.16.tar.gz")
        (file-name "458b658277ba51b4-rules_cc-0.2.16.tar.gz")
        (sha256 (base32 "00ccz9vq4c7l6wpff3fkyynxripizl7058m71rrv8ldsfy16b2s5"))))
   (list "archive-rules-foreign-cc-0-10-1"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/rules_foreign_cc/releases/download/0.10.1/rules_foreign_cc-0.10.1.tar.gz")
        (file-name "476303bd0f1b04cc-rules_foreign_cc-0.10.1.tar.gz")
        (sha256 (base32 "0sjs8a1h78kzjz8kzrci60nzhvjzi9qg2n623wqwq10v1yyh6qs7"))))
   (list "archive-rules-go-override-0-57-0"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazel-contrib/rules_go/releases/download/v0.57.0/rules_go-v0.57.0.zip")
        (file-name "a729c8ed2447c90f-rules_go-v0.57.0.zip")
        (sha256 (base32 "15ixv7lhqr9d65zn6hgch1szpb50kh3qjxh783hhzja74knwhad7"))))
   (list "archive-rules-java-8-16-1"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/rules_java/releases/download/8.16.1/rules_java-8.16.1.tar.gz")
        (file-name "1b30698d89dccd9d-rules_java-8.16.1.tar.gz")
        (sha256 (base32 "0phv1as6bqrl0c2vp3ciy76nkrn6wplxfjhs3g09vkfwi66njc0v"))))
   (list "archive-rules-kotlin-1-9-6"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/rules_kotlin/releases/download/v1.9.6/rules_kotlin-v1.9.6.tar.gz")
        (file-name "3b772976fec7bdcd-rules_kotlin-v1.9.6.tar.gz")
        (sha256 (base32 "0hxga0767b4ss2z7a8gb8z02952qfsqkk7abv2hwvgf7zrv2jxrv"))))
   (list "archive-rules-license-1-0-0"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/rules_license/releases/download/1.0.0/rules_license-1.0.0.tar.gz")
        (file-name "26d4021f6898e23b-rules_license-1.0.0.tar.gz")
        (sha256 (base32 "0f3v2knwr1zgwjnn9icac6sw56nlklw7hc4mxy13pqlqd0gh5m16"))))
   (list "archive-rules-perl-0-2-4"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazel-contrib/rules_perl/archive/refs/tags/0.2.4.tar.gz")
        (file-name "bc7550f3881f6325-0.2.4.tar.gz")
        (sha256 (base32 "1y5z7irhcyr3x7kag6kvipj0lpn3hg7cgpn6cmd2aqqzi3rm0xdw"))))
   (list "archive-rules-pkg-1-0-1"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/rules_pkg/releases/download/1.0.1/rules_pkg-1.0.1.tar.gz")
        (file-name "d20c951960ed77cb-rules_pkg-1.0.1.tar.gz")
        (sha256 (base32 "1vwz59vmfvbkij0w8c0xmpar9r1lhm45jahw6ixwnxzdc0cra36j"))))
   (list "archive-rules-proto-7-1-0"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/rules_proto/releases/download/7.1.0/rules_proto-7.1.0.tar.gz")
        (file-name "14a225870ab4e918-rules_proto-7.1.0.tar.gz")
        (sha256 (base32 "1x11mvhdcqiv6mfxc429vk0py9r843pnkz9ccmliisdl1a3jb8hl"))))
   (list "archive-rules-python-1-7-0"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazel-contrib/rules_python/releases/download/1.7.0/rules_python-1.7.0.tar.gz")
        (file-name "f609f341d6e9090b-rules_python-1.7.0.tar.gz")
        (sha256 (base32 "1nj75k7726bnkj24yhsnb9xgs6d80m6k4i9z3fc0n2g9sr0z62gn"))))
   (list "archive-rules-shell-0-3-0"
     (origin
        (method url-fetch)
        (uri "https://github.com/bazelbuild/rules_shell/releases/download/v0.3.0/rules_shell-v0.3.0.tar.gz")
        (file-name "d8cd4a3a91fc1dc6-rules_shell-v0.3.0.tar.gz")
        (sha256 (base32 "0lqcd91snq4v1bsy6dv433vhkwfy15gnasvx9j6wc7gwj4x4mkfq"))))
   (list "archive-zlib-1-3-1"
     (origin
        (method url-fetch)
        (uri "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz")
        (file-name "9a93b2b7dfdac77c-zlib-1.3.1.tar.gz")
        (sha256 (base32 "08yzf8xz0q7vxs8mnn74xmpxsrs6wy0aan55lpmpriysvyvv54ws"))))
   (list "go-module-co-honnef-go-tools"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/honnef.co/go/tools/@v/v0.5.1.zip")
        (file-name "d728ff392fc5b6f6-v0.5.1.zip")
        (sha256 (base32 "04gsvz5nbn973h9bpsxl0qp6ypxqlp8fjdhcldvgddn55wwzya6p"))))
   (list "go-module-com-github-burntsushi-toml"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/!burnt!sushi/toml/@v/v1.4.1-0.20240526193622-a339e1f7089c.zip")
        (file-name "f15f0ca7a3c5a427-v1.4.1-0.20240526193622-a339e1f7089c.zip")
        (sha256 (base32 "02i30rl6fpzchnvg6jskhjh3bmz9g3qkc0jn7mfjg965lfkhqpzi"))))
   (list "go-module-com-github-cenkalti-backoff"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/cenkalti/backoff/@v/v2.2.1+incompatible.zip")
        (file-name "f8196815a1b4d25e-v2.2.1+incompatible.zip")
        (sha256 (base32 "0fyljfb1dzaj0zrwqa7ibymch7w0ci99s0jqh5dmxlmll4anh6gq"))))
   (list "go-module-com-github-cespare-xxhash-v2"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/cespare/xxhash/v2/@v/v2.3.0.zip")
        (file-name "145a26cdc7c49db5-v2.3.0.zip")
        (sha256 (base32 "1lr16sn5z6czp6f3whk9npg7szzfi54pr03v05kbb7f4qz6jcnhl"))))
   (list "go-module-com-github-cilium-ebpf"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/cilium/ebpf/@v/v0.16.0.zip")
        (file-name "94f18289e55ece88-v0.16.0.zip")
        (sha256 (base32 "1kwmi4n9cmprbxmzsdrq86j0471h2x8vvwzpg5sqikjywn4q5wcl"))))
   (list "go-module-com-github-cncf-xds-go"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/cncf/xds/go/@v/v0.0.0-20251210132809-ee656c7534f5.zip")
        (file-name "cca4463a6b464413-v0.0.0-20251210132809-ee656c7534f5.zip")
        (sha256 (base32 "0701m3rwv1krpq2gr718x2bxz82mxl55if04q9b16i26dcx4d96c"))))
   (list "go-module-com-github-containerd-cgroups-v3"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/cgroups/v3/@v/v3.0.5.zip")
        (file-name "8ddceaca7d2b60ed-v3.0.5.zip")
        (sha256 (base32 "10xxq538s19vglf2zsv9lw4yz8r02ry0sqa36qaysq1bgp5fmp4d"))))
   (list "go-module-com-github-containerd-console"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/console/@v/v1.0.4.zip")
        (file-name "80c4b1f54a9d8278-v1.0.4.zip")
        (sha256 (base32 "1whcknk6w183nck2s3ifm1zb9albffrj6s90x41pi0lx9bsv3i40"))))
   (list "go-module-com-github-containerd-containerd-api"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/containerd/api/@v/v1.10.0.zip")
        (file-name "14852596630c8aa3-v1.10.0.zip")
        (sha256 (base32 "05fhcwxwflgfmln9gazvsrn4aj3j5jf63zd6xy9a72hccfb2b18l"))))
   (list "go-module-com-github-containerd-containerd-v2"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/containerd/v2/@v/v2.1.5.zip")
        (file-name "dffe08911fcd926e-v2.1.5.zip")
        (sha256 (base32 "1bhw9slgs89p0rlgwfqsvj3id9jxfw3b3n6wqx5nx4nd3y8hiznz"))))
   (list "go-module-com-github-containerd-continuity"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/continuity/@v/v0.4.5.zip")
        (file-name "dc5749a7ddf8e6a0-v0.4.5.zip")
        (sha256 (base32 "0jbxqy85zpykpq8ji7lx676v1n91cjxv4nbvrghs1rpqvnkljmyw"))))
   (list "go-module-com-github-containerd-errdefs"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/errdefs/@v/v1.0.0.zip")
        (file-name "b4ef42c38d00f2c8-v1.0.0.zip")
        (sha256 (base32 "0qlimk03v5lingbh556yfbxwhpbzkda4d5p6ycfciwh0ip1l5vxl"))))
   (list "go-module-com-github-containerd-errdefs-pkg"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/errdefs/pkg/@v/v0.3.0.zip")
        (file-name "593bf56f1991517e-v0.3.0.zip")
        (sha256 (base32 "0kxjmab5009gh5bdxcxz1xavhi6kqs7mv08h6m4pwlci35pzafsr"))))
   (list "go-module-com-github-containerd-fifo"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/fifo/@v/v1.1.0.zip")
        (file-name "b139b81b236b2961-v1.1.0.zip")
        (sha256 (base32 "1hnvvjzv8qk1w5ra8gif9ndg9fakjz90iagwvwz62abb4cdvhfdi"))))
   (list "go-module-com-github-containerd-go-runc"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/go-runc/@v/v1.1.0.zip")
        (file-name "2b096a08bc0a8c4f-v1.1.0.zip")
        (sha256 (base32 "1x1ymsd5q6c2mgfs9c4kx7zgpj4caan9qwspbg74z30aph46l29b"))))
   (list "go-module-com-github-containerd-log"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/log/@v/v0.1.0.zip")
        (file-name "2008faf206ec820e-v0.1.0.zip")
        (sha256 (base32 "1mspdvi91yi2y5zlmbdggls22v4k4jlsn2ylqdzhx0pc0vrgl210"))))
   (list "go-module-com-github-containerd-plugin"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/plugin/@v/v1.0.0.zip")
        (file-name "14f3b757a16b670a-v1.0.0.zip")
        (sha256 (base32 "0rd03ad6k0d8dad762i5yz8a2m00847cxwjy86vhlrvbl5bvgwql"))))
   (list "go-module-com-github-containerd-ttrpc"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/ttrpc/@v/v1.2.7.zip")
        (file-name "b5bf2d0282ccdeeb-v1.2.7.zip")
        (sha256 (base32 "1spwz3vfylhrp61byiaa6dhsc7z58vp3gxvdxvhfppnch812vgxm"))))
   (list "go-module-com-github-containerd-typeurl-v2"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/containerd/typeurl/v2/@v/v2.2.3.zip")
        (file-name "aabdf9f00f4381f4-v2.2.3.zip")
        (sha256 (base32 "129ilylhrb61s4iihw0zayq05mdf5xz8zbv6x6zg90a31zqgkgda"))))
   (list "go-module-com-github-coreos-go-systemd-v22"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/coreos/go-systemd/v22/@v/v22.6.0.zip")
        (file-name "7759d251cb9c2f02-v22.6.0.zip")
        (sha256 (base32 "0bxwp9xjd11lpyaf3qv192nirc9wcmss0pvvic6h4bwwrd8x4nbp"))))
   (list "go-module-com-github-creack-pty"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/creack/pty/@v/v1.1.24.zip")
        (file-name "754e25253e76a558-v1.1.24.zip")
        (sha256 (base32 "05c8zp4aivfim5l0jj9akx6zqs7y7bfklzfmh0xmi9bn7qjjakkm"))))
   (list "go-module-com-github-docker-go-units"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/docker/go-units/@v/v0.5.0.zip")
        (file-name "039d53ebe64af1ae-v0.5.0.zip")
        (sha256 (base32 "1xmgxsdm4mzkngjibbaq5h2s65qsc8nf8k791gxaxwaawvmm7783"))))
   (list "go-module-com-github-envoyproxy-go-control-plane-envoy"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/envoyproxy/go-control-plane/envoy/@v/v1.36.0.zip")
        (file-name "dc628978da600214-v1.36.0.zip")
        (sha256 (base32 "0nkb1xgrhj1m8hfny8a07ay2f3mmq91f1gx5ccz180k0v9w8jqnw"))))
   (list "go-module-com-github-felixge-httpsnoop"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/felixge/httpsnoop/@v/v1.0.4.zip")
        (file-name "75aa471311265e98-v1.0.4.zip")
        (sha256 (base32 "1574j9kj41qz89m7hqijlg0x03k5nh038lhfvxh9hpi6249lgakm"))))
   (list "go-module-com-github-go-jose-go-jose-v4"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/go-jose/go-jose/v4/@v/v4.1.4.zip")
        (file-name "06a37b6668012a2d-v4.1.4.zip")
        (sha256 (base32 "09xh2y5ff1p4ymrwzlrmif0dr1skw5m1zxx5178jsah1d1k7p8q6"))))
   (list "go-module-com-github-go-logr-logr"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/go-logr/logr/@v/v1.4.3.zip")
        (file-name "523d7a3587fe73f6-v1.4.3.zip")
        (sha256 (base32 "0w5df03yc1xkaj0jfijd23l8vwypywkwd2qwyhggcwzyhwsplgaj"))))
   (list "go-module-com-github-go-logr-stdr"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/go-logr/stdr/@v/v1.2.2.zip")
        (file-name "9dd6893bf7001984-v1.2.2.zip")
        (sha256 (base32 "1vvzizyy2xh459wvaz5kfdnbrvy1kfs415k9ms2q8680ywxqkmlx"))))
   (list "go-module-com-github-godbus-dbus-v5"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/godbus/dbus/v5/@v/v5.1.0.zip")
        (file-name "03dfa8e71089a6f4-v5.1.0.zip")
        (sha256 (base32 "1n9ag273am72zr81p21jhl12vn1nl39w858d65vz99l923ksipq3"))))
   (list "go-module-com-github-gofrs-flock"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/gofrs/flock/@v/v0.8.0.zip")
        (file-name "816d8ac38372193f-v0.8.0.zip")
        (sha256 (base32 "196bh4036cp6gdpa60y0srip62nz8ijncrhsx46ky6bjhg1qlvc1"))))
   (list "go-module-com-github-gogo-protobuf"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/gogo/protobuf/@v/v1.3.2.zip")
        (file-name "dd2b73f163c81839-v1.3.2.zip")
        (sha256 (base32 "1xsg238246rf86h43lr3akcxsjl4ixn1jq33c90kj668cgqp6ayx"))))
   (list "go-module-com-github-golang-protobuf"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.5.4.zip")
        (file-name "9a2f43d3eac8ceda-v1.5.4.zip")
        (sha256 (base32 "02qrh90n2cz2l296cd4hrqsp5f2lj8i4zsxvdr8dmkn8xb9l6bws"))))
   (list "go-module-com-github-google-btree"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/google/btree/@v/v1.1.2.zip")
        (file-name "faee8550c5fffb4a-v1.1.2.zip")
        (sha256 (base32 "07a81b4h637d9sxjdlpsz4k8fa8krfncrrfxvbhlmyzzqm88bvps"))))
   (list "go-module-com-github-google-go-cmp"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/google/go-cmp/@v/v0.7.0.zip")
        (file-name "64a9ce046f2c320e-v0.7.0.zip")
        (sha256 (base32 "0fgmnffr2c3ngzr7pdh9n3q1i2jzl7sd387vhcvhwcicdw2cxab4"))))
   (list "go-module-com-github-google-s2a-go"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/google/s2a-go/@v/v0.1.9.zip")
        (file-name "bf8f4b159d3fc201-v0.1.9.zip")
        (sha256 (base32 "01vzzgjwrb607vbzx3xpck3mhpzhwha2bv92g13h3hizklalp3xz"))))
   (list "go-module-com-github-google-subcommands"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/google/subcommands/@v/v1.0.2-0.20190508160503-636abe8753b8.zip")
        (file-name "579d425640f38e87-v1.0.2-0.20190508160503-636abe8753b8.zip")
        (sha256 (base32 "1p2zhwq7jkkzcwbqmprlmx8xar82kfwxjdjq2mg8g3pk81b457ap"))))
   (list "go-module-com-github-google-uuid"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/google/uuid/@v/v1.6.0.zip")
        (file-name "d0f02f377217f427-v1.6.0.zip")
        (sha256 (base32 "1vd6725h6mpakfx39k6x1lagbnqy8h34ws2rw812gx0pf8vjzw6h"))))
   (list "go-module-com-github-googleapis-enterprise-certificate-proxy"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/googleapis/enterprise-certificate-proxy/@v/v0.3.14.zip")
        (file-name "ab19ba449c062755-v0.3.14.zip")
        (sha256 (base32 "1rimy4j7dzx3n3hxl5prd1dkr3m4jrjsmgpr5c3ma9q6ki2bl6db"))))
   (list "go-module-com-github-googleapis-gax-go-v2"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/googleapis/gax-go/v2/@v/v2.21.0.zip")
        (file-name "e4ff14be567241c5-v2.21.0.zip")
        (sha256 (base32 "1578ny5rs2dshx0cg5xyplw8gcqwdw0i4rzpdlycahbjasz19zz4"))))
   (list "go-module-com-github-googlecloudplatform-opentelemetry-operations-go-detectors-gcp"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/!google!cloud!platform/opentelemetry-operations-go/detectors/gcp/@v/v1.31.0.zip")
        (file-name "60558bb0633e963a-v1.31.0.zip")
        (sha256 (base32 "1hk3hkpd5sw3zrzs1dd7gy0sghkv5qb9515g5923m5iycfq8nmb0"))))
   (list "go-module-com-github-googlecloudplatform-opentelemetry-operations-go-exporter-metric"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/metric/@v/v0.55.0.zip")
        (file-name "f76ca1fa72665494-v0.55.0.zip")
        (sha256 (base32 "1scfm3412bvdyr4iap0chc3hndrc63g5n0y11a598m36fbxa2v7p"))))
   (list "go-module-com-github-googlecloudplatform-opentelemetry-operations-go-internal-resourcemapping"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/!google!cloud!platform/opentelemetry-operations-go/internal/resourcemapping/@v/v0.55.0.zip")
        (file-name "d7f5f7dd65f51194-v0.55.0.zip")
        (sha256 (base32 "0pky67sqdxwlj4wrcs7r80ssnb7f05vw6xyxn0fr84gmcpfzgxfp"))))
   (list "go-module-com-github-mdlayher-socket"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/mdlayher/socket/@v/v0.5.1.zip")
        (file-name "f0f07bdd9811f857-v0.5.1.zip")
        (sha256 (base32 "18p24zag3rri984xcm5jvczgnp6q0q7mxkv4g0f5gy0ik3fppw7h"))))
   (list "go-module-com-github-mdlayher-vsock"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/mdlayher/vsock/@v/v1.2.1.zip")
        (file-name "cd25f9f33aa4fb94-v1.2.1.zip")
        (sha256 (base32 "1lf0bg2226xa5p52dj2ch8s1yklrsvpaw71m09ar9yx47brzj9fd"))))
   (list "go-module-com-github-moby-sys-capability"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/moby/sys/capability/@v/v0.4.0.zip")
        (file-name "3502bba106a402fd-v0.4.0.zip")
        (sha256 (base32 "0k5l4a7fqf2qf89q6kk71bbs87blrasqwkhx1m2gs0m40shvn0im"))))
   (list "go-module-com-github-moby-sys-mountinfo"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/moby/sys/mountinfo/@v/v0.7.2.zip")
        (file-name "94f79687bc3b72ca-v0.7.2.zip")
        (sha256 (base32 "1lxm67ib5hn7x2cl9nsby07grzjl2j2xmbqgqr6clwivpj3rdxwl"))))
   (list "go-module-com-github-moby-sys-userns"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/moby/sys/userns/@v/v0.1.0.zip")
        (file-name "24c102bcc418dedc-v0.1.0.zip")
        (sha256 (base32 "101hzrj009bkyy4g0sz8y9151csi0aqm7amwiwvxrphqqjy05h94"))))
   (list "go-module-com-github-mohae-deepcopy"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/mohae/deepcopy/@v/v0.0.0-20170308212314-bb9b5e7adda9.zip")
        (file-name "ba787dcf6444f09d-v0.0.0-20170308212314-bb9b5e7adda9.zip")
        (sha256 (base32 "03p7ky8zxw4prki6vmc5afzskg931d8ihz421di9vw24ck7psy5s"))))
   (list "go-module-com-github-opencontainers-go-digest"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/opencontainers/go-digest/@v/v1.0.0.zip")
        (file-name "615efb31ff6cd710-v1.0.0.zip")
        (sha256 (base32 "11kwwggrli2hrc3whanr7ips8kcbkmjw6f5ap0si1mvczwqznpk1"))))
   (list "go-module-com-github-opencontainers-image-spec"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/opencontainers/image-spec/@v/v1.1.1.zip")
        (file-name "3a32eeb459719172-v1.1.1.zip")
        (sha256 (base32 "0x4mq5mnfsvghi71hfa09yl6wg19nyspigi0gja754bib6sfwcis"))))
   (list "go-module-com-github-opencontainers-runtime-spec"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/opencontainers/runtime-spec/@v/v1.2.1.zip")
        (file-name "847dfbbec37aef7d-v1.2.1.zip")
        (sha256 (base32 "0cgg2vyfppx31mmakg44z8icsvh3xaqarsya2hg7vvvsqfzgnzc4"))))
   (list "go-module-com-github-sirupsen-logrus"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/sirupsen/logrus/@v/v1.9.3.zip")
        (file-name "4501f4e6b858bfdd-v1.9.3.zip")
        (sha256 (base32 "1l0x28bpbh57r9216kbbkfr7hcbschpxvz3ifscxvgsqp3kg80a5"))))
   (list "go-module-com-github-spiffe-go-spiffe-v2"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/spiffe/go-spiffe/v2/@v/v2.6.0.zip")
        (file-name "b90f378c70e2c985-v2.6.0.zip")
        (sha256 (base32 "1mnps09hacvd4xczf2ljcr7vnn427szj1jlk33v8bjg2f263f3xr"))))
   (list "go-module-com-github-vishvananda-netlink"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/vishvananda/netlink/@v/v1.3.1-0.20250303224720-0e7078ed04c8.zip")
        (file-name "e943364458eb3008-v1.3.1-0.20250303224720-0e7078ed04c8.zip")
        (sha256 (base32 "1kw3rdbh7s571058q1vqvk4rpcp4hbpvkhbzwxdhhc7bb123chz9"))))
   (list "go-module-com-github-vishvananda-netns"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/github.com/vishvananda/netns/@v/v0.0.5.zip")
        (file-name "07804b88c922c2a6-v0.0.5.zip")
        (sha256 (base32 "08llz96d7bdw2zmv6kiqhk2yl9niz7z2yfgy1rwadhi2r644p007"))))
   (list "go-module-com-google-cloud-go"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/cloud.google.com/go/@v/v0.123.0.zip")
        (file-name "e9c9509cf75beb95-v0.123.0.zip")
        (sha256 (base32 "0lldhwbablkfddrysrka95qjl3m204yi3ssyg4b9bssvyyf51jg9"))))
   (list "go-module-com-google-cloud-go-auth"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/cloud.google.com/go/auth/@v/v0.20.0.zip")
        (file-name "06371584193bbb88-v0.20.0.zip")
        (sha256 (base32 "0figcx9v19mdi9dvwhr6qmn6cidgxy2iv4y2yal8ifrv3621adq6"))))
   (list "go-module-com-google-cloud-go-auth-oauth2adapt"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/cloud.google.com/go/auth/oauth2adapt/@v/v0.2.8.zip")
        (file-name "4cd64264bafc4dd0-v0.2.8.zip")
        (sha256 (base32 "0qs9ag6i1nwmqns85g9hj4q95pss93hxcljlcigx0kgwp9j45mjc"))))
   (list "go-module-com-google-cloud-go-compute-metadata"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/cloud.google.com/go/compute/metadata/@v/v0.9.0.zip")
        (file-name "f97e35d1c96239b8-v0.9.0.zip")
        (sha256 (base32 "1jlyqmgnvspazx3ay7f2i4mcillm5hqpx9sl81bvhfb2r78kazpr"))))
   (list "go-module-com-google-cloud-go-iam"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/cloud.google.com/go/iam/@v/v1.7.0.zip")
        (file-name "a3d9f0ebc3baf0cd-v1.7.0.zip")
        (sha256 (base32 "0yn8xi8dvam8jxlighjqxs6kp75i10ji3gmp7nhwvw5sqgmz1nd3"))))
   (list "go-module-com-google-cloud-go-monitoring"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/cloud.google.com/go/monitoring/@v/v1.24.3.zip")
        (file-name "e28a4ca46eef2ade-v1.24.3.zip")
        (sha256 (base32 "12psf870xngpxji6jpsfb1rnd9ckb4373vi9y9nxwapgdsj4r2p2"))))
   (list "go-module-com-google-cloud-go-storage"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/cloud.google.com/go/storage/@v/v1.62.1.zip")
        (file-name "2c8a2520ef58c3d2-v1.62.1.zip")
        (sha256 (base32 "1y4pjf0gs5c4sh1wj02fvcbxnym3rv12wfg0x6kd5hsqxwh2b2ic"))))
   (list "go-module-in-gopkg-yaml-v2"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/gopkg.in/yaml.v2/@v/v2.4.0.zip")
        (file-name "ede49e27c4cca6cd-v2.4.0.zip")
        (sha256 (base32 "1zcisg0dxyw6lzki3m5krq672qyklj7fv6kixk9cv9ncqhkrxr7d"))))
   (list "go-module-io-opentelemetry-go-auto-sdk"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/go.opentelemetry.io/auto/sdk/@v/v1.2.1.zip")
        (file-name "a08a16fc0a7041cd-v1.2.1.zip")
        (sha256 (base32 "0dc31hw7cg0458q5mxl55hhk41h0aq52cyplfnwcshbh1by1d2m0"))))
   (list "go-module-io-opentelemetry-go-contrib-detectors-gcp"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/go.opentelemetry.io/contrib/detectors/gcp/@v/v1.39.0.zip")
        (file-name "861471f535479361-v1.39.0.zip")
        (sha256 (base32 "1gdp66h348xpgkbcfs4y322xv5lypzv40vzq3dm634s76psp2546"))))
   (list "go-module-io-opentelemetry-go-contrib-instrumentation-google-golang-org-grpc-otelgrpc"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/@v/v0.67.0.zip")
        (file-name "8d28360aab471b39-v0.67.0.zip")
        (sha256 (base32 "1lbwdinp3k94g5g4hjx07dygk7frixrmw7pah5ykj6s7mc53ca4d"))))
   (list "go-module-io-opentelemetry-go-contrib-instrumentation-net-http-otelhttp"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/@v/v0.67.0.zip")
        (file-name "a184e0b582e09004-v0.67.0.zip")
        (sha256 (base32 "1ry87kiq0l6rpixzn1s9d507lfx8w8kg7dkj2bq09470hasy1151"))))
   (list "go-module-io-opentelemetry-go-otel"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/go.opentelemetry.io/otel/@v/v1.43.0.zip")
        (file-name "177d24c79e756950-v1.43.0.zip")
        (sha256 (base32 "088rcl0mnrsz5jvn0lj3zv3pr05v2g3c31xa67250sbmkv3j8z8p"))))
   (list "go-module-io-opentelemetry-go-otel-metric"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/go.opentelemetry.io/otel/metric/@v/v1.43.0.zip")
        (file-name "3efb5ad706fab815-v1.43.0.zip")
        (sha256 (base32 "19h8ibfi08vwq43d9v877x0d5j3fcp0qkz78nbs1bf7s0vbmmyry"))))
   (list "go-module-io-opentelemetry-go-otel-sdk"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/go.opentelemetry.io/otel/sdk/@v/v1.43.0.zip")
        (file-name "cf46abeb516a88a0-v1.43.0.zip")
        (sha256 (base32 "1wp871ly3aj88yl8gm0wp46iy5mkkzih6w8i6gms123aa7msning"))))
   (list "go-module-io-opentelemetry-go-otel-sdk-metric"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/go.opentelemetry.io/otel/sdk/metric/@v/v1.43.0.zip")
        (file-name "b02c5dded25925d2-v1.43.0.zip")
        (sha256 (base32 "0jgwc7cgnfjg07c7sjmbfsjqddrfdx29v9lfryzd49arsbg5sb5h"))))
   (list "go-module-io-opentelemetry-go-otel-trace"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/go.opentelemetry.io/otel/trace/@v/v1.43.0.zip")
        (file-name "34fdc70a75e90d68-v1.43.0.zip")
        (sha256 (base32 "0bdn7jz0mpc98kpfm4w325k55pm503lbjndadkinh3g9fl5cgz9l"))))
   (list "go-module-org-golang-google-api"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/google.golang.org/api/@v/v0.274.0.zip")
        (file-name "7d6d36f933d73c87-v0.274.0.zip")
        (sha256 (base32 "02xm9gdymgnxkmynvlgs3wzmscn6jjyrkwc347mqfg6p6gwkcvbx"))))
   (list "go-module-org-golang-google-genproto"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/google.golang.org/genproto/@v/v0.0.0-20260319201613-d00831a3d3e7.zip")
        (file-name "a75d9f7ea0d1bba5-v0.0.0-20260319201613-d00831a3d3e7.zip")
        (sha256 (base32 "03s0wlh4s4wmnblw1s1gya46r1jcfr4chsf7rrxabfyil1z9ypd7"))))
   (list "go-module-org-golang-google-genproto-googleapis-api"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/google.golang.org/genproto/googleapis/api/@v/v0.0.0-20260401024825-9d38bb4040a9.zip")
        (file-name "88b3d97eaf60fbc3-v0.0.0-20260401024825-9d38bb4040a9.zip")
        (sha256 (base32 "1gv7940fpg40pff3nvibinfdr9gr1hchxgxkgykc7yv0mxzdkcw8"))))
   (list "go-module-org-golang-google-genproto-googleapis-rpc"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/google.golang.org/genproto/googleapis/rpc/@v/v0.0.0-20260401024825-9d38bb4040a9.zip")
        (file-name "782f7750728f860a-v0.0.0-20260401024825-9d38bb4040a9.zip")
        (sha256 (base32 "1hz7ik6wndp2qxcn8mfhsqs89xcn4v7qclg84h10m1lgf987fbvq"))))
   (list "go-module-org-golang-google-grpc"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/google.golang.org/grpc/@v/v1.80.0.zip")
        (file-name "12b91cdce1bbcd83-v1.80.0.zip")
        (sha256 (base32 "0y8pwk12hqrrk8wappg08kvbym5l14mc8wggjdqq7kdvw7f1rf8j"))))
   (list "go-module-org-golang-google-grpc-cmd-protoc-gen-go-grpc"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/google.golang.org/grpc/cmd/protoc-gen-go-grpc/@v/v1.5.1.zip")
        (file-name "997320e3e21562ef-v1.5.1.zip")
        (sha256 (base32 "1cm84xba34dim4kp5b5sal12l73da2qw1218sxkyyqhmwbij0wwr"))))
   (list "go-module-org-golang-google-protobuf"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/google.golang.org/protobuf/@v/v1.36.11.zip")
        (file-name "14983d36c56a814e-v1.36.11.zip")
        (sha256 (base32 "0x6jgiiwhcmil0l3pd2fp2hsnnw9iwmjyrbd3gclx0baqlv3v60l"))))
   (list "go-module-org-golang-x-crypto"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/crypto/@v/v0.49.0.zip")
        (file-name "cbca45d1fcb0fa35-v0.49.0.zip")
        (sha256 (base32 "0p801zmv6zc0g7mzszpz8hka78fghsx89f1jsaf3bymhzk8lbjnb"))))
   (list "go-module-org-golang-x-exp"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/exp/@v/v0.0.0-20250711185948-6ae5c78190dc.zip")
        (file-name "01d8fecd44e904b8-v0.0.0-20250711185948-6ae5c78190dc.zip")
        (sha256 (base32 "1ampv406dj5rwxg4ad057i8i4wxj0fsgd367crpbh1798k6zxn01"))))
   (list "go-module-org-golang-x-exp-typeparams"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/exp/typeparams/@v/v0.0.0-20221208152030-732eee02a75a.zip")
        (file-name "9bd73f186851c622-v0.0.0-20221208152030-732eee02a75a.zip")
        (sha256 (base32 "195412jq016cyzsgdgnbdawf45ldc0gri1plhja25ijid0c3zmwv"))))
   (list "go-module-org-golang-x-mod"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/mod/@v/v0.34.0.zip")
        (file-name "8e6b8d8a771dac07-v0.34.0.zip")
        (sha256 (base32 "0cmanhi317gddw71gxzl6585dhx4zfqh3iy88h6hgb0xfy58sswf"))))
   (list "go-module-org-golang-x-net"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/net/@v/v0.52.0.zip")
        (file-name "5b8bf13a81552cd4-v0.52.0.zip")
        (sha256 (base32 "1v8px58r5hgrdwwnwi2lgvjyqwhyzdw2pbkdq3zx8b2mh4xg32sv"))))
   (list "go-module-org-golang-x-oauth2"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/oauth2/@v/v0.36.0.zip")
        (file-name "15bf65ff103e5daf-v0.36.0.zip")
        (sha256 (base32 "0125609jl02n262lx0jihk5qrs6il4vx136p174ayp9y23znbgqm"))))
   (list "go-module-org-golang-x-sync"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/sync/@v/v0.20.0.zip")
        (file-name "7179d4d68800f6fd-v0.20.0.zip")
        (sha256 (base32 "0xfkrcihgqiz41f3128c6r09ppxmrc8vyjwxvg5gvxh0i3bd8ybi"))))
   (list "go-module-org-golang-x-sys"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/sys/@v/v0.43.0.zip")
        (file-name "cb8b073934cf7e57-v0.43.0.zip")
        (sha256 (base32 "1pxd1bnarrs9qvyhfvxgjz7nzyfm34kd3i40kyf5fzng6hwhg2yb"))))
   (list "go-module-org-golang-x-telemetry"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/telemetry/@v/v0.0.0-20250908211612-aef8a434d053.zip")
        (file-name "ae079c5f1321c91f-v0.0.0-20250908211612-aef8a434d053.zip")
        (sha256 (base32 "0klv19v2jjs9q50wwm368hl45mzf7sialnifmyn1zj912dgrq1xf"))))
   (list "go-module-org-golang-x-term"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/term/@v/v0.42.0.zip")
        (file-name "c69cf2bf68d1d73e-v0.42.0.zip")
        (sha256 (base32 "1hpk0ii8rh7dm8svpdpr9rffzv8nfdl9l70wlcakxmyid2zz5766"))))
   (list "go-module-org-golang-x-text"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/text/@v/v0.36.0.zip")
        (file-name "15c60227cf084605-v0.36.0.zip")
        (sha256 (base32 "0g5j89g7ldm92j5ydjc0zq4i2hdgrzcsr3kb4nh0aih8rwkh5ihm"))))
   (list "go-module-org-golang-x-time"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/time/@v/v0.15.0.zip")
        (file-name "8cfb20e915fa5d6c-v0.15.0.zip")
        (sha256 (base32 "113zlafsscn576982dwawj2k66npz0rl4c34s8znqpgs2plj1ywc"))))
   (list "go-module-org-golang-x-tools"
     (origin
        (method url-fetch)
        (uri "https://proxy.golang.org/golang.org/x/tools/@v/v0.43.0.zip")
        (file-name "7c1f13a8ddbf2de1-v0.43.0.zip")
        (sha256 (base32 "0aql5k571fnji12s48grqxp1b34kahvr8w0idq9y2bdzvnl167vw"))))))
