#!/bin/sh
exec guile -e '(@ (pinenote tools power power-snapshot) command-line-main)' -s "$0" "$@"
!#
;; Read-only PineNote power evidence recorder.  It deliberately has no command
;; runner and writes reports only to stdout.
(define-module (pinenote tools power power-snapshot)
  #:use-module (ice-9 match)
  #:use-module (ice-9 rdelim)
  #:use-module (ice-9 ftw)
  #:use-module (ice-9 textual-ports)
  #:use-module (srfi srfi-1)
  #:export (snapshot delta main command-line-main schema-name schema-version lookup text-value numeric-delta
             set-reader-for-test! reset-reader-for-test! safe-output-path?))

(define schema-name "wilkbook-pinenote-power")
(define schema-version 1)

(define (root-path root path)
  (string-append (if (string=? root "/") "" root) path))

(define default-reader
  (lambda (path) (call-with-input-file path get-string-all)))
(define current-reader default-reader)
(define (set-reader-for-test! reader) (set! current-reader reader))
(define (reset-reader-for-test!) (set! current-reader default-reader))
(define (text-value root path)
  (catch #t
    (lambda ()
      `(available (source ,path) (value ,(string-trim-both (current-reader (root-path root path))))))
    (lambda args `(unavailable (source ,path) (error ,(format #f "~a" args))))))

(define (number-or-text text)
  (let ((n (string->number text))) (if n n text)))

(define (numeric-value root path)
  (match (text-value root path)
    (('available ('source source) ('value value))
     `(available (source ,source) (value ,(number-or-text value))))
    (other other)))

(define (directory-names root path)
  (sort (filter (lambda (name) (not (member name '("." ".."))))
                (scandir (root-path root path)))
        string<?))

(define (directory-unavailable path args)
  `(unavailable (source ,path) (error ,(format #f "~a" args))))

(define (records root directory properties)
  (catch #t
    (lambda ()
      (map (lambda (name)
             `(record (name ,name)
                      (properties ,(map (lambda (property)
                                          `(,property ,(numeric-value root
                                                                      (string-append directory "/" name "/" property))))
                                         (map (lambda (property)
                                                (if (symbol? property) (symbol->string property) property))
                                              properties)))))
           (directory-names root directory)))
    (lambda args (directory-unavailable directory args))))
(define (records-for-names root directory properties names)
  (map (lambda (name)
         `(record (name ,name)
                  (properties ,(map (lambda (property)
                                      `(,property ,(numeric-value root
                                                                  (string-append directory "/" name "/" property))))
                                    (map (lambda (property)
                                           (if (symbol? property) (symbol->string property) property))
                                         properties)))))
       names))

(define (lines root path)
  (match (text-value root path)
    (('available ('source source) ('value value))
     `(available (source ,source) (lines ,(string-split value #\newline))) )
    (other other)))

(define (parse-interrupt-line line)
  (let ((colon (string-index line #\:)))
    (and colon
         (let* ((irq (string-trim-both (substring line 0 colon)))
                (fields (string-tokenize (substring line (+ colon 1))))
                (counts (take-while string->number fields))
                (description (string-join (drop fields (length counts)) " ")))
           (and (not (null? counts))
                `(interrupt (irq ,irq) (cpu-counts ,(map string->number counts))
                            (description ,description)))))))

(define (interrupts root)
  (match (lines root "/proc/interrupts")
    (('available ('source source) ('lines lines))
     `(available (source ,source)
                 (entries ,(filter-map parse-interrupt-line (cdr lines)))))
    (other other)))

(define (parse-stat-line line)
  (let ((f (string-tokenize line)))
    (and (pair? f) (string-prefix? "cpu" (car f))
         `(cpu (name ,(car f)) (counters ,(map string->number (cdr f)))))))

(define (cpu-stat root)
  (match (lines root "/proc/stat")
    (('available ('source source) ('lines lines))
     `(available (source ,source) (entries ,(filter-map parse-stat-line lines))))
    (other other)))

(define (parse-wakeup-row header line)
  (let ((fields (string-tokenize line)))
    (and (= (length fields) (length header))
         (let ((numbers (map string->number (cdr fields))))
           (and (every number? numbers)
                `(wakeup-source (name ,(car fields))
                                (counters ,(map (lambda (key value) `(,key ,value))
                                                (cdr header) numbers))))))))
(define (wakeup-sources root)
  (match (lines root "/sys/kernel/debug/wakeup_sources")
    (('available ('source source) ('lines (header . rows)))
     (let ((columns (string-tokenize header)))
       `(available (source ,source) (columns ,columns)
                   (entries ,(filter-map (lambda (line) (parse-wakeup-row columns line)) rows)))))
    (other other)))

(define pm-attributes '(runtime_status runtime_usage runtime_active_time
                         runtime_suspended_time control wakeup autosuspend_delay_ms))
(define pm-buses '(platform i2c spi mmc sdio usb))
(define (runtime-records root directory)
  (catch #t
    (lambda ()
      (map (lambda (name)
             `(device (name ,name)
                      (properties ,(map (lambda (property)
                                          `(,property ,(numeric-value root
                                                                      (string-append directory "/" name "/power/" property))))
                                        (map symbol->string pm-attributes)))))
           (directory-names root directory)))
    (lambda args (directory-unavailable directory args))))
(define (runtime-device root directory name)
  `(device (name ,name)
           (properties ,(map (lambda (property)
                               `(,property ,(numeric-value root
                                                           (string-append directory "/" name "/power/" property))))
                             (map symbol->string pm-attributes)))))

(define (runtime-pm root)
  `(record (buses ,(map (lambda (bus)
                          `(,bus ,(runtime-records root (string-append "/sys/bus/" (symbol->string bus) "/devices"))) )
                        pm-buses))))

(define (class-wakeup root)
  (records root "/sys/class/wakeup" '(name active_count event_count wakeup_count expire_count
                                       active_since total_time max_time last_change prevent_suspend_time)))

(define (power-supplies root)
  (records root "/sys/class/power_supply"
            '(type status present capacity capacity_level voltage_now voltage_avg current_now current_avg
                   charge_now charge_full charge_full_design charge_counter energy_now energy_full
                   energy_full_design power_now time_to_empty_now time_to_full_now temp cycle_count health online
                   constant_charge_voltage_max constant_charge_current_max voltage_min_design voltage_max_design
                   charge_empty_design charge_type usb_type)))

(define (network root)
  `(record (interfaces ,(records root "/sys/class/net" '(carrier operstate address)))
           (wireless ,(text-value root "/proc/net/wireless"))))

(define selected-processes '("koreader" "luajit" "orientation-bridge" "wpa_supplicant" "dhcpcd" "sshd" "agetty"))
(define (cmdline-value root pid)
  (match (text-value root (string-append "/proc/" pid "/cmdline"))
    (('available ('source source) ('value value))
     `(available (source ,source) (arguments ,(filter (lambda (x) (not (string-null? x)))
                                                        (string-split value #\nul)))))
    (other other)))
(define (processes root)
  (catch #t
    (lambda ()
      (let ((pids (filter (lambda (name) (string->number name))
                          (directory-names root "/proc"))))
        `(selected
          ,(filter-map
            (lambda (pid)
              (let ((comm (text-value root (string-append "/proc/" pid "/comm"))))
                (if (match comm (('available ('source _) ('value value)) (member value selected-processes)) (_ #f))
                    `(process (pid ,pid) (comm ,comm) (cmdline ,(cmdline-value root pid))
                              (stat ,(text-value root (string-append "/proc/" pid "/stat")))
                              (cpu ,(process-cpu root pid)))
                    #f)))
            pids))))
    (lambda args (directory-unavailable "/proc" args))))

(define (process-cpu root pid)
  (let ((path (string-append "/proc/" pid "/stat")))
    (match (text-value root path)
      (('available ('source source) ('value value))
       (let ((close (string-rindex value #\))))
         (if close
             (let ((fields (string-tokenize (substring value (+ close 1)))))
               (if (>= (length fields) 20)
                   `(available (source ,source) (utime ,(number-or-text (list-ref fields 11)))
                                (stime ,(number-or-text (list-ref fields 12)))
                                (starttime ,(number-or-text (list-ref fields 19))))
                   `(unavailable (source ,source) (error "short proc stat row"))))
             `(unavailable (source ,source) (error "malformed proc stat row")))))
      (other other))))

(define (cpu-idle root)
  `(record
    (cpus ,(catch #t
             (lambda ()
               (map (lambda (cpu)
                      `(cpu (name ,cpu)
                            (states ,(records root (string-append "/sys/devices/system/cpu/" cpu "/cpuidle")
                                              '(name latency usage time)))))
                    (filter (lambda (name) (string-prefix? "cpu" name))
                            (directory-names root "/sys/devices/system/cpu"))))
             (lambda args (directory-unavailable "/sys/devices/system/cpu" args))))))

(define dt-base "/sys/firmware/devicetree/base")
(define (real-directory? path)
  (catch #t (lambda () (eq? (stat:type (lstat path)) 'directory))
         (lambda args #f)))
(define (dt-walk-wakeup-sources full relative)
  (sort (append-map
         (lambda (name)
           (let ((child (string-append full "/" name))
                 (child-relative (string-append relative "/" name)))
             (cond ((string=? name "wakeup-source") (list child-relative))
                   ((real-directory? child) (dt-walk-wakeup-sources child child-relative))
                   (else '()))))
         (filter (lambda (name) (not (member name '("." "..")))) (scandir full)))
        string<?))
(define (dt-wakeup-sources root)
  (let ((base (root-path root dt-base)))
    (if (not (real-directory? base)) `(absent (source ,dt-base))
        (catch #t
           (lambda () `(available (source ,dt-base)
                                  (paths ,(dt-walk-wakeup-sources base dt-base))))
          (lambda args `(unavailable (source ,dt-base) (error ,(format #f "~a" args))))))))
(define (dt-idle-states root)
  (let ((path "/sys/firmware/devicetree/base/cpus/idle-states"))
    (if (not (real-directory? (root-path root path))) `(absent (source ,path))
        (catch #t
          (lambda ()
            `(available (source ,path)
                        (nodes ,(filter (lambda (name)
                                          (real-directory? (root-path root (string-append path "/" name))))
                                        (directory-names root path)))))
          (lambda args (directory-unavailable path args))))))

(define (cpu-frequency root)
  (let ((directory "/sys/devices/system/cpu/cpufreq"))
    (catch #t
      (lambda ()
        (records-for-names root directory
                           '(scaling_driver affected_cpus related_cpus cpuinfo_cur_freq cpuinfo_transition_latency
                             scaling_available_frequencies scaling_available_governors
                             scaling_governor scaling_cur_freq scaling_min_freq scaling_max_freq
                             cpuinfo_min_freq cpuinfo_max_freq stats/total_trans stats/time_in_state)
                           (filter (lambda (name)
                                     (and (string-prefix? "policy" name)
                                          (> (string-length name) 6)
                                          (every char-numeric? (string->list (substring name 6)))
                                          (real-directory? (root-path root (string-append directory "/" name)))))
                                   (directory-names root directory))))
      (lambda args (directory-unavailable directory args)))))
(define (usb-gadgets root)
  `(record (udcs ,(records root "/sys/class/udc" '(state function driver)))
           (gadgets ,(records root "/sys/kernel/config/usb_gadget" '(UDC)))))

(define (snapshot root phase timestamp)
  `(snapshot (schema ,schema-name) (version ,schema-version) (phase ,phase) (timestamp ,timestamp)
              (system-power (record (state ,(text-value root "/sys/power/state"))
                            (mem-sleep ,(text-value root "/sys/power/mem_sleep"))
                            (wakeup-count ,(numeric-value root "/sys/power/wakeup_count"))
                            (pm-wakeup-irq ,(numeric-value root "/sys/power/pm_wakeup_irq"))
                            (pm-debug-messages ,(text-value root "/sys/power/pm_debug_messages"))
                           (dt-model ,(text-value root "/sys/firmware/devicetree/base/model"))
                           (dt-compatible ,(text-value root "/sys/firmware/devicetree/base/compatible"))
                            (dt-wakeup-sources ,(dt-wakeup-sources root))
                            (dt-cpu-idle-states ,(dt-idle-states root))))
              (suspend-stats (record (success ,(numeric-value root "/sys/kernel/debug/suspend_stats/success"))
                            (fail ,(numeric-value root "/sys/kernel/debug/suspend_stats/fail"))
                             (last-failed-dev ,(text-value root "/sys/kernel/debug/suspend_stats/last_failed_dev"))))
             (power-supplies ,(power-supplies root))
             (wakeup-sources ,(wakeup-sources root))
             (class-wakeup-devices ,(class-wakeup root))
             (runtime-pm ,(runtime-pm root))
             (interrupts ,(interrupts root))
               (cpu (record (stat ,(cpu-stat root))
                   (frequency ,(cpu-frequency root))
                    (idle ,(cpu-idle root))))
              (processes ,(processes root))
               (workload (record (backlight ,(records root "/sys/class/backlight" '(brightness actual_brightness)))
                       (network ,(network root))
                        (usb-gadget ,(usb-gadgets root))
                        (ebc-runtime-pm ,(runtime-device root "/sys/bus/platform/devices" "fdec0000.ebc"))
                       (orientation (consumer ,(text-value root "/run/wilkbook-orientation.consumer"))
                                    (state ,(text-value root "/run/wilkbook-orientation.state")))
                         (mountinfo ,(text-value root "/proc/self/mountinfo"))))
                (diagnostics (record (root ,root) (collector "read-only allowlisted paths")
                                     (waveform-vcom "never read")))))

(define (lookup field object) (let ((x (assoc field (cdr object)))) (and x (cadr x))))
(define (numeric-delta before after)
  (cond ((and (number? before) (number? after))
         (if (>= after before) `(delta ,(- after before)) `(reset (before ,before) (after ,after))))
         (else `(unavailable (reason "non-numeric or absent")))))
(define (signed-delta before after)
  (if (and (number? before) (number? after)) `(delta ,(- after before))
      `(unavailable (reason "non-numeric or absent"))))
(define (record-identity value)
  (and (pair? value)
       (cond ((string? (car value)) (car value))
             ((symbol? (car value))
              (let* ((process? (eq? (car value) 'process))
                     (pid (and process? (assoc 'pid (cdr value))))
                     (cpu (and process? (assoc 'cpu (cdr value))))
                     (starttime (and cpu (pair? (cadr cpu))
                                     (assoc 'starttime (cdr (cadr cpu)))))
                     (identity (and (every pair? (cdr value))
                                    (or (assoc 'name (cdr value)) (assoc 'irq (cdr value)) pid))))
                (cond ((and pid starttime) (list 'process (cadr pid) (cadr starttime)))
                      (identity (list (car value) (cadr identity)))
                      ;; Bus wrappers (i2c, platform, ...) are uniquely tagged within
                      ;; runtime-pm and retain that scope without an ordinal.
                      ((every pair? (cdr value)) (car value))
                      (else #f))))
             (else #f))))
(define (identifiable-record-list? values)
  (let ((ids (map record-identity values)))
    (and (not (null? values)) (every (lambda (id) id) ids)
         (= (length ids) (length (delete-duplicates ids equal?))))))
(define (numeric-leaves value)
  (let walk ((value value) (path '()))
    (cond ((number? value) (list (cons (reverse path) value)))
           ((pair? value)
            (cond ((string? (car value))
                   (append-map (lambda (item) (walk item (cons (car value) path))) (cdr value)))
                  ((symbol? (car value))
                 (let ((identity (record-identity value)))
                   (append-map (lambda (item)
                                 (walk item (cons (or identity (car value)) path)))
                               (cdr value))))
                   ((identifiable-record-list? value)
                      (append-map (lambda (item) (walk item path)) value))
                   (else
                      (let loop ((items value) (index 0))
                        (if (null? items) '()
                            (append (walk (car items) (cons index path))
                                   (loop (cdr items) (+ index 1))))))))
          (else '()))))
(define (domain-deltas before after name change-kind)
  (let ((old (numeric-leaves (lookup name before)))
        (new (numeric-leaves (lookup name after)))
        (change (if (eq? change-kind 'signed-observation) signed-delta numeric-delta)))
    `(domain (semantics ,change-kind)
             (entries
                 ,(filter-map
                   (lambda (entry)
                     (let ((later (assoc (car entry) new)))
                       (and later `(counter (key ,(car entry))
                                            (change ,(change (cdr entry) (cdr later)))))))
                     old)))))
(define (delta before after)
  `(delta (schema ,schema-name) (version ,schema-version)
          (before-phase ,(lookup 'phase before)) (after-phase ,(lookup 'phase after))
          (elapsed-seconds ,(numeric-delta (lookup 'timestamp before) (lookup 'timestamp after)))
          (battery ,(domain-deltas before after 'power-supplies 'signed-observation))
          (interrupts ,(domain-deltas before after 'interrupts 'monotonic-counter))
          (wakeup-sources ,(domain-deltas before after 'wakeup-sources 'monotonic-counter))
          (runtime-pm ,(domain-deltas before after 'runtime-pm 'monotonic-counter))
          (cpu ,(domain-deltas before after 'cpu 'monotonic-counter))
          (processes ,(domain-deltas before after 'processes 'monotonic-counter))))
(define (valid-snapshot? value)
  (and (pair? value) (eq? (car value) 'snapshot)
       (equal? (lookup 'schema value) schema-name) (= (lookup 'version value) schema-version)))
(define (read-snapshot path)
  (catch #t (lambda () (let ((value (call-with-input-file path read)))
                         (and (valid-snapshot? value) value)))
         (lambda args #f)))

(define (safe-output-path? path)
  (string=? path "-"))
(define (write-report value output)
  (if (not (safe-output-path? output))
      #f
      (begin
        (write value)
        (newline)
        #t)))
(define (usage) (display "usage: power-snapshot.scm snapshot [--root ROOT] --phase LABEL [--timestamp EPOCH] [--output -]\n       power-snapshot.scm delta BEFORE AFTER [--output -]\n" (current-error-port)))
(define (arg-value args name default)
  (let loop ((rest args)) (match rest (() default) ((x y . tail) (if (string=? x name) y (loop (cdr rest)))) ((x . tail) (loop tail)))))
(define (option-pairs? args allowed)
  (match args (() #t) ((flag value . tail) (and (member flag allowed) (option-pairs? tail allowed))) (_ #f)))
(define (main args)
  (match args
    (("snapshot" . rest)
     (let ((phase (arg-value rest "--phase" #f)))
       (if (or (not phase) (not (option-pairs? rest '("--root" "--phase" "--timestamp" "--output")))
               (not (string->number (arg-value rest "--timestamp" "0"))))
           (begin (usage) 2)
            (if (write-report (snapshot (arg-value rest "--root" "/") phase
                                        (string->number (arg-value rest "--timestamp"
                                                                      (number->string (current-time)))))
                              (arg-value rest "--output" "-"))
                0
                (begin (display "power-snapshot: unsafe output path\n" (current-error-port)) 2)))))
    (("delta" before-path after-path . rest)
     (if (not (option-pairs? rest '("--output"))) (begin (usage) 2)
         (let ((before (read-snapshot before-path)) (after (read-snapshot after-path)))
           (cond ((not (and before after))
                  (display "power-snapshot: invalid snapshot input\n" (current-error-port)) 2)
                 ((write-report (delta before after) (arg-value rest "--output" "-")) 0)
                 (else (display "power-snapshot: unsafe output path\n" (current-error-port)) 2)))))
    (_ (usage) 2)))

(define (command-line-main args)
  (exit (main (cdr args))))
