(define-module (pinenote packages ebc-test)
  #:use-module (guix build-system trivial)
  #:use-module (guix gexp)
  #:use-module (guix licenses)
  #:use-module (guix packages))

(define-public pinenote-ebc-test
  (package
    (name "pinenote-ebc-test")
    (version "0.1.0")
    (source #f)
    (build-system trivial-build-system)
    (arguments
     (list
      #:modules '((guix build utils))
      #:builder
      #~(begin
          (use-modules (guix build utils))
          (let* ((out #$output)
                 (bin (string-append out "/bin"))
                 (script (string-append bin "/pinenote-ebc-test")))
            (mkdir-p bin)
            (call-with-output-file script
              (lambda (port)
                (display "#!/bin/sh\n" port)
                (display "set -eu\n" port)
                (display "fb=/dev/fb0\n" port)
                (display "geometry=/sys/class/graphics/fb0/virtual_size\n" port)
                (display "bpp_file=/sys/class/graphics/fb0/bits_per_pixel\n" port)
                (display "stride_file=/sys/class/graphics/fb0/stride\n" port)
                (display "draw_smoke() {\n" port)
                (display "  [ -c \"$fb\" ] || { echo 'missing framebuffer /dev/fb0' >&2; exit 1; }\n" port)
                (display "  [ -r \"$geometry\" ] && [ -r \"$bpp_file\" ] && [ -r \"$stride_file\" ] || { echo 'missing framebuffer geometry sysfs' >&2; exit 1; }\n" port)
                (display "  IFS=, read width height < \"$geometry\"\n" port)
                (display "  bpp=$(cat \"$bpp_file\")\n" port)
                (display "  stride=$(cat \"$stride_file\")\n" port)
                (display "  bytes_per_pixel=$((bpp / 8))\n" port)
                (display "  size=96\n" port)
                (display "  x=32\n" port)
                (display "  y=32\n" port)
                (display "  [ \"$bytes_per_pixel\" -gt 0 ] && [ $((x + size)) -le \"$width\" ] && [ $((y + size)) -le \"$height\" ] || { echo 'framebuffer geometry is too small for smoke test' >&2; exit 1; }\n" port)
                (display "  row_bytes=$((size * bytes_per_pixel))\n" port)
                (display "  temporary=$(mktemp -d /tmp/pinenote-ebc-test.XXXXXX)\n" port)
                (display "  trap 'rm -rf -- \"$temporary\"' EXIT HUP INT TERM\n" port)
                (display "  dd if=/dev/zero bs=1 count=\"$row_bytes\" status=none | tr '\\000' '\\377' > \"$temporary/white-row\"\n" port)
                (display "  row=0\n" port)
                (display "  while [ \"$row\" -lt \"$size\" ]; do\n" port)
                (display "    offset=$(((y + row) * stride + x * bytes_per_pixel))\n" port)
                (display "    dd if=\"$fb\" of=\"$temporary/row-$row\" bs=1 skip=\"$offset\" count=\"$row_bytes\" status=none\n" port)
                (display "    dd if=\"$temporary/white-row\" of=\"$fb\" bs=1 seek=\"$offset\" conv=notrunc status=none\n" port)
                (display "    row=$((row + 1))\n" port)
                (display "  done\n" port)
                (display "  sync\n" port)
                (display "  echo \"pinenote-ebc-test: drew ${size}x${size} white square at ${x},${y}; restoring in 10 seconds\"\n" port)
                (display "  sleep 10\n" port)
                (display "  row=0\n" port)
                (display "  while [ \"$row\" -lt \"$size\" ]; do\n" port)
                (display "    offset=$(((y + row) * stride + x * bytes_per_pixel))\n" port)
                (display "    dd if=\"$temporary/row-$row\" of=\"$fb\" bs=1 seek=\"$offset\" conv=notrunc status=none\n" port)
                (display "    row=$((row + 1))\n" port)
                (display "  done\n" port)
                (display "  sync\n" port)
                (display "  echo 'pinenote-ebc-test: framebuffer smoke test restored saved region'\n" port)
                (display "}\n" port)
                (display "case \"${1:-}\" in\n" port)
                (display "  --draw-smoke) draw_smoke; exit 0 ;;\n" port)
                (display "  --help) echo 'usage: pinenote-ebc-test [--draw-smoke]'; exit 0 ;;\n" port)
                (display "  '') ;;\n" port)
                (display "  *) echo 'usage: pinenote-ebc-test [--draw-smoke]' >&2; exit 2 ;;\n" port)
                (display "esac\n" port)
                (display "echo 'pinenote-ebc-test: read-only report; use --draw-smoke for a reversible framebuffer test'\n" port)
                (display "echo 'rockchip_ebc parameters:'\n" port)
                (display "if [ -d /sys/module/rockchip_ebc/parameters ]; then\n" port)
                (display "  for parameter in /sys/module/rockchip_ebc/parameters/*; do\n" port)
                (display "    [ -r \"$parameter\" ] || continue\n" port)
                (display "    printf '%s=' \"$(basename \"$parameter\")\"\n" port)
                (display "    cat \"$parameter\"\n" port)
                (display "  done\n" port)
                (display "else\n" port)
                (display "  echo 'rockchip_ebc module parameters not present'\n" port)
                (display "fi\n" port)
                (display "echo 'DRM devices:'\n" port)
                (display "ls -1 /dev/dri 2>/dev/null || true\n" port)
                (display "echo 'No framebuffer, DRM, EBC, partition, or bootloader writes are performed unless --draw-smoke is passed.'\n" port)))
            (chmod script #o555)))))
    (home-page "https://github.com/m-weigand/linux/tree/branch_pinenote_6-12-11")
    (synopsis "Conservative PineNote EBC bring-up placeholder")
    (description
      "Install a small pinenote-ebc-test command that reports the EBC and DRM
state without writing by default, and can run an explicit reversible framebuffer
smoke test with --draw-smoke.  It is a real package so the minimal
operating-system declaration can refer to an in-repository test artifact while
native rendering is still being implemented.")
    (license gpl3+)))
