(define-module (pinenote packages firmware)
  #:use-module (guix build-system trivial)
  #:use-module (guix gexp)
  #:use-module (guix licenses)
  #:use-module (guix packages))

(define-public pinenote-firmware-support
  (package
    (name "pinenote-firmware-support")
    (version "0.1.0")
    (source #f)
    (build-system trivial-build-system)
    (arguments
     (list
      #:modules '((guix build utils))
      #:builder
      #~(begin
          (use-modules (guix build utils))
          (let* ((out #$output)
                 (bin (string-append out "/bin"))
                 (modprobe (string-append out "/etc/modprobe.d"))
                 (script (string-append bin "/pinenote-install-waveform"))
                 (params-script (string-append bin "/pinenote-apply-ebc-params"))
                 (config (string-append modprobe "/rockchip_ebc.conf")))
            (mkdir-p bin)
            (mkdir-p modprobe)
            (call-with-output-file script
              (lambda (port)
                (display "#!/bin/sh\n" port)
                (display "set -eu\n" port)
                (display "primary_source=/dev/disk/by-partlabel/waveform\n" port)
                (display "fallback_source=/state/firmware/ebc.wbf\n" port)
                (display "destination=/lib/firmware/rockchip/ebc.wbf\n" port)
                (display "destination_directory=/lib/firmware/rockchip\n" port)
                (display "if [ -e \"$destination\" ]; then\n" port)
                (display "  echo \"waveform already installed at $destination\"\n" port)
                (display "  exit 0\n" port)
                (display "fi\n" port)
                (display "temporary=\"$destination.tmp\"\n" port)
                (display "if [ -e \"$primary_source\" ]; then\n" port)
                (display "  source=$primary_source\n" port)
                (display "elif [ -e \"$fallback_source\" ]; then\n" port)
                (display "  source=$fallback_source\n" port)
                (display "else\n" port)
                (display "  echo 'no waveform source found; not loading EBC panel firmware' >&2\n" port)
                (display "  exit 1\n" port)
                (display "fi\n" port)
                (display "mkdir -p -- \"$destination_directory\"\n" port)
                (display "echo \"copying waveform from $source to $destination\"\n" port)
                (display "cp --no-preserve=mode,ownership -- \"$source\" \"$temporary\"\n" port)
                (display "chmod -- 0644 \"$temporary\"\n" port)
                (display "mv -- \"$temporary\" \"$destination\"\n" port)
                (display "echo \"installed waveform at $destination\"\n" port)))
            (chmod script #o555)
            (call-with-output-file params-script
              (lambda (port)
                (display "#!/bin/sh\n" port)
                (display "set -eu\n" port)
                (display "directory=/sys/module/rockchip_ebc/parameters\n" port)
                (display "if [ ! -d \"$directory\" ]; then\n" port)
                (display "  echo 'rockchip_ebc parameters are not available yet' >&2\n" port)
                (display "  exit 1\n" port)
                (display "fi\n" port)
                (display "set_parameter() {\n" port)
                (display "  name=$1\n" port)
                (display "  value=$2\n" port)
                (display "  path=$directory/$name\n" port)
                (display "  if [ -e \"$path\" ]; then\n" port)
                (display "    printf '%s' \"$value\" > \"$path\"\n" port)
                (display "  fi\n" port)
                (display "}\n" port)
                (display "set_parameter direct_mode 0\n" port)
                (display "set_parameter auto_refresh 1\n" port)
                (display "set_parameter refresh_threshold 60\n" port)
                (display "set_parameter split_area_limit 0\n" port)
                (display "set_parameter panel_reflection 1\n" port)
                (display "set_parameter prepare_prev_before_a2 0\n" port)
                (display "set_parameter dclk_select 0\n" port)))
            (chmod params-script #o555)
            (call-with-output-file config
              (lambda (port)
                (display "options rockchip_ebc direct_mode=0 auto_refresh=1 refresh_threshold=60 split_area_limit=0 panel_reflection=1 prepare_prev_before_a2=0 dclk_select=0\n" port)))))))
    (home-page "https://github.com/PNDeb/pinenote-debian-image")
    (synopsis "PineNote firmware helper scripts and EBC module options")
    (description
     "Install PineNote firmware support files without bundling private firmware
or waveform blobs.  The waveform helper copies a locally present waveform
partition or state-file into the firmware path expected by rockchip_ebc, and
the modprobe configuration records the PNDeb-derived conservative EBC module
options.")
    (license gpl3+)))
