(define-module (pinenote packages firmware)
  #:use-module (guix build-system trivial)
  #:use-module (guix gexp)
  #:use-module (guix licenses)
  #:use-module (guix packages))

(define-public pinenote-firmware-support
  (package
    (name "pinenote-firmware-support")
    (version "0.1.0")
    (source #f)
    (build-system trivial-build-system)
    (arguments
     (list
      #:modules '((guix build utils))
      #:builder
      #~(begin
          (use-modules (guix build utils))
           (let* ((out #$output)
                  (bin (string-append out "/bin"))
                  (modprobe (string-append out "/etc/modprobe.d"))
                  (waveform-script
                   (string-append bin "/pinenote-install-waveform"))
                  (brcm-script
                   (string-append bin "/pinenote-install-brcm-firmware"))
                  (params-script (string-append bin "/pinenote-apply-ebc-params"))
                  (config (string-append modprobe "/rockchip_ebc.conf")))
             (mkdir-p bin)
             (mkdir-p modprobe)
             (call-with-output-file waveform-script
               (lambda (port)
                 (display "#!/bin/sh\n" port)
                 (display "set -eu\n" port)
                 (display "primary_source=/dev/disk/by-partlabel/waveform\n" port)
                 (display "fallback_source=/state/firmware/ebc.wbf\n" port)
                 (display "destination=/lib/firmware/rockchip/ebc.wbf\n" port)
                 (display "destination_directory=/lib/firmware/rockchip\n" port)
                  (display "if [ -e \"$destination\" ] || [ -L \"$destination\" ]; then\n" port)
                  (display "  echo \"waveform already installed at $destination\"\n" port)
                  (display "  exit 0\n" port)
                  (display "fi\n" port)
                  (display "if [ -e \"$primary_source\" ]; then\n" port)
                  (display "  source=$primary_source\n" port)
                  (display "elif [ -e \"$fallback_source\" ]; then\n" port)
                  (display "  if [ ! -f \"$fallback_source\" ] || [ -L \"$fallback_source\" ]; then\n" port)
                  (display "    echo 'fallback waveform source is not a regular file' >&2\n" port)
                  (display "    exit 1\n" port)
                  (display "  fi\n" port)
                  (display "  source=$fallback_source\n" port)
                  (display "else\n" port)
                  (display "  echo 'no waveform source found; not loading EBC panel firmware' >&2\n" port)
                  (display "  exit 1\n" port)
                  (display "fi\n" port)
                  (display "if [ -L \"$destination_directory\" ]; then\n" port)
                  (display "  echo 'waveform destination directory is a symlink' >&2\n" port)
                  (display "  exit 1\n" port)
                  (display "fi\n" port)
                  (display "mkdir -p -- \"$destination_directory\"\n" port)
                  (display "if [ ! -d \"$destination_directory\" ] || [ -L \"$destination_directory\" ]; then\n" port)
                  (display "  echo 'waveform destination directory is not a real directory' >&2\n" port)
                  (display "  exit 1\n" port)
                  (display "fi\n" port)
                  (display "temporary=$(mktemp \"$destination_directory/.ebc.wbf.XXXXXX\")\n" port)
                  (display "trap 'rm -f -- \"$temporary\"' EXIT HUP INT TERM\n" port)
                  (display "echo \"copying waveform from $source to $destination\"\n" port)
                  (display "if [ -b \"$source\" ]; then\n" port)
                  (display "  dd if=\"$source\" of=\"$temporary\" bs=1k count=2048 status=none\n" port)
                 (display "else\n" port)
                 (display "  cp --no-preserve=mode,ownership -- \"$source\" \"$temporary\"\n" port)
                  (display "fi\n" port)
                  (display "chmod -- 0644 \"$temporary\"\n" port)
                  (display "mv -- \"$temporary\" \"$destination\"\n" port)
                  (display "trap - EXIT HUP INT TERM\n" port)
                  (display "echo \"installed waveform at $destination\"\n" port)))
             (chmod waveform-script #o555)
             (call-with-output-file brcm-script
               (lambda (port)
                 (display "#!/bin/sh\n" port)
                 (display "set -eu\n" port)
                  (display "source_directory=/state/firmware/brcm\n" port)
                  (display "destination_directory=/lib/firmware/brcm\n" port)
                  (display "if [ ! -d \"$source_directory\" ]; then\n" port)
                  (display "  echo 'no Broadcom firmware source directory found at /state/firmware/brcm; skipping' >&2\n" port)
                  (display "  exit 0\n" port)
                  (display "fi\n" port)
                  (display "if [ -L \"$source_directory\" ]; then\n" port)
                  (display "  echo 'Broadcom firmware source directory is a symlink' >&2\n" port)
                  (display "  exit 1\n" port)
                  (display "fi\n" port)
                  (display "if [ -L \"$destination_directory\" ]; then\n" port)
                  (display "  echo 'Broadcom firmware destination directory is a symlink' >&2\n" port)
                  (display "  exit 1\n" port)
                  (display "fi\n" port)
                  (display "mkdir -p -- \"$destination_directory\"\n" port)
                  (display "if [ ! -d \"$destination_directory\" ] || [ -L \"$destination_directory\" ]; then\n" port)
                  (display "  echo 'Broadcom firmware destination directory is not a real directory' >&2\n" port)
                  (display "  exit 1\n" port)
                  (display "fi\n" port)
                  (display "copy_file() {\n" port)
                  (display "  source=$1\n" port)
                  (display "  destination=$2\n" port)
                  (display "  source_path=$source_directory/$source\n" port)
                  (display "  destination_path=$destination_directory/$destination\n" port)
                  (display "  if [ -e \"$source_path\" ] && [ ! -e \"$destination_path\" ] && [ ! -L \"$destination_path\" ]; then\n" port)
                  (display "    if [ ! -f \"$source_path\" ] || [ -L \"$source_path\" ]; then\n" port)
                  (display "      echo \"Broadcom firmware source is not a regular file: $source\" >&2\n" port)
                  (display "      exit 1\n" port)
                  (display "    fi\n" port)
                  (display "    temporary=$(mktemp \"$destination_directory/.$destination.XXXXXX\")\n" port)
                  (display "    trap 'rm -f -- \"$temporary\"' EXIT HUP INT TERM\n" port)
                  (display "    cp --no-preserve=mode,ownership -- \"$source_path\" \"$temporary\"\n" port)
                  (display "    chmod -- 0644 \"$temporary\"\n" port)
                  (display "    mv -- \"$temporary\" \"$destination_path\"\n" port)
                  (display "    trap - EXIT HUP INT TERM\n" port)
                  (display "    echo \"installed Broadcom firmware $destination\"\n" port)
                  (display "  fi\n" port)
                 (display "}\n" port)
                  (display "copy_file fw_bcm43455c0_ag_cy.bin brcmfmac43455-sdio.bin\n" port)
                  (display "copy_file fw_bcm43455c0_ag_cy.bin brcmfmac43455-sdio.pine64,pinenote.bin\n" port)
                  (display "copy_file brcmfmac43455-sdio.AW-CM256SM.txt brcmfmac43455-sdio.txt\n" port)
                  (display "copy_file brcmfmac43455-sdio.AW-CM256SM.txt brcmfmac43455-sdio.pine64,pinenote.txt\n" port)
                  (display "copy_file nvram_ap6255_cy.txt brcmfmac43455-sdio.txt\n" port)
                  (display "copy_file nvram_ap6255_cy.txt brcmfmac43455-sdio.pine64,pinenote.txt\n" port)
                  (display "copy_file BCM4345C0.hcd BCM4345C0.hcd\n" port)))
             (chmod brcm-script #o555)
             (call-with-output-file params-script
               (lambda (port)
                (display "#!/bin/sh\n" port)
                (display "set -eu\n" port)
                (display "directory=/sys/module/rockchip_ebc/parameters\n" port)
                (display "if [ ! -d \"$directory\" ]; then\n" port)
                (display "  echo 'rockchip_ebc parameters are not available yet' >&2\n" port)
                (display "  exit 1\n" port)
                (display "fi\n" port)
                (display "set_parameter() {\n" port)
                (display "  name=$1\n" port)
                (display "  value=$2\n" port)
                (display "  path=$directory/$name\n" port)
                (display "  if [ -e \"$path\" ]; then\n" port)
                (display "    printf '%s' \"$value\" > \"$path\"\n" port)
                (display "  fi\n" port)
                (display "}\n" port)
                (display "set_parameter direct_mode 0\n" port)
                (display "set_parameter auto_refresh 1\n" port)
                (display "set_parameter refresh_threshold 60\n" port)
                (display "set_parameter split_area_limit 0\n" port)
                (display "set_parameter panel_reflection 1\n" port)
                (display "set_parameter prepare_prev_before_a2 0\n" port)
                (display "set_parameter dclk_select 0\n" port)))
            (chmod params-script #o555)
            (call-with-output-file config
              (lambda (port)
                (display "options rockchip_ebc direct_mode=0 auto_refresh=1 refresh_threshold=60 split_area_limit=0 panel_reflection=1 prepare_prev_before_a2=0 dclk_select=0\n" port)))))))
    (home-page "https://github.com/PNDeb/pinenote-debian-image")
    (synopsis "PineNote firmware helper scripts and EBC module options")
    (description
     "Install PineNote firmware support files without bundling private firmware
or waveform blobs.  The waveform helper copies the first 2 MiB of the local
waveform partition, or a state-file fallback, into the firmware path expected by
rockchip_ebc.  The Broadcom helper maps locally supplied AP6255/BCM43455
firmware and NVRAM files staged in the root file system under /state/firmware/brcm
into the names requested by brcmfmac on PineNote, preferring the public
AW-CM256SM NVRAM file when multiple NVRAM sources are supplied.  The
modprobe configuration records the PNDeb-derived conservative EBC module
options.")
    (license gpl3+)))
