;;; This entire file is the editable Workbench. Save it to author a successor.
(use-modules (rnrs bytevectors) (srfi srfi-1))
(define workbench-title "Source Workbench")
(define header-text ";;; Edited in Source Workbench\n")

(define (workbench-main receive! send! own-source)
  (define workspace #f)
  (define surface #f)
  (define snapshot #f)
  (define operation-sequence 0)
  (define action-sequence 0)
  (define (get object key) (assoc-ref object key))
  (define (need ok message) (unless ok (error message)))
  (define (text? text limit)
    (and (string? text) (not (string-index text #\nul))
         (<= (bytevector-length (string->utf8 text)) limit)))
  (define (positive-counter? n)
    (and (integer? n) (exact? n) (<= 1 n 2147483647)))
  (define (surface-counter? n)
    (and (integer? n) (exact? n) (<= 1 n 9007199254740991)))
  (define (author?) (equal? (get workspace "access") "author"))
  (define (action id label enabled)
    `(("id" . ,id) ("label" . ,label) ("enabled" . ,enabled)))
  (define (actions)
    (vector (action "read" "Read draft" #t)
            (action "save" "Save draft" #t)
            (action "preview" "Preview saved draft" (author?))
            (action "install" "Request installation" (author?))
            (action "successor" "Begin successor" #t)
            (action "insert-header" "Insert header" #t)
            (action "export" "Export installed revision" (author?))))
  (define (present request text status)
    ;; A full diagnostic plus its error-code prefix can exceed the surface cap.
    (let trim ()
      (unless (text? status 2048)
        (set! status (substring status 0 (- (string-length status) 1))) (trim)))
    (need (text? text 8192) "presentation too large")
    (send!
     (append
      `(("type" . "editor-present") ("protocol_version" . 1)
        ("title" . ,workbench-title) ("text" . ,text)
        ("status" . ,status) ("actions" . ,(actions)))
      (map (lambda (key) (cons key (get request key)))
           '("request_id" "action_id" "surface_handle"
             "surface_generation" "sequence")))))
  (define (operation type extras)
    (set! operation-sequence (+ operation-sequence 1))
    (need (positive-counter? operation-sequence) "workspace sequence exhausted")
    (send!
     (append `(("type" . ,type) ("protocol_version" . 1)
               ("grant_handle" . ,(get workspace "grant_handle"))
               ("grant_generation" . ,(get workspace "grant_generation"))
               ("operation_sequence" . ,operation-sequence)) extras))
    (let ((reply (receive!)))
      (need (and (list? reply) (equal? (get reply "protocol_version") 1)
                 (equal? (get reply "operation_sequence") operation-sequence))
            "uncorrelated workspace reply")
      (when (member (get reply "type")
                    '("workspace-snapshot" "workspace-saved" "workspace-install-result"))
        (set! snapshot (get reply "snapshot"))
        (need (and (list? snapshot) (text? (get snapshot "source") 8192))
              "invalid workspace snapshot"))
      reply))
  (define (version)
    `(("expected_version" . ,(get snapshot "workspace_version"))))
  (define (status reply fallback)
    (if (equal? (get reply "type") "workspace-failed")
        (string-append (get reply "code") ": " (get reply "diagnostic"))
        fallback))
  ;; Ready order is host-independent. No action is accepted before both grants.
  (let ready ()
    (unless (and workspace surface)
      (let ((message (receive!)))
        (need (and (list? message) (equal? (get message "protocol_version") 1))
              "expected v1 ready")
        (cond
         ((equal? (get message "type") "workspace-ready")
          (need (and (not workspace) (text? (get message "grant_handle") 128)
                     (positive-counter? (get message "grant_generation"))
                     (member (get message "access") '("author" "preview"))
                     (equal? (get message "max_source_bytes") 8192)
                     (equal? (get message "max_pending_operations") 1))
                "invalid workspace ready")
          (set! workspace message))
         ((equal? (get message "type") "editor-ready")
          (need (and (not surface) (text? (get message "surface_handle") 128)
                     (surface-counter? (get message "surface_generation"))
                     (equal? (get message "max_text_bytes") 8192)
                     (equal? (get message "max_actions") 8)) "invalid editor ready")
          (set! surface message))
         (else (error "unexpected ready message"))))
      (ready)))
  (let loop ()
    (let ((request (receive!)))
      (unless (eof-object? request)
        (need (and (list? request) (equal? (get request "type") "editor-action")
                   (equal? (get request "protocol_version") 1)
                   (surface-counter? (get request "request_id"))
                   (equal? (get request "surface_handle") (get surface "surface_handle"))
                   (equal? (get request "surface_generation") (get surface "surface_generation"))
                   (surface-counter? (get request "sequence"))
                   (> (get request "sequence") action-sequence)
                   (text? (get request "text") 8192)) "invalid editor action")
        (let ((id (get request "action_id")) (text (get request "text")))
          (need (or (positive? action-sequence) (equal? id "open")) "first action must open")
          (set! action-sequence (get request "sequence"))
          (cond
           ((member id '("open" "read"))
            (let ((reply (operation "workspace-read" '())))
              (present request (if snapshot (get snapshot "source") text)
                       (status reply "Draft loaded."))))
           ((equal? id "successor")
            (present request own-source "Executing source copied into editor. Edit and Save draft."))
           ((equal? id "insert-header")
            (let ((next (string-append header-text text)))
              (present request (if (text? next 8192) next text)
                       (if (text? next 8192) "Header inserted; save to persist." "Header exceeds source limit."))))
           ((not snapshot) (present request text "Read the draft before continuing."))
           ((equal? id "save")
            (let ((reply (operation "workspace-save" (append (version) `(("source" . ,text))))))
              (present request text (status reply "Draft saved."))))
           ((member id '("preview" "install" "export"))
            (cond
             ((not (author?)) (present request text "Preview access permits only read and save."))
             ((and (not (equal? id "export")) (not (equal? text (get snapshot "source"))))
              (present request text "Save or read the draft before this operation."))
             (else
              (let* ((type (cond ((equal? id "preview") "workspace-preview")
                                 ((equal? id "install") "workspace-install-propose")
                                 (else "workspace-export")))
                     (extras (cond ((equal? id "export") '())
                                   ((equal? id "install")
                                    (append (version) `(("expected_activation" . ,(get snapshot "activation_generation")))))
                                   (else (version))))
                     (reply (operation type extras)))
                (present request text
                         (status reply
                          (cond ((equal? id "preview") (get reply "diagnostic"))
                                ((equal? id "install") (string-append "Installation " (or (get reply "outcome") "not completed") "."))
                                (else (string-append "Installed revision " (or (get reply "exported_revision") "unavailable") " exported by host; edit buffer retained.")))))))))
           (else (present request text "Unknown action."))))
        (loop)))))
