;;; Generic editor form protocol. No workspace operations or action semantics.
(define-module (editor-surface)
  #:use-module (book-protocol)
  #:use-module (rnrs bytevectors)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-9)
  #:use-module (srfi srfi-13)
  #:export (editor-protocol-version max-editor-text-bytes max-editor-actions
            make-editor-message editor-message? editor-message-type
            editor-message-ref editor-message->object encode-editor-message
            decode-editor-payload decode-editor-frame
            make-editor-surface editor-surface? editor-surface-phase
            editor-surface-generation editor-surface-pending editor-surface-form
            editor-surface-new-view! editor-surface-action!
            editor-surface-present! editor-surface-fail! editor-surface-close!))

(define editor-protocol-version 1)
(define max-editor-text-bytes 8192)
(define max-editor-actions 8)
(define (fail reason) (throw 'editor-surface-error reason))
(define (copy value)
  (cond ((string? value) (string-copy value))
        ((pair? value) (cons (copy (car value)) (copy (cdr value))))
        ((vector? value) (list->vector (map copy (vector->list value))))
        (else value)))
(define (text! value maximum empty?)
  (unless (and (string? value) (or empty? (positive? (string-length value)))
               (<= (string-length value) maximum)
               (not (string-index value #\nul))
               (<= (bytevector-length (string->utf8 value)) maximum))
    (fail "invalid UTF-8 text length or NUL")))
(define (id! value)
  (text! value 64 #f)
  (unless (string-every (lambda (c)
                         (or (char<=? #\a c #\z) (char<=? #\A c #\Z)
                             (char<=? #\0 c #\9) (memv c '(#\_ #\-)))) value)
    (fail "action id must match [A-Za-z0-9_-]{1,64}")))
(define (integer! value minimum maximum)
  (unless (and (integer? value) (exact? value) (<= minimum value maximum))
    (fail "invalid integer")))
(define (fields! object fields)
  (unless (and (list? object) (= (length object) (length fields))
               (every (lambda (entry)
                        (and (pair? entry) (string? (car entry))
                             (member (car entry) fields))) object)
               (every (lambda (key) (= 1 (count (lambda (entry)
                                                   (equal? key (car entry))) object))) fields))
    (fail "fields must match closed schema")))
(define (ref object key) (assoc-ref object key))
(define identity-fields
  '("protocol_version" "request_id" "action_id" "surface_handle"
    "surface_generation" "sequence"))
(define (identity! object)
  (integer! (ref object "protocol_version") 1 1)
  (for-each (lambda (key) (integer! (ref object key) 1 max-safe-integer))
            '("request_id" "surface_generation" "sequence"))
  (text! (ref object "surface_handle") 128 #f)
  (id! (ref object "action_id")))
(define (actions! actions)
  (unless (and (vector? actions) (<= (vector-length actions) max-editor-actions))
    (fail "actions must be an array of at most eight objects"))
  (let ((seen '()))
    (for-each
     (lambda (action)
       (fields! action '("id" "label" "enabled"))
       (let ((id (ref action "id")))
         (id! id)
         (when (or (string=? id "open") (member id seen))
           (fail "duplicate or reserved action id"))
         (set! seen (cons id seen)))
       (text! (ref action "label") 128 #f)
       (unless (boolean? (ref action "enabled")) (fail "enabled must be boolean")))
     (vector->list actions))))

(define-record-type <editor-message>
  (%message object) editor-message? (object %object))
(define (editor-message->object message) (copy (%object message)))
(define (editor-message-ref message key) (copy (ref (%object message) key)))
(define (editor-message-type message) (editor-message-ref message "type"))
(define (make-editor-message object)
  (unless (list? object) (fail "message must be object"))
  (let ((type (ref object "type")))
    (cond
     ((equal? type "editor-ready")
      (fields! object '("type" "protocol_version" "surface_handle"
                       "surface_generation" "max_text_bytes" "max_actions"))
      (integer! (ref object "protocol_version") 1 1)
      (text! (ref object "surface_handle") 128 #f)
      (integer! (ref object "surface_generation") 1 max-safe-integer)
      (integer! (ref object "max_text_bytes") 8192 8192)
      (integer! (ref object "max_actions") 8 8))
     ((member type '("editor-action" "editor-present"))
      (fields! object (append '("type" "text") identity-fields
                             (if (equal? type "editor-present")
                                 '("title" "status" "actions") '())))
      (identity! object)
      (text! (ref object "text") max-editor-text-bytes #t)
      (when (equal? type "editor-present")
        (text! (ref object "title") 128 #t)
        (text! (ref object "status") 2048 #t)
        (actions! (ref object "actions"))))
     (else (fail "unknown editor message type"))))
  (%message (copy object)))
(define (encode-editor-message message) (encode-frame (%object message)))

;; Book Protocol has already validated the complete JSON, including escapes,
;; duplicate keys and arrays. Inspect raw numeric tokens outside strings: every
;; numeric field in this schema is an integer. Decoding first alone would lose
;; the distinction between 1, 1.0, 1e0 and underflowed decimal tokens.
(define (lexical-integers! text)
  (let loop ((i 0) (quoted? #f) (escape? #f))
    (when (< i (string-length text))
      (let ((c (string-ref text i)))
        (cond
         (escape? (loop (+ i 1) quoted? #f))
         ((and quoted? (char=? c #\\)) (loop (+ i 1) #t #t))
         ((char=? c #\") (loop (+ i 1) (not quoted?) #f))
         ((and (not quoted?) (or (char=? c #\-) (char<=? #\0 c #\9)))
          (let scan ((end (+ i 1)))
            (if (and (< end (string-length text))
                     (not (memv (string-ref text end)
                                '(#\space #\tab #\newline #\return #\, #\] #\}))))
                (scan (+ end 1))
                (begin
                  (when (string-any (lambda (c) (memv c '(#\. #\e #\E)))
                                    (substring text i end))
                    (fail "integer field requires lexical JSON integer"))
                  (loop end #f #f)))))
         (else (loop (+ i 1) quoted? #f)))))))
(define (project object payload direction)
  (lexical-integers! (utf8->string payload))
  (let ((message (make-editor-message object)))
    (unless (case direction
              ((book-to-authority) (equal? (editor-message-type message) "editor-present"))
              ((authority-to-book) (member (editor-message-type message)
                                          '("editor-ready" "editor-action")))
              (else #f))
      (fail "invalid direction"))
    message))
(define (decode-editor-payload payload direction)
  (project (decode-payload payload) payload direction))
(define (decode-editor-frame frame direction)
  (let* ((object (decode-frame frame))
         (payload (make-bytevector (- (bytevector-length frame) 4))))
    (bytevector-copy! frame 4 payload 0 (bytevector-length payload))
    (project object payload direction)))

(define-record-type <editor-surface>
  (%surface handle generation counter phase pending form)
  editor-surface?
  (handle surface-handle)
  (generation editor-surface-generation set-generation!)
  (counter surface-counter set-counter!)
  (phase editor-surface-phase set-phase!)
  (pending editor-surface-pending set-pending!)
  (form editor-surface-form set-form!))
(define (make-editor-surface handle)
  (text! handle 128 #f)
  (%surface (string-copy handle) 0 0 'closed #f #f))
(define (editor-surface-new-view! surface)
  (let* ((generation (+ 1 (editor-surface-generation surface)))
         (ready (make-editor-message
                 `(("type" . "editor-ready") ("protocol_version" . 1)
                   ("surface_handle" . ,(surface-handle surface))
                   ("surface_generation" . ,generation)
                   ("max_text_bytes" . 8192) ("max_actions" . 8)))))
    (set-generation! surface generation)
    (set-pending! surface #f) (set-form! surface #f)
    (set-phase! surface 'initial)
    ready))
(define (editor-surface-action! surface id text)
  (unless (and (memq (editor-surface-phase surface) '(initial idle))
               (not (editor-surface-pending surface)))
    (fail "surface is closed or busy"))
  (unless (if (eq? (editor-surface-phase surface) 'initial)
              (equal? id "open")
              (any (lambda (action) (and (equal? id (ref action "id"))
                                        (ref action "enabled")))
                   (vector->list (editor-message-ref (editor-surface-form surface) "actions"))))
    (fail "action was not enabled in the accepted form"))
  (let* ((counter (+ 1 (surface-counter surface)))
         (message (make-editor-message
                   `(("type" . "editor-action") ("protocol_version" . 1)
                     ("request_id" . ,counter) ("action_id" . ,id)
                     ("surface_handle" . ,(surface-handle surface))
                     ("surface_generation" . ,(editor-surface-generation surface))
                     ("sequence" . ,counter) ("text" . ,text)))))
    (set-counter! surface counter) (set-pending! surface message)
    (set-phase! surface 'pending)
    message))
(define (editor-surface-present! surface message)
  (let ((pending (editor-surface-pending surface)))
    (unless (and (editor-message? message)
                 (equal? (editor-message-type message) "editor-present")
                 pending
                 (every (lambda (key) (equal? (editor-message-ref pending key)
                                              (editor-message-ref message key))) identity-fields))
      (fail "unsolicited or mismatched presentation"))
    (set-form! surface message) (set-pending! surface #f)
    (set-phase! surface 'idle)
    message))
;; A trusted timeout/failure is correlated by the exact pending record, never by
;; an authored string. After an initial-open failure only open can be retried.
(define (editor-surface-fail! surface pending)
  (unless (and pending (eq? pending (editor-surface-pending surface)))
    (fail "failure does not name the pending action"))
  (set-pending! surface #f)
  (set-phase! surface (if (editor-surface-form surface) 'idle 'initial)))
(define (editor-surface-close! surface)
  (set-pending! surface #f) (set-form! surface #f) (set-phase! surface 'closed))
