;;; Real SQLite + deterministic task schedules. No process/sandbox claims.
(use-modules (workspace-protocol) (workspace-delegate) (book-workspace)
             (book-protocol) (ice-9 ftw) (rnrs bytevectors)
             (srfi srfi-1) (srfi srfi-64))
(set! test-log-to-file #f)
(define runner (test-runner-simple))
(test-runner-current runner)
(define roots '())
(define stores '())
(define (open-store root seed)
  (let ((store (open-workspace-store root seed #:environment "workbench-editor-v1-test")))
    (set! stores (cons store stores)) store))
(define (new-store)
  (let ((root (mkdtemp "/tmp/opencode/workspace-editor-test.XXXXXX")))
    (chmod root #o700) (set! roots (cons root roots))
    (open-store root "seed source")))
(define (refuses? thunk)
  (catch #t (lambda () (thunk) #f) (lambda _ #t)))
(define (request seq type . extra)
  ;; Exercise real framed decoder at the authority boundary, not only constructors.
  (decode-workspace-frame
   (encode-frame
    (append `(("type" . ,type) ("protocol_version" . 1)
              ("grant_handle" . "same-visible-handle") ("grant_generation" . 1)
              ("operation_sequence" . ,seq)) extra))))
(define owner (list 'private-owner))
(define (preview-ok source snapshot cancelled?)
  '((status . ok) (diagnostic . "preview fixture completed")))
(define* (delegate store #:optional (preview preview-ok) (access 'author) (who owner))
  (let ((d (make-workspace-delegate who store "same-visible-handle" 1 access preview)))
    (workspace-delegate-announce! d) d))
(define (drain d)
  (let ((task (workspace-delegate-take-task! d)))
    (workspace-delegate-complete! d (workspace-delegate-run-task! d task))))
(define (call d seq type . extra)
  (workspace-delegate-receive! d owner (apply request seq type extra))
  (drain d))
(define (save d seq version source)
  (call d seq "workspace-save" (cons "expected_version" version) (cons "source" source)))
(define (preview d seq version)
  (call d seq "workspace-preview" (cons "expected_version" version)))
(define (propose d seq version epoch)
  (call d seq "workspace-install-propose" (cons "expected_version" version)
        (cons "expected_activation" epoch)))
(define (type r) (assoc-ref r "type"))
(define (code r) (assoc-ref r "code"))
(define (snap store key) (assq-ref (workspace-snapshot store) key))
(define (revision-count store)
  ((@@ (book-workspace) scalar) ((@@ (book-workspace) store-database) store)
   "SELECT count(*) FROM revisions"))
(define (delegate-error-code thunk)
  (catch 'workspace-delegate-error (lambda () (thunk) #f)
    (lambda (_ code) code)))

(test-begin "workspace-delegate")
(let* ((store (new-store))
       (d (make-workspace-delegate owner store "same-visible-handle" 1 'author preview-ok)))
  (test-assert "unannounced grant rejects operation"
    (refuses? (lambda () (workspace-delegate-receive! d owner (request 1 "workspace-read")))))
  (workspace-delegate-announce! d)
  (test-assert "ready announcement is one-shot"
    (refuses? (lambda () (workspace-delegate-announce! d))))
  (for-each
   (lambda (replacement)
     (let ((bad (make-workspace-request
                 (map (lambda (entry)
                        (if (string=? (car entry) (car replacement)) replacement entry))
                      '(("type" . "workspace-read") ("protocol_version" . 1)
                        ("grant_handle" . "same-visible-handle") ("grant_generation" . 1)
                        ("operation_sequence" . 1))))))
       (test-assert "foreign grant handle/generation fails before sequence admission"
         (refuses? (lambda () (workspace-delegate-receive! d owner bad))))))
   '(("grant_handle" . "foreign") ("grant_generation" . 2)))
  (test-equal "rejections leave first sequence usable" "workspace-snapshot" (type (call d 1 "workspace-read"))))
(let* ((store (new-store)) (d (delegate store))
       (other-owner (list 'private-owner)) (b (delegate store preview-ok 'author other-owner)))
  (test-assert "copied owner label and leaked grant do not authorize"
    (refuses? (lambda () (workspace-delegate-receive! b owner (request 1 "workspace-read")))))
  (test-assert "untyped decoded alist is not dispatchable"
    (refuses? (lambda () (workspace-delegate-receive! d owner '(("type" . "workspace-read"))))))
  (test-equal "valid owner still has sequence one" "workspace-snapshot" (type (call d 1 "workspace-read")))
  (test-assert "reused sequence rejected"
    (refuses? (lambda () (workspace-delegate-receive! d owner (request 1 "workspace-read")))))
  (workspace-delegate-receive! d owner (request 2 "workspace-read"))
  (test-assert "one pending operation"
    (refuses? (lambda () (workspace-delegate-receive! d owner (request 3 "workspace-read")))))
  (let* ((task (workspace-delegate-take-task! d))
         (completion (workspace-delegate-run-task! d task)))
    (test-equal "taken slot cannot be taken again" #f (workspace-delegate-take-task! d))
    (test-assert "task cannot run twice" (refuses? (lambda () (workspace-delegate-run-task! d task))))
    (test-assert "foreign completion rejected" (refuses? (lambda () (workspace-delegate-complete! b completion))))
    (test-equal "completion produces correlated read" 2
      (assoc-ref (workspace-delegate-complete! d completion) "operation_sequence"))
    (test-assert "completion delivered once"
      (refuses? (lambda () (workspace-delegate-complete! d completion)))))
  (test-equal "busy rejection did not consume sequence" "workspace-snapshot" (type (call d 3 "workspace-read"))))

(let* ((store (new-store)) (d (delegate store))
       (last workspace-protocol-max-counter) (before (workspace-snapshot store)))
  ;; Private boundary setup avoids issuing billions of real read operations.
  ;; The final request and repeats still pass the actual framed wire decoder.
  ((@@ (workspace-delegate) set-next!) d last)
  (test-equal "pre-final older sequence still reports wrong sequence" 'wrong-sequence
    (delegate-error-code (lambda () (workspace-delegate-receive! d owner
                                     (request (- last 1) "workspace-read")))))
  (test-equal "final legal sequence completes normally" last
    (assoc-ref (call d last "workspace-read") "operation_sequence"))
  (for-each
   (lambda (sequence)
     (test-equal "exhaustion takes precedence over repeated/old sequence mismatch" 'sequence-exhausted
       (delegate-error-code (lambda () (workspace-delegate-receive! d owner
                                        (request sequence "workspace-read"))))))
   (list last 1))
  (test-equal "exhausted requests queue no work" #f (workspace-delegate-take-task! d))
  (test-equal "exhausted requests mutate no durable state" before (workspace-snapshot store))
  (test-equal "fresh endpoint can resume at sequence one" 1
    (assoc-ref (call (delegate store) 1 "workspace-read") "operation_sequence")))

(let* ((store (new-store)) (d (delegate store)) (seed (snap store 'active-revision)))
  (test-equal "save commits actual draft" "workspace-saved" (type (save d 1 0 "candidate")))
  (test-equal "save never installs" seed (snap store 'active-revision))
  (test-equal "no preview cannot propose" "preview-required-for-this-draft" (code (propose d 2 1 0)))
  (test-equal "preview succeeds" "workspace-previewed" (type (preview d 3 1)))
  (test-equal "propose creates no sandbox reply yet" #f (propose d 4 1 0))
  (test-equal "proposal awaits trusted UI" 'confirming (workspace-delegate-phase d))
  (test-equal "proposal does not install" seed (snap store 'active-revision))
  (let ((p (workspace-delegate-proposal d)))
    (test-equal "private proposal captures source/version/epoch" '(1 "candidate" 0)
      (map (lambda (k) (assq-ref (workspace-proposal-snapshot p) k))
           '(workspace-version source activation-generation)))
    (test-assert "unrelated trusted owner cannot confirm"
      (refuses? (lambda () (workspace-delegate-confirm! d (list 'private-owner) p))))
    (test-equal "explicit Cancel receipt" "cancelled"
      (assoc-ref (workspace-delegate-cancel! d owner p) "outcome"))
    (test-assert "cancelled proposal cannot later confirm"
      (refuses? (lambda () (workspace-delegate-confirm! d owner p)))))
  (test-equal "cancel consumes preview authorization" "preview-required-for-this-draft" (code (propose d 5 1 0)))
  (preview d 6 1) (propose d 7 1 0)
  (workspace-delegate-confirm! d owner (workspace-delegate-proposal d))
  (test-equal "confirmation scheduling alone does not install" seed (snap store 'active-revision))
  (test-equal "confirmed transaction installs" "installed" (assoc-ref (drain d) "outcome"))
  (test-equal "active revision is exact candidate digest" (snap store 'source-digest) (snap store 'active-revision))
  (test-equal "epoch advances exactly once" 1 (snap store 'activation-generation))
  (test-equal "old seed is retained predecessor" seed (snap store 'previous-revision))
  (let ((expected (workspace-snapshot store)) (root (car roots)))
    (workspace-delegate-close! d) (close-workspace-store! store)
    (set! store (open-store root "replacement seed ignored"))
    (test-equal "fresh store open recovers installed revision and draft" expected (workspace-snapshot store)))
  (set! d (delegate store))
  (save d 1 1 "broken (")
  (workspace-delegate-retire-view! d)
  (workspace-rollback! store 1)
  (test-equal "trusted rollback works with broken draft" seed (snap store 'active-revision))
  (test-equal "rollback preserves broken draft" "broken (" (snap store 'source))
  (workspace-activate! store (snap store 'seed-revision) 2)
  (test-equal "permanent seed recovery advances epoch" 3 (snap store 'activation-generation))
  (let* ((before (workspace-snapshot store)) (count-before (revision-count store))
         (exported (call d 2 "workspace-export"))
         (artifact (decode-payload (string->utf8 (assoc-ref exported "artifact")))))
    (test-equal "export selects seed, not broken draft" (workspace-export store seed)
      (assoc-ref exported "artifact"))
    (test-equal "export explicitly identifies captured installed revision" seed
      (assoc-ref exported "exported_revision"))
    (test-equal "decoded artifact revision matches exported revision"
      (assoc-ref exported "exported_revision") (assoc-ref artifact "revision"))
    (test-equal "decoded artifact source is installed source" "seed source" (assoc-ref artifact "source"))
    (test-equal "export retains separately identified draft metadata" (snap store 'source-digest)
      (assoc-ref exported "source_digest"))
    (test-assert "draft identity is distinct from exported revision"
      (not (equal? (assoc-ref exported "source_digest") (assoc-ref exported "exported_revision"))))
    (test-equal "export mutates no draft or installation field" before (workspace-snapshot store))
    (test-equal "export does not seal draft or consume a revision slot" count-before (revision-count store))
    (test-assert "broken draft remains unsealed after export"
      (refuses? (lambda () (workspace-revision-source store (snap store 'source-digest)))))))

(let* ((store (new-store)) (root (car roots)) (d (delegate store)))
  (save d 1 0 "sealed but uninstalled") (preview d 2 1) (propose d 3 1 0)
  (workspace-delegate-confirm! d owner (workspace-delegate-proposal d))
  (let* ((before (workspace-snapshot store)) (count-before (revision-count store))
         (candidate (assq-ref before 'source-digest)) (commits 0)
         (result
          (parameterize
              (((@@ (book-workspace) commit-fault-hook)
                (lambda ()
                  (set! commits (+ commits 1))
                  ;; Seal is committed by now. Fail after activation writes but
                  ;; before its COMMIT, exercising real transaction rollback.
                  (when (= commits 2) (throw 'injected-activation-failure)))))
            (drain d))))
    (test-equal "confirmation attempted independent seal and activation transactions" 2 commits)
    (test-equal "post-seal activation failure reports no installation" "workspace-operation-failed" (code result))
    (test-equal "failed activation leaves all draft/pointer/epoch fields unchanged" before (workspace-snapshot store))
    (test-equal "successful seal still consumes one retained quota slot" (+ count-before 1) (revision-count store))
    (test-equal "uninstalled sealed source remains readable by its immutable revision" "sealed but uninstalled"
      (workspace-revision-source store candidate))
    (workspace-delegate-close! d) (close-workspace-store! store)
    (set! store (open-store root "ignored"))
    (test-equal "reopen preserves failed activation's unchanged draft and pointers" before (workspace-snapshot store))
    (test-equal "reopen preserves independently committed seal/quota slot" (+ count-before 1) (revision-count store))
    (test-equal "reopen recovers retained uninstalled source" "sealed but uninstalled"
      (workspace-revision-source store candidate))))

(let* ((store (new-store)) (second (open-store (car roots) "ignored"))
       (a (delegate store)) (b (delegate second)))
  (save a 1 0 "winner")
  (test-equal "second connection loses real CAS" "stale-workspace-version" (code (save b 1 0 "loser")))
  (test-equal "CAS loser preserves actual source" "winner" (snap second 'source))
  (preview a 2 1)
  (test-equal "other endpoint cannot borrow preview ticket" "preview-required-for-this-draft" (code (propose b 2 1 0)))
  (save a 3 1 "winner")
  (test-equal "identical save retires preview" "preview-required-for-this-draft" (code (propose a 4 2 0)))
  (preview a 5 2)
  (call a 6 "workspace-read")
  (test-equal "open/read retires preview" "preview-required-for-this-draft" (code (propose a 7 2 0)))
  (preview a 8 2) (propose a 9 2 0)
  (let ((p (workspace-delegate-proposal a)))
    (workspace-save! second 2 "competing")
    (workspace-delegate-confirm! a owner p)
    (test-equal "save during confirmation prevents install" "workspace-conflict" (code (drain a))))
  (test-equal "failed install leaves epoch" 0 (snap store 'activation-generation))
  ;; Exact backend transaction invoked by confirm rejects a competing save
  ;; after sealing; no successful preview can bypass this storage constraint.
  (let* ((count-before (revision-count store)) (sealed (workspace-seal! store 3)))
    (workspace-save! second 3 "after seal")
    (let ((after-save (workspace-snapshot store)))
      (test-assert "seal/install race CAS refuses"
        (refuses? (lambda () (workspace-activate-draft! store sealed 3 0))))
      (test-equal "failed raced activation preserves competing draft and pointers" after-save (workspace-snapshot store))
      (test-equal "raced activation retains separately sealed quota slot" (+ count-before 1) (revision-count store))
      (test-equal "raced activation retains old immutable source" "competing" (workspace-revision-source store sealed))))
  (preview a 10 4) (propose a 11 4 0)
  (workspace-activate! second (snap second 'seed-revision) 0)
  (workspace-delegate-confirm! a owner (workspace-delegate-proposal a))
  (test-equal "activation ABA/same-source epoch cannot reuse proposal" "activation-conflict" (code (drain a))))

(let* ((store (new-store)) (d #f) (cancelled #f))
  (set! d (delegate store
             (lambda (source snapshot cancelled?)
               (workspace-delegate-retire-view! d)
               (set! cancelled (cancelled?))
               (test-equal "retired task still owns slot" 'retiring (workspace-delegate-phase d))
               (test-assert "retired executing task prevents overlapping save"
                 (refuses? (lambda () (workspace-delegate-receive! d owner
                                       (request 2 "workspace-save" '("expected_version" . 0) '("source" . "overlap"))))))
               '((status . ok)))))
  (test-equal "retired preview completion suppressed" #f (preview d 1 0))
  (test-assert "callback sees cancellation" cancelled)
  (test-equal "retired slot returns to ready after completion" 'ready (workspace-delegate-phase d))
  (test-equal "retired preview never authorizes install" "preview-required-for-this-draft" (code (propose d 2 0 0))))
(let* ((store (new-store)) (d (delegate store)))
  (save d 1 0 "successor")
  (let ((successor (workspace-seal! store 1)) (seed (snap store 'seed-revision)))
    (preview d 2 1) (propose d 3 1 0)
    (workspace-activate! store successor 0)
    (workspace-activate! store seed 1)
    (workspace-delegate-confirm! d owner (workspace-delegate-proposal d))
    (test-equal "real R0-R1-R0 ABA invalidates proposal" "activation-conflict" (code (drain d)))
    (test-equal "ABA failure preserves current revision/epoch" (list seed 2)
      (list (snap store 'active-revision) (snap store 'activation-generation))))
  (preview d 4 1)
  (workspace-save! store 1 "temporary")
  (workspace-save! store 2 "successor")
  (test-equal "draft ABA invalidates ticket despite identical bytes" "preview-required-for-this-draft" (code (propose d 5 3 2))))
(let* ((store (new-store)) (d (delegate store)))
  (workspace-delegate-receive! d owner (request 1 "workspace-save" '("expected_version" . 0) '("source" . "not written")))
  (let ((task (workspace-delegate-take-task! d)))
    (workspace-delegate-close! d)
    (test-equal "close before execution suppresses completion" #f
      (workspace-delegate-complete! d (workspace-delegate-run-task! d task))))
  (test-equal "close before execution prevents write" 0 (snap store 'workspace-version))
  (test-equal "close idempotent" 'already-closed (workspace-delegate-close! d)))
(let* ((store (new-store)) (d (delegate store)))
  (workspace-delegate-receive! d owner (request 1 "workspace-save" '("expected_version" . 0) '("source" . "committed")))
  (let* ((task (workspace-delegate-take-task! d)) (done (workspace-delegate-run-task! d task)))
    (workspace-delegate-close! d)
    (test-equal "close after commit suppresses stale receipt" #f (workspace-delegate-complete! d done)))
  (test-equal "lost receipt does not undo actual commit" "committed" (snap store 'source))
  (test-equal "fresh endpoint reads exact committed version" 1
    (assoc-ref (assoc-ref (call (delegate store) 1 "workspace-read") "snapshot") "workspace_version")))
(let* ((store (new-store)) (d (delegate store)))
  (preview d 1 0) (propose d 2 0 0)
  (let ((p (workspace-delegate-proposal d)))
    (workspace-delegate-retire-view! d)
    (test-assert "view retirement invalidates confirmation object"
      (refuses? (lambda () (workspace-delegate-confirm! d owner p)))))
  (preview d 3 0) (propose d 4 0 0)
  (workspace-delegate-confirm! d owner (workspace-delegate-proposal d))
  (workspace-delegate-close! d)
  (test-equal "close discards queued confirmed installation" #f (workspace-delegate-take-task! d))
  (test-equal "queued confirmed candidate was never installed" 0 (snap store 'activation-generation)))

(let* ((live (new-store)) (scratch (new-store)) (d (delegate scratch preview-ok 'preview)))
  (test-equal "preview grant may save disposable source" "workspace-saved" (type (save d 1 0 "scratch only")))
  (test-equal "live source unchanged" "seed source" (snap live 'source))
  (test-equal "preview reads its own saved source" "scratch only"
    (assoc-ref (assoc-ref (call d 2 "workspace-read") "snapshot") "source"))
  (test-equal "recursive preview denied" "access-denied" (code (preview d 3 1)))
  (test-equal "preview cannot propose installation" "access-denied" (code (propose d 4 1 0)))
  (test-equal "preview cannot export live installation" "access-denied" (code (call d 5 "workspace-export"))))
(let* ((store (new-store))
       (d (delegate store (lambda (source snapshot cancelled?)
                            (workspace-save! store 0 "new writer")
                            '((status . ok))))))
  (test-equal "concurrent draft change invalidates callback success" "workspace-changed-during-preview" (code (preview d 1 0))))
(let* ((store (new-store)) (d (delegate store (lambda args '((status . failed) (diagnostic . "syntax failure"))))))
  (test-equal "callback failure is correlated" "preview-failed" (code (preview d 1 0)))
  (test-equal "callback failure preserves active" (snap store 'seed-revision) (snap store 'active-revision)))

(let* ((store (new-store)) (d (delegate store)))
  (do ((i 1 (+ i 1))) ((= i 128))
    (workspace-save! store (- i 1) (number->string i))
    (workspace-seal! store i))
  (save d 1 127 "candidate beyond capacity")
  (preview d 2 128) (propose d 3 128 0)
  (workspace-delegate-confirm! d owner (workspace-delegate-proposal d))
  (test-equal "real revision quota failure survives delegate" "revision-quota-exhausted" (code (drain d)))
  (test-equal "quota install failure leaves active pointer" (snap store 'seed-revision) (snap store 'active-revision))
  (test-equal "save remains available at quota" "workspace-saved" (type (save d 4 128 "saved beyond quota")))
  (test-equal "export remains available at quota" "workspace-exported" (type (call d 5 "workspace-export")))
  (workspace-delegate-retire-view! d)
  (workspace-rollback! store 0)
  (workspace-activate! store (snap store 'seed-revision) 1)
  (test-equal "rollback and seed recovery available at quota" 2 (snap store 'activation-generation)))
(let* ((store (new-store)) (d (delegate store)) (source (make-string 8192 (integer->char 1))))
  (test-assert "maximum saved reply fits real encoder"
    (<= (bytevector-length (encode-frame (save d 1 0 source))) 65540))
  (preview d 2 1) (propose d 3 1 0)
  (workspace-delegate-confirm! d owner (workspace-delegate-proposal d)) (drain d)
  (test-assert "maximum installed export fits real encoder"
    (<= (bytevector-length (encode-frame (call d 4 "workspace-export"))) 65540)))

(for-each close-workspace-store! stores)
(define (remove-tree root)
  (for-each (lambda (name) (delete-file (string-append root "/" name)))
            (scandir root (lambda (name) (not (member name '("." ".."))))))
  (rmdir root))
(for-each remove-tree roots)
(test-end "workspace-delegate")
(exit (if (zero? (test-runner-fail-count runner)) 0 1))
