;;; Closed, shallow Workspace Protocol 1 request schemas. Framing and JSON
;;; remain Book Protocol's responsibility; raw integer spelling is checked here.
(define-module (workspace-protocol)
  #:use-module (book-protocol)
  #:use-module (rnrs bytevectors)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-9)
  #:use-module (srfi srfi-13)
  #:export (workspace-protocol-version workspace-protocol-max-counter
            workspace-protocol-max-source-bytes workspace-request?
            make-workspace-request workspace-request-type
            workspace-request-sequence workspace-request-field
            encode-workspace-request decode-workspace-payload
            decode-workspace-frame))

(define workspace-protocol-version 1)
(define workspace-protocol-max-counter 2147483647)
(define workspace-protocol-max-source-bytes 8192)
(define common-fields
  '("type" "protocol_version" "grant_handle" "grant_generation" "operation_sequence"))
(define schemas
  '(("workspace-read")
    ("workspace-save" "expected_version" "source")
    ("workspace-preview" "expected_version")
    ("workspace-install-propose" "expected_version" "expected_activation")
    ("workspace-export")))

(define (reject code) (throw 'workspace-protocol-error code))
(define (copy-value value) (if (string? value) (string-copy value) value))
(define (copy-object object)
  (map (lambda (entry) (cons (string-copy (car entry)) (copy-value (cdr entry)))) object))
(define-record-type <workspace-request>
  (%make-request object) workspace-request?
  (object request-object))
(define (workspace-request-field request key)
  (unless (workspace-request? request) (reject 'typed-request-required))
  (copy-value (assoc-ref (request-object request) key)))
(define (workspace-request-type request) (workspace-request-field request "type"))
(define (workspace-request-sequence request)
  (workspace-request-field request "operation_sequence"))

(define (text! value minimum maximum)
  (unless (and (string? value) (<= minimum (string-length value) maximum)
               (string-every (lambda (c)
                               (let ((n (char->integer c)))
                                 (and (> n 0) (<= n #x10ffff)
                                      (not (<= #xd800 n #xdfff))))) value)
               (<= minimum (bytevector-length (string->utf8 value)) maximum))
    (reject 'invalid-text)))
(define (integer! value minimum maximum)
  (unless (and (exact-integer? value) (<= minimum value maximum))
    (reject 'invalid-integer)))
(define (validate! object)
  (unless (and (list? object) (<= (length object) 7)
               (every (lambda (entry) (and (pair? entry) (string? (car entry)))) object))
    (reject 'invalid-object))
  (let* ((type (assoc-ref object "type"))
         (schema (and (string? type) (assoc type schemas)))
         (fields (and schema (append common-fields (cdr schema)))))
    (unless (and fields
                 (equal? (sort (map car object) string<?) (sort fields string<?)))
      (reject 'invalid-fields))
    (integer! (assoc-ref object "protocol_version") 1 1)
    (text! (assoc-ref object "grant_handle") 1 128)
    (for-each (lambda (key)
                (integer! (assoc-ref object key) 1 workspace-protocol-max-counter))
              '("grant_generation" "operation_sequence"))
    (for-each (lambda (key)
                (when (member key fields)
                  (integer! (assoc-ref object key) 0 workspace-protocol-max-counter)))
              '("expected_version" "expected_activation"))
    (when (member "source" fields)
      (text! (assoc-ref object "source") 0 workspace-protocol-max-source-bytes))
    object))

(define (make-workspace-request object)
  ;; Trusted/sandbox-library constructor. Untrusted wire dispatch must retain
  ;; the raw payload and call decode-workspace-payload, never this constructor.
  (validate! object)
  (%make-request (copy-object object)))
(define (encode-workspace-request request)
  (unless (workspace-request? request) (reject 'typed-request-required))
  (encode-frame (request-object request)))

;;; Like book-state-protocol's scalar-token-evidence: JSON has already been
;;; decoded with ordered members and exact shallow shape checked. Track each
;;; value's lexical spelling in that order, including escaped/reordered keys.
;;; This is not another JSON parser and never accepts data the codec rejected.
(define (white? c) (memv c '(#\space #\tab #\newline #\return)))
(define (skip-white text start)
  (let loop ((i start))
    (if (and (< i (string-length text)) (white? (string-ref text i)))
        (loop (+ i 1)) i)))
(define (string-end text start)
  (let loop ((i start) (escaped? #f))
    (when (>= i (string-length text)) (reject 'invalid-token-evidence))
    (let ((c (string-ref text i)))
      (cond (escaped? (loop (+ i 1) #f))
            ((char=? c #\\) (loop (+ i 1) #t))
            ((char=? c #\") (+ i 1))
            (else (loop (+ i 1) #f))))))
(define (scalar-end text start)
  (let loop ((i start))
    (if (or (= i (string-length text)) (white? (string-ref text i))
            (memv (string-ref text i) '(#\, #\})))
        i (loop (+ i 1)))))
(define (lexical-integers! text object)
  (let loop ((i (+ 1 (skip-white text 0))) (entries object))
    (if (null? entries)
        (unless (= (skip-white text i) (string-length text))
          (reject 'invalid-token-evidence))
        (let* ((key-start (skip-white text i))
               (key-end (string-end text (+ key-start 1)))
               (colon (skip-white text key-end))
               (start (skip-white text (+ colon 1)))
               (value (cdar entries))
               (end (if (string? value) (string-end text (+ start 1))
                        (scalar-end text start)))
               (delimiter (skip-white text end)))
          (unless (and (char=? (string-ref text key-start) #\")
                       (char=? (string-ref text colon) #\:)
                       (char=? (string-ref text delimiter)
                               (if (null? (cdr entries)) #\} #\,)))
            (reject 'invalid-token-evidence))
          (when (number? value)
            (when (string-any (lambda (c) (memv c '(#\. #\e #\E)))
                              (substring text start end))
              (reject 'nonlexical-integer)))
          (loop (+ delimiter 1) (cdr entries))))))
(define (decode-workspace-payload payload)
  (let ((object (decode-payload payload)))
    (validate! object)
    (lexical-integers! (utf8->string payload) object)
    (%make-request (copy-object object))))
(define (decode-workspace-frame frame)
  ;; decode-frame validates exact length/header before retaining payload bytes.
  (decode-frame frame)
  (let ((payload (make-bytevector (- (bytevector-length frame) 4))))
    (bytevector-copy! frame 4 payload 0 (bytevector-length payload))
    (decode-workspace-payload payload)))
