;;; Fixed child transport. Authored source executes only inside this child.
;;; Isolation belongs to the prepared sandbox, not to Scheme's module system.
(use-modules (book-protocol)
             (book-protocol blocking-io)
             (ice-9 ftw)
             (rnrs bytevectors)
             (rnrs io ports)
             (srfi srfi-1)
             (srfi srfi-13))

(define (require! condition message)
  (unless condition (error message)))

(define (text? value limit)
  (and (string? value) (positive? (string-length value))
       (not (string-index value #\nul))
       (<= (bytevector-length (string->utf8 value)) limit)))

(define (fields? object names)
  (and (list? object) (= (length object) (length names))
       (every (lambda (name) (assoc name object)) names)))

(define (integer-spellings! payload)
  ;; All numbers in this transport's v1 messages are integer counters. Scan
  ;; outside strings only; the shared codec still owns JSON grammar/UTF-8.
  (let ((text (utf8->string payload)))
    (let loop ((i 0) (quoted? #f) (escaped? #f))
      (when (< i (string-length text))
        (let ((c (string-ref text i)))
          (cond
           (escaped? (loop (+ i 1) quoted? #f))
           ((and quoted? (char=? c #\\)) (loop (+ i 1) #t #t))
           ((char=? c #\") (loop (+ i 1) (not quoted?) #f))
           ((and (not quoted?) (or (char-numeric? c) (char=? c #\-)))
            (let scan ((end (+ i 1)))
              (if (and (< end (string-length text))
                       (let ((next (string-ref text end)))
                         (or (char-numeric? next)
                             (memv next '(#\- #\+ #\. #\e #\E)))))
                  (scan (+ end 1))
                  (begin
                    (require!
                     (not (string-any (lambda (x) (memv x '(#\. #\e #\E #\+)))
                                      (substring text i end)))
                     "wire counters require lexical JSON integers")
                    (loop end #f #f)))))
           (else (loop (+ i 1) quoted? #f))))))))

(define (receive-frame port)
  (let ((header ((@@ (book-protocol blocking-io) read-exactly) port 4 #t)))
    (if (eof-object? header) header
        (let* ((payload ((@@ (book-protocol blocking-io) read-exactly)
                         port (frame-payload-length header) #f))
               (message (decode-payload payload)))
          (integer-spellings! payload)
          message))))

(define (native-descriptors!)
  (setpgid 0 0)
  (kill (getpid) SIGSTOP)
  (require! (eq? (stat:type (stat 0)) 'socket) "native donation is not a socket")
  (dup2 0 3)
  (let ((null (open-fdes "/dev/null" O_RDONLY)))
    (dup2 null 0) (close-fdes null))
  (for-each
   (lambda (name)
     (let ((fd (string->number name)))
       (when (and fd (> fd 3))
         (catch 'system-error (lambda () (close-fdes fd)) (lambda _ #f)))))
   (scandir "/proc/self/fd"))
  (for-each (lambda (fd) (fcntl fd F_SETFD 0)) '(0 1 2 3)))

(define (read-source path)
  (let ((port (open-file path "rb")))
    (dynamic-wind
      (lambda () #t)
      (lambda ()
        (require! (eq? (stat:type (stat port)) 'regular) "source is not regular")
        (let ((bytes (get-bytevector-n port 8193)))
          (require! (and (bytevector? bytes)
                         (<= 1 (bytevector-length bytes) 8192))
                    "source must be 1..8192 bytes")
          (let ((text (utf8->string bytes)))
            (require! (and (not (string-index text #\nul))
                           (bytevector=? bytes (string->utf8 text)))
                      "source must be UTF-8 without NUL")
            text)))
      (lambda () (close-port port)))))

(define (run path)
  (require! (equal? (getenv "BOOK_SESSION_FD") "3") "BOOK_SESSION_FD must be 3")
  (require! (eq? (stat:type (stat 3)) 'socket) "FD 3 is not a socket")
  (let ((port (fdopen 3 "r+0")) (source (read-source path)))
    (require! (and (= (getsockopt port SOL_SOCKET SO_TYPE) SOCK_STREAM)
                   (= (vector-ref (getsockname port) 0) AF_UNIX)
                   (= (vector-ref (getpeername port) 0) AF_UNIX))
              "FD 3 must be a connected Unix stream")
    (write-frame port '(("type" . "hello") ("version" . 1)))
    (let ((init (receive-frame port)))
      (require!
       (and (fields? init '("type" "version" "grant_count" "surface_handle"
                           "surface_generation" "max_pending_requests"
                           "max_present_text_bytes"))
            (equal? (assoc-ref init "type") "initialize")
            (equal? (assoc-ref init "version") 1)
            (equal? (assoc-ref init "grant_count") 1)
            (text? (assoc-ref init "surface_handle") 96)
            (equal? (assoc-ref init "surface_generation") 1)
            (equal? (assoc-ref init "max_pending_requests") 4)
            (equal? (assoc-ref init "max_present_text_bytes") 4096))
       "unexpected ordinary initialize"))
    (let ((program (make-fresh-user-module)))
      (save-module-excursion
       (lambda ()
         (set-current-module program)
         (call-with-input-string source
           (lambda (input)
             (let loop ()
               (let ((form (read input)))
                 (unless (eof-object? form) (eval form program) (loop))))))))
      (let ((entry (module-ref program 'workbench-main #f)))
        (require! (procedure? entry)
                  "source must define (workbench-main receive! send! own-source)")
        (entry (lambda () (receive-frame port))
               (lambda (message) (write-frame port message))
               (string-copy source))))
    (close-port port)))

(sigaction SIGPIPE SIG_IGN)
(let ((args (cdr (command-line))))
  (cond
   ((equal? args '("--sandbox")) (run "/book/program.scm"))
   ((and (= (length args) 4) (string=? (car args) "--trusted-native-fixture"))
    (native-descriptors!)
    (execl (caddr args) (caddr args) "--no-auto-compile"
           "-L" (cadddr args) (car (command-line)) "--native-run" (cadr args)))
   ((and (= (length args) 2) (string=? (car args) "--native-run"))
    (chdir (dirname (cadr args))) (run (cadr args)))
   (else (error "runner requires --sandbox or explicit trusted native fixture"))))
