;;; One endpoint-bound workspace authority. The session owner schedules opaque
;;; tasks; storage/preview execution occurs outside the transition mutex.
(define-module (workspace-delegate)
  #:use-module (workspace-protocol)
  #:use-module (book-workspace)
  #:use-module (ice-9 threads)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-9)
  #:use-module (srfi srfi-13)
  #:export (make-workspace-delegate workspace-delegate?
            workspace-delegate-announce! workspace-delegate-receive!
            workspace-delegate-take-task! workspace-delegate-run-task!
            workspace-delegate-complete! workspace-delegate-proposal
            workspace-proposal? workspace-proposal-snapshot workspace-proposal-sequence
            workspace-delegate-confirm! workspace-delegate-cancel!
            workspace-delegate-retire-view! workspace-delegate-close!
            workspace-delegate-phase))

(define (reject code) (throw 'workspace-delegate-error code))
(define (own value)
  (cond ((string? value) (string-copy value))
        ((pair? value) (cons (own (car value)) (own (cdr value))))
        (else value)))
(define-record-type <delegate>
  (%make-delegate owner store handle generation access preview mutex announced?
                  closed? epoch next task proposal ticket)
  workspace-delegate?
  (owner delegate-owner) (store delegate-store)
  (handle delegate-handle) (generation delegate-generation)
  (access delegate-access) (preview delegate-preview) (mutex delegate-mutex)
  (announced? delegate-announced? set-announced!)
  (closed? delegate-closed? set-closed!)
  (epoch delegate-epoch set-epoch!) (next delegate-next set-next!)
  (task delegate-task set-task!) (proposal delegate-proposal set-proposal!)
  (ticket delegate-ticket set-ticket!))
(define-record-type <task>
  (%make-task delegate epoch request kind snapshot state)
  task?
  (delegate task-delegate) (epoch task-epoch) (request task-request)
  (kind task-kind) (snapshot task-snapshot)
  (state task-state set-task-state!))
(define-record-type <completion>
  (%make-completion task outcome) completion?
  (task completion-task) (outcome completion-outcome))
(define-record-type <proposal>
  (%make-proposal delegate epoch request snapshot)
  workspace-proposal?
  (delegate proposal-delegate) (epoch proposal-epoch)
  (request proposal-request) (snapshot proposal-snapshot))
(define (workspace-proposal-snapshot proposal)
  (unless (workspace-proposal? proposal) (reject 'invalid-proposal))
  (own (proposal-snapshot proposal)))
(define (workspace-proposal-sequence proposal)
  (unless (workspace-proposal? proposal) (reject 'invalid-proposal))
  (workspace-request-sequence (proposal-request proposal)))
(define (locked delegate thunk)
  (unless (workspace-delegate? delegate) (reject 'invalid-delegate))
  (with-mutex (delegate-mutex delegate) (thunk)))
(define (owner! delegate owner)
  (unless (eq? owner (delegate-owner delegate)) (reject 'wrong-owner)))
(define (live! delegate)
  (when (delegate-closed? delegate) (reject 'closed)))
(define (field request key) (workspace-request-field request key))
(define (identity snapshot)
  (map (lambda (key) (assq-ref snapshot key))
       '(workspace-version source-digest activation-generation)))
(define (wire-snapshot snapshot)
  (map (lambda (pair) (cons (cdr pair) (own (assq-ref snapshot (car pair)))))
       '((workspace-version . "workspace_version") (source . "source")
         (source-digest . "source_digest") (active-revision . "active_revision")
         (previous-revision . "previous_revision")
         (activation-generation . "activation_generation"))))
(define (reply type request . fields)
  (append `(("type" . ,type) ("protocol_version" . 1)
            ("operation_sequence" . ,(workspace-request-sequence request))) fields))
(define (snapshot-reply type request snapshot)
  (reply type request (cons "snapshot" (wire-snapshot snapshot))))
(define (bounded-diagnostic value)
  (if (not (string? value)) ""
      (string-map (lambda (c) (if (char=? c #\nul) #\? c))
                  (substring value 0 (min 512 (string-length value))))))
(define (failed request code diagnostic)
  (reply "workspace-failed" request
         (cons "operation" (workspace-request-type request))
         (cons "code" code) (cons "diagnostic" (bounded-diagnostic diagnostic))))
(define (read-fields snapshot)
  `(("workspace_version" . ,(assq-ref snapshot 'workspace-version))
    ("source_digest" . ,(own (assq-ref snapshot 'source-digest)))
    ("activation_generation" . ,(assq-ref snapshot 'activation-generation))))

(define (make-workspace-delegate owner store handle generation access preview)
  (unless (and owner (workspace-store? store) (memq access '(author preview))
               (procedure? preview)) (reject 'invalid-construction))
  ;; Reuse the actual exact request bounds for trusted grant construction too.
  (make-workspace-request
   `(("type" . "workspace-read") ("protocol_version" . 1)
     ("grant_handle" . ,handle) ("grant_generation" . ,generation)
     ("operation_sequence" . 1)))
  (%make-delegate owner store (string-copy handle) generation access preview
                  (make-mutex) #f #f 0 1 #f #f #f))
(define (workspace-delegate-announce! delegate)
  (locked delegate
    (lambda ()
      (live! delegate)
      (when (delegate-announced? delegate) (reject 'already-announced))
      (set-announced! delegate #t)
      `(("type" . "workspace-ready") ("protocol_version" . 1)
        ("grant_handle" . ,(string-copy (delegate-handle delegate)))
        ("grant_generation" . ,(delegate-generation delegate))
        ("access" . ,(symbol->string (delegate-access delegate)))
        ("max_source_bytes" . 8192) ("max_pending_operations" . 1)))))
(define (workspace-delegate-phase delegate)
  (locked delegate
    (lambda ()
      (cond ((delegate-closed? delegate) 'closed)
            ((delegate-proposal delegate) 'confirming)
            ((delegate-task delegate)
             => (lambda (task)
                  (cond ((not (= (task-epoch task) (delegate-epoch delegate))) 'retiring)
                        ((eq? (task-state task) 'queued) 'pending)
                        (else 'running))))
            (else 'ready)))))
(define (workspace-delegate-receive! delegate owner request)
  (locked delegate
    (lambda ()
      (owner! delegate owner) (live! delegate)
      (unless (delegate-announced? delegate) (reject 'unannounced))
      (unless (workspace-request? request) (reject 'typed-request-required))
      (unless (and (string=? (field request "grant_handle") (delegate-handle delegate))
                   (= (field request "grant_generation") (delegate-generation delegate)))
        (reject 'wrong-grant))
      (when (or (delegate-task delegate) (delegate-proposal delegate)) (reject 'busy))
      (when (> (delegate-next delegate) workspace-protocol-max-counter)
        (reject 'sequence-exhausted))
      (unless (= (workspace-request-sequence request) (delegate-next delegate))
        (reject 'wrong-sequence))
      (set-next! delegate (+ 1 (delegate-next delegate)))
      (when (member (workspace-request-type request)
                    '("workspace-read" "workspace-save" "workspace-preview"))
        (set-ticket! delegate #f))
      (set-task! delegate (%make-task delegate (delegate-epoch delegate)
                                      request 'operation #f 'queued))
      'queued)))
(define (workspace-delegate-take-task! delegate)
  (locked delegate
    (lambda ()
      (let ((task (delegate-task delegate)))
        (and task (not (delegate-closed? delegate))
             (eq? (task-state task) 'queued)
             (begin (set-task-state! task 'taken) task))))))
(define (current-task? delegate task)
  (and (not (delegate-closed? delegate))
       (eq? task (delegate-task delegate))
       (= (task-epoch task) (delegate-epoch delegate))))
(define (require-version! request snapshot)
  (unless (= (field request "expected_version") (assq-ref snapshot 'workspace-version))
    (reject 'workspace-conflict)))
(define (require-activation! request snapshot)
  (unless (= (field request "expected_activation")
             (assq-ref snapshot 'activation-generation))
    (reject 'activation-conflict)))
(define (require-ticket! delegate task snapshot)
  (locked delegate
    (lambda ()
      (unless (current-task? delegate task) (reject 'retired))
      (unless (equal? (delegate-ticket delegate) (identity snapshot))
        (reject 'preview-required-for-this-draft)))))

(define (execute-task delegate task)
  (let* ((request (task-request task))
         (op (workspace-request-type request))
         (store (delegate-store delegate)))
    (define (response value) (cons 'reply value))
    (when (and (eq? (delegate-access delegate) 'preview)
               (not (member op '("workspace-read" "workspace-save"))))
      (reject 'access-denied))
    (let ((before (workspace-snapshot store)))
      (cond
       ((eq? (task-kind task) 'confirm)
        (require-version! request before) (require-activation! request before)
        (require-ticket! delegate task before)
        (unless (equal? (identity before) (identity (task-snapshot task)))
          (reject 'proposal-conflict))
        ;; Seal commits independently. A subsequent activation failure can retain
        ;; this immutable catalog entry/quota slot; only pointer + draft CAS is
        ;; atomic, not the combined seal-and-install operation.
        (let* ((revision (workspace-seal! store (field request "expected_version")))
               (after (workspace-activate-draft! store revision
                        (field request "expected_version") (field request "expected_activation"))))
          (response (reply "workspace-install-result" request
                           '("outcome" . "installed")
                           (cons "snapshot" (wire-snapshot after))))))
       ((string=? op "workspace-read")
        (response (snapshot-reply "workspace-snapshot" request before)))
       ((string=? op "workspace-save")
        (response (snapshot-reply "workspace-saved" request
                    (workspace-save! store (field request "expected_version") (field request "source")))))
       ((string=? op "workspace-preview")
        (require-version! request before)
        (let ((result ((delegate-preview delegate) (own (assq-ref before 'source)) (own before)
                       (lambda () (locked delegate (lambda () (not (current-task? delegate task))))))))
          (unless (and (list? result) (every pair? result) (eq? (assq-ref result 'status) 'ok))
            (throw 'workspace-preview-failed
                   (if (and (list? result) (every pair? result))
                       (assq-ref result 'diagnostic) "Preview failed")))
          (unless (equal? (identity before) (identity (workspace-snapshot store)))
            (reject 'workspace-changed-during-preview))
          (list 'preview before
                (append (reply "workspace-previewed" request) (read-fields before)
                        (list (cons "diagnostic" (bounded-diagnostic (assq-ref result 'diagnostic))))))))
       ((string=? op "workspace-install-propose")
        (require-version! request before) (require-activation! request before)
        (require-ticket! delegate task before)
        (list 'proposal before))
       ((string=? op "workspace-export")
        (response (append (reply "workspace-exported" request) (read-fields before)
                          (list (cons "exported_revision" (own (assq-ref before 'active-revision)))
                                (cons "artifact" (workspace-export store (assq-ref before 'active-revision)))))))
       (else (reject 'invalid-operation))))))

(define (workspace-delegate-run-task! delegate task)
  (let ((run?
         (locked delegate
           (lambda ()
             (unless (and (task? task) (eq? (task-delegate task) delegate)
                          (eq? (task-state task) 'taken)) (reject 'invalid-task))
             (set-task-state! task 'executing)
             (current-task? delegate task)))))
    ;; Starting a task is the execution admission point. Retirement after this
    ;; point suppresses its receipt, but cannot undo an admitted SQLite commit.
    ;; A retired preview sees cancelled? and must reap before it returns.
    (let ((outcome
           (if (not run?) '(stale)
               (catch #t
                 (lambda () (execute-task delegate task))
                 (lambda (key . args)
                   (cons 'reply
                         (failed (task-request task)
                           (cond ((eq? key 'workspace-preview-failed) "preview-failed")
                                 ((and (memq key '(workspace-error workspace-delegate-error))
                                       (pair? args) (symbol? (car args))) (symbol->string (car args)))
                                 (else "workspace-operation-failed"))
                           (if (and (eq? key 'workspace-preview-failed) (pair? args))
                               (car args) ""))))))))
      (locked delegate (lambda () (set-task-state! task 'finished)))
      (%make-completion task outcome))))
(define (workspace-delegate-complete! delegate completion)
  (locked delegate
    (lambda ()
      (unless (and (completion? completion)
                   (eq? (task-delegate (completion-task completion)) delegate))
        (reject 'invalid-completion))
      (let* ((task (completion-task completion)) (outcome (completion-outcome completion))
             (current? (current-task? delegate task)))
        (unless (eq? (task-state task) 'finished) (reject 'completion-already-consumed))
        (set-task-state! task 'consumed)
        (when (eq? task (delegate-task delegate)) (set-task! delegate #f))
        (and current?
             (case (car outcome)
               ((proposal)
                (set-proposal! delegate (%make-proposal delegate (delegate-epoch delegate)
                                                       (task-request task) (own (cadr outcome))))
                #f)
               ((preview)
                (set-ticket! delegate (own (identity (cadr outcome))))
                (own (caddr outcome)))
               ((reply)
                (when (eq? (task-kind task) 'confirm) (set-ticket! delegate #f))
                (own (cdr outcome)))
               (else #f)))))))
(define (workspace-delegate-proposal delegate)
  (locked delegate (lambda () (delegate-proposal delegate))))
(define (proposal! delegate owner proposal)
  (owner! delegate owner) (live! delegate)
  (unless (and (workspace-proposal? proposal)
               (eq? proposal (delegate-proposal delegate))
               (eq? (proposal-delegate proposal) delegate)
               (= (proposal-epoch proposal) (delegate-epoch delegate)))
    (reject 'stale-proposal)))
(define (workspace-delegate-confirm! delegate owner proposal)
  (locked delegate
    (lambda ()
      (proposal! delegate owner proposal)
      (set-proposal! delegate #f)
      (set-task! delegate (%make-task delegate (delegate-epoch delegate)
                                      (proposal-request proposal) 'confirm
                                      (own (proposal-snapshot proposal)) 'queued))
      'queued)))
(define (workspace-delegate-cancel! delegate owner proposal)
  (locked delegate
    (lambda ()
      (proposal! delegate owner proposal)
      (set-proposal! delegate #f) (set-ticket! delegate #f)
      ;; Cancellation reports the proposal's captured snapshot, not a fresh
      ;; durable read. The caller should read again before issuing another CAS.
      (reply "workspace-install-result" (proposal-request proposal)
             '("outcome" . "cancelled")
             (cons "snapshot" (wire-snapshot (proposal-snapshot proposal)))))))
(define (retire! delegate)
  (set-epoch! delegate (+ 1 (delegate-epoch delegate)))
  (set-ticket! delegate #f) (set-proposal! delegate #f)
  (let ((task (delegate-task delegate)))
    ;; Keep taken/executing tasks until their completion is explicitly consumed.
    ;; This prevents a new operation overlapping a retired backend call.
    (when (and task (eq? (task-state task) 'queued))
      (set-task-state! task 'cancelled) (set-task! delegate #f))))
(define (workspace-delegate-retire-view! delegate)
  (locked delegate (lambda () (live! delegate) (retire! delegate) 'retired)))
(define (workspace-delegate-close! delegate)
  (locked delegate
    (lambda ()
      (if (delegate-closed? delegate) 'already-closed
          (begin (set-closed! delegate #t) (retire! delegate) 'closed)))))
