-- Pure logic for the update path (doc/update-path.md): what a system
-- generation is on this device, how the extlinux menu is rendered from
-- the ledger, and the promote / prune / health decisions.  No I/O here;
-- wilkbook-generation.lua does the copying, linking and kexec.
local M = {}

M.ROOT_ARG = "root=PNGuixRoot"
M.BOOT_DIR = "/boot"
M.DTB_NAME = "rk3566-pinenote-v1.2.dtb"
M.TIMEOUT_DECISECONDS = 30

-- Guix's boot-parameters sexp for a system (S/parameters).  We need
-- exactly three things and read them with anchored patterns rather than
-- a reader: the kernel image, the initrd, and the kernel-arguments list.
function M.parse_parameters(text)
    local kernel = text:match('%(kernel%s+"([^"]+)"')
    local initrd = text:match('%(initrd%s+"([^"]+)"')
    local block = text:match('%(kernel%-arguments%s*%((.-)%)%s*%)')
    if not (kernel and initrd and block) then
        return nil, "parameters: missing kernel, initrd or kernel-arguments"
    end
    local args = {}
    for arg in block:gmatch('"([^"]*)"') do args[#args + 1] = arg end
    return { kernel = kernel, initrd = initrd, kernel_arguments = args }
end

-- The kernel command line for a generation: what Guix's own extlinux
-- generator would write, from the same boot parameters.  Used verbatim
-- for the menu entry AND for kexec, so a trial boot and a menu boot are
-- the same boot.
function M.append_for(system, kernel_arguments)
    local parts = { M.ROOT_ARG,
                    "gnu.system=" .. system,
                    "gnu.load=" .. system .. "/boot" }
    for _, a in ipairs(kernel_arguments) do parts[#parts + 1] = a end
    return table.concat(parts, " ")
end

function M.gen_dir(number)
    return string.format("%s/gen-%d", M.BOOT_DIR, number)
end

-- ledger: array of { number = N, system = S, append = "..." }.
-- Renders newest first; DEFAULT is the promoted generation, never
-- implicitly the newest -- that is the whole trial-then-promote idea.
function M.render_extlinux(ledger, default_number)
    local sorted = {}
    for _, g in ipairs(ledger) do sorted[#sorted + 1] = g end
    table.sort(sorted, function(a, b) return a.number > b.number end)
    local found = false
    for _, g in ipairs(sorted) do if g.number == default_number then found = true end end
    if not found then
        return nil, string.format("default generation %s is not in the ledger", tostring(default_number))
    end
    local out = {
        "# Generated by wilkbook-generation (doc/update-path.md).",
        "# One entry per kept system generation; DEFAULT is the PROMOTED one,",
        "# so a power-cycle after a failed trial boots the last known-good.",
        "MENU TITLE wilkbook generations",
        string.format("TIMEOUT %d", M.TIMEOUT_DECISECONDS),
        string.format("DEFAULT gen-%d", default_number),
        "",
    }
    for _, g in ipairs(sorted) do
        local dir = M.gen_dir(g.number)
        out[#out + 1] = string.format("LABEL gen-%d", g.number)
        out[#out + 1] = string.format("  MENU LABEL wilkbook generation %d%s", g.number,
                                      g.number == default_number and " (promoted)" or "")
        out[#out + 1] = string.format("  KERNEL %s/Image", dir)
        out[#out + 1] = string.format("  FDT %s/%s", dir, M.DTB_NAME)
        out[#out + 1] = string.format("  INITRD %s/initrd.cpio.gz", dir)
        out[#out + 1] = string.format("  APPEND %s", g.append)
        out[#out + 1] = ""
    end
    return table.concat(out, "\n")
end

function M.parse_default(extlinux_text)
    local n = extlinux_text and extlinux_text:match("\nDEFAULT gen%-(%d+)")
    return n and tonumber(n) or nil
end

function M.next_number(numbers)
    local max = 0
    for _, n in ipairs(numbers) do if n > max then max = n end end
    return max + 1
end

-- Which generations to delete: keep the `keep` newest, and ALWAYS keep
-- the promoted default, the booted one and every PINNED one, whatever
-- their age.  `pinned` is a set ({ [number] = true }): the generations an
-- operator marked known-good (a cold boot proved the tree) -- the newest
-- generations are the least proven, so "keep K newest" on its own
-- deletes the proven one as soon as it ages out of the window
-- (2026-09-04: the generation-16 deploy's KEEP=8 left generation 10,
-- the last cold-booted one, as the seventh of eight -- a deploy or two
-- from going).  A pinned generation is kept IN ADDITION to the `keep`
-- newest, exactly like the default and the booted one: a pin protects
-- one that has aged out of the window and changes nothing for one
-- still inside it.
function M.prune_plan(numbers, default_number, booted_number, keep, pinned)
    pinned = pinned or {}
    local sorted = {}
    for _, n in ipairs(numbers) do sorted[#sorted + 1] = n end
    table.sort(sorted, function(a, b) return a > b end)
    local plan = {}
    for i, n in ipairs(sorted) do
        if i > keep and n ~= default_number and n ~= booted_number and not pinned[n] then
            plan[#plan + 1] = n
        end
    end
    table.sort(plan)
    return plan
end

-- The pin marker's path: an empty file inside the generation's own
-- payload directory.  It lives with the payload so that it cannot
-- outlive the generation (prune removes the directory whole), needs no
-- parsing, and stays inside the helper's write set (/boot).
function M.pin_path(number)
    return M.gen_dir(number) .. "/pinned"
end

-- report: { current_system = S, broker_ready = bool, reader_started = bool }
function M.health_ok(report, expected_system)
    if report.current_system ~= expected_system then
        return false, string.format("running %s, expected %s",
                                    tostring(report.current_system), tostring(expected_system))
    end
    if not report.broker_ready then return false, "platform-controls broker not ready" end
    if not report.reader_started then return false, "reader-session not started" end
    return true, "ok"
end

-- The generation a running kernel booted, from its command line.
function M.booted_system(cmdline)
    return cmdline and cmdline:match("gnu%.system=(%S+)") or nil
end

return M
