;;; Prove that every project module resolves to the private compiled cache built
;;; from the already-authenticated source closure.
(use-modules (ice-9 match))

(define (fail message . details) (error message details))

(let ((arguments (cdr (command-line))))
  (unless (= (length arguments) 6)
    (fail "usage: verify-module-origins.scm JOIN NATIVE OBSERVER SESSION UI CACHE"))
  (match arguments
    ((join native observer session ui compiled)
     (let* ((join (canonicalize-path join))
            (native (canonicalize-path native))
             (observer (canonicalize-path observer))
             (session (canonicalize-path session))
            (ui (canonicalize-path ui))
            (compiled (canonicalize-path compiled))
            (protocol (string-append native "/accepted-inputs/book-protocol"))
            (state (string-append native "/accepted-inputs/state-protocol"))
            (backend (string-append native "/accepted-inputs/backend"))
            (expected
             `(((book-protocol)
                ,(string-append protocol "/book-protocol.scm")
                "book-protocol.go")
               ((book-protocol blocking-io)
                ,(string-append protocol "/book-protocol/blocking-io.scm")
                "book-protocol/blocking-io.go")
               ((book-state)
                ,(string-append backend "/book-state.scm")
                "book-state.go")
               ((book-state-operation-id)
                ,(string-append state "/book-state-operation-id.scm")
                "book-state-operation-id.go")
               ((book-state-protocol)
                ,(string-append state "/book-state-protocol.scm")
                "book-state-protocol.go")
               ((book-state-backend-adapter)
                ,(string-append state "/book-state-backend-adapter.scm")
                "book-state-backend-adapter.go")
               ((book-state-session-delegate)
                ,(string-append observer "/book-state-session-delegate.scm")
                "book-state-session-delegate.go")
                ((book-session)
                 ,(string-append session "/book-session.scm")
                "book-session.go")
               ((private-control)
                ,(string-append ui "/private-control.scm")
                "private-control.go")
               ((book-state-reader-bridge)
                ,(string-append join "/book-state-reader-bridge.scm")
                "book-state-reader-bridge.go")
               ((adversarial-book-common)
                ,(string-append join "/adversarial-book-common.scm")
                "adversarial-book-common.go"))))
       (for-each
        (lambda (entry)
          (let* ((name (car entry))
                 (wanted-source (cadr entry))
                 (relative-compiled (caddr entry))
                 (wanted-compiled
                  (string-append compiled "/" relative-compiled))
                 (loaded (resolve-interface name))
                 (actual-compiled
                  (search-path %load-compiled-path relative-compiled)))
            (unless (and (module? loaded)
                         actual-compiled
                         (file-exists? wanted-source)
                         (string=? (canonicalize-path actual-compiled)
                                   wanted-compiled))
              (fail "project module escaped authenticated source/cache"
                    name wanted-source wanted-compiled actual-compiled))
            (format #t "JOIN-MODULE-ORIGIN: ~s source=~a compiled=~a~%"
                    name wanted-source actual-compiled)))
        expected)))))
